el.result('pg19').feature('ptgr1').remove('legends', 0);
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').feature('ptgr2').remove('legends', 0);
model.result('pg19').run;
model.result('pg19').run;

model.label('Electrode_model_with_experiment_deLi_constant_thickness.mph');

model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').feature('tblp1').active(true);
model.result('pg19').run;
model.result('pg19').feature('tblp1').active(false);
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').feature('tblp6').active(false);
model.result('pg19').feature('tblp7').active(false);
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').feature('ptgr2').active(false);
model.result('pg19').run;
model.result('pg19').run;
model.result('pg55').run;
model.result('pg55').set('data', 'dset11');
model.result('pg55').setIndex('looplevel', [4], 2);
model.result('pg55').run;
model.result('pg55').setIndex('looplevel', [3], 2);
model.result('pg55').run;
model.result('pg37').run;
model.result('pg37').setIndex('looplevelindices', 100, 0);
model.result('pg37').run;
model.result('pg37').setIndex('looplevelindices', 60, 0);
model.result('pg37').run;
model.result('pg37').setIndex('looplevelindices', 50, 0);
model.result('pg37').run;
model.result('pg37').setIndex('looplevel', [3], 2);
model.result('pg37').run;
model.result('pg37').setIndex('looplevel', [4], 2);
model.result('pg37').run;
model.result('pg27').run;
model.result('pg27').setIndex('looplevelinput', 'manual', 2);
model.result('pg27').setIndex('looplevelinput', 'manualindices', 0);
model.result('pg27').setIndex('looplevelindices', 50, 0);
model.result('pg27').run;
model.result('pg27').setIndex('looplevelindices', 90, 0);
model.result('pg27').run;
model.result('pg27').setIndex('looplevelindices', 50, 0);
model.result('pg27').run;
model.result('pg29').run;
model.result('pg36').run;
model.result('pg30').run;
model.result('pg30').setIndex('looplevel', [4], 2);
model.result('pg30').run;
model.result('pg37').run;
model.result('pg37').setIndex('looplevelinput', 'all', 0);
model.result('pg37').run;
model.result('pg27').run;
model.result('pg35').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').feature('tblp1').active(true);
model.result('pg19').run;
model.result('pg19').feature('tblp1').set('scalingx', '1/0.82');
model.result('pg19').run;
model.result('pg19').run;
model.result.dataset('dset5').set('solution', 'none');
model.result.dataset('dset6').set('solution', 'none');
model.result.dataset('dset19').set('solution', 'none');
model.result.dataset('dset20').set('solution', 'none');
model.result.dataset('dset21').set('solution', 'none');
model.result.dataset('dset22').set('solution', 'none');

model.study.remove('std4');
model.study('std2').feature('param').setIndex('plistarr', '1 2 5 10 14', 0);

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.batch('p2').run('compute');

model.result('pg20').run;
model.result('pg19').run;
model.result('pg19').setIndex('looplevelinput', 'manual', 2);
model.result('pg19').run;
model.result('pg19').feature('ptgr1').setIndex('looplevel', [1 2 3 4 5], 2);
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').feature('tblp3').set('linecolor', 'cycle');
model.result('pg19').run;
model.result('pg19').feature('ptgr1').setIndex('looplevelinput', 'all', 2);
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').feature('ptgr1').setIndex('legends', '1C', 4);
model.result('pg19').feature('ptgr1').set('legendmethod', 'manual');
model.result('pg19').feature('ptgr1').setIndex('legends', '2C', 5);
model.result('pg19').feature('ptgr1').setIndex('legends', '5C', 6);
model.result('pg19').feature('ptgr1').setIndex('legends', '10C', 7);
model.result('pg19').feature('ptgr1').setIndex('legends', '15C', 8);
model.result('pg19').feature('ptgr1').remove('legends', 0);
model.result('pg19').feature('ptgr1').remove('legends', 0);
model.result('pg19').feature('ptgr1').remove('legends', 0);
model.result('pg19').feature('ptgr1').remove('legends', 0);
model.result('pg19').run;
model.result('pg19').run;
model.result('pg37').run;
model.result('pg37').setIndex('looplevel', [5], 2);
model.result('pg37').setIndex('looplevelinput', 'all', 2);
model.result('pg37').setIndex('looplevelinput', 'manualindices', 0);
model.result('pg37').run;
model.result('pg37').setIndex('looplevelinput', 'interp', 0);
model.result('pg37').setIndex('looplevelinput', 'manualindices', 0);
model.result('pg37').setIndex('looplevelinput', 'interp', 0);
model.result('pg37').setIndex('interp', '0.5*3600/C', 0);
model.result('pg37').run;
model.result('pg37').setIndex('interp', '0.1*3600/C', 0);
model.result('pg37').run;
model.result('pg37').run;
model.result('pg37').run;
model.result('pg37').run;
model.result('pg37').run;
model.result('pg37').run;
model.result('pg37').run;
model.result('pg37').setIndex('interp', '3600/C', 0);
model.result('pg37').run;
model.result('pg37').setIndex('looplevelinput', 'manualindices', 0);
model.result('pg37').run;
model.result('pg37').setIndex('looplevelindices', 75, 0);
model.result('pg37').run;
model.result('pg37').setIndex('looplevelinput', 'interp', 0);
model.result('pg37').run;
model.result('pg37').setIndex('interp', 360, 0);
model.result('pg37').run;
model.result('pg37').setIndex('interp', 1, 0);
model.result('pg37').setIndex('looplevelinput', 'manualindices', 0);
model.result('pg37').setIndex('looplevelindices', 1, 0);
model.result('pg37').run;
model.result('pg37').run;
model.result('pg37').setIndex('looplevelinput', 'interp', 0);
model.result('pg37').setIndex('interp', '3600/C', 0);
model.result('pg37').run;
model.result('pg37').setIndex('interp', '3600/C*0.5', 0);
model.result('pg37').run;
model.result('pg37').run;
model.result('pg37').setIndex('interp', '3600[s]/C*0.5', 0);
model.result('pg37').run;
model.result('pg37').run;
model.result('pg37').run;
model.result('pg37').run;
model.result('pg37').run;
model.result('pg37').setIndex('looplevelinput', 'manual', 2);
model.result('pg37').setIndex('looplevel', [3], 2);
model.result('pg37').setIndex('looplevel', [5], 2);
model.result('pg37').run;
model.result('pg37').setIndex('looplevel', [4], 2);
model.result('pg37').run;
model.result('pg37').setIndex('looplevel', [5], 2);
model.result('pg37').run;
model.result('pg19').run;

model.sol('sol4').feature('t1').set('tout', 'tlist');

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.batch('p2').run('compute');

model.result('pg20').run;
model.result('pg19').run;
model.result('pg37').run;
model.result('pg37').setIndex('looplevelinput', 'manualindices', 0);
model.result('pg37').setIndex('looplevelindices', 50, 0);
model.result('pg37').run;
model.result('pg37').setIndex('looplevelinput', 'all', 2);
model.result('pg37').run;
model.result('pg27').run;
model.result('pg27').setIndex('looplevel', [1 2 3 4 5], 2);
model.result('pg27').run;
model.result('pg27').setIndex('looplevelindices', 70, 0);
model.result('pg27').run;
model.result('pg27').setIndex('looplevelindices', 80, 0);
model.result('pg27').run;
model.result('pg27').setIndex('looplevelindices', 75, 0);
model.result('pg27').run;
model.result.create('pg57', 'PlotGroup1D');
model.result('pg57').run;
model.result.move('pg57', 16);
model.result('pg57').label('Macroscale stress of the domain');
model.result('pg27').run;
model.result('pg57').run;
model.result('pg57').create('lngr1', 'LineGraph');
model.result('pg57').feature('lngr1').selection.set([1]);
model.result('pg27').run;
model.result('pg27').run;
model.result('pg57').run;
model.result('pg27').run;
model.result('pg27').setIndex('looplevelinput', 'all', 2);
model.result('pg57').run;
model.result('pg57').feature('lngr1').set('expr', 'T_xx_M');
model.result('pg57').feature('lngr1').set('descr', '');
model.result('pg57').run;
model.result('pg57').run;
model.result('pg57').set('data', 'dset11');
model.result('pg57').setIndex('looplevelinput', 'manualindices', 0);
model.result('pg57').setIndex('looplevelindices', 50, 0);
model.result('pg57').run;
model.result('pg57').run;
model.result('pg57').feature('lngr1').set('expr', 'T_yy_M');
model.result('pg57').run;
model.result('pg27').run;
model.result('pg27').feature('lngr1').set('expr', 'comp2.linext1(comp2.T_RR)');
model.result('pg27').run;
model.result('pg27').run;
model.result('pg27').setIndex('looplevelindices', 50, 0);
model.result('pg27').run;
model.result('pg27').run;
model.result('pg27').feature('lngr1').set('expr', 'comp2.linext1(comp2.T_tt)');
model.result('pg27').run;
model.result('pg27').run;
model.result('pg27').run;
model.result('pg27').run;
model.result('pg27').run;
model.result('pg27').feature('lngr1').set('expr', 'comp2.linext1(comp2.T_h)');
model.result('pg27').run;
model.result('pg27').run;
model.result('pg27').run;
model.result('pg27').run;
model.result('pg27').run;
model.result('pg57').run;
model.result('pg27').run;
model.result('pg57').run;
model.result('pg53').set('window', 'window1');
model.result('pg53').run;
model.result('pg2').run;
model.result('pg2').set('data', 'dset12');
model.result('pg2').set('looplevel', {'interp' '1' '1'});
model.result('pg2').set('interp', {'3600/C'});
model.result('pg2').run;
model.result('pg2').set('looplevel', [51 1 1]);
model.result('pg2').run;
model.result('pg2').set('looplevel', [51 1 2]);
model.result('pg2').run;
model.result('pg2').run;
model.result('pg2').run;
model.result('pg2').set('looplevel', [51 1 3]);
model.result('pg2').run;
model.result('pg2').set('looplevel', [51 1 4]);
model.result('pg2').run;
model.result('pg2').run;
model.result('pg2').set('looplevel', [51 1 5]);
model.result('pg2').run;
model.result('pg2').run;
model.result('pg2').run;
model.result('pg2').run;
model.result('pg35').run;
model.result('pg35').setIndex('looplevelinput', 'all', 2);
model.result('pg35').setIndex('looplevelinput', 'manualindices', 0);
model.result('pg35').setIndex('looplevelindices', 75, 0);
model.result('pg35').run;
model.result('pg27').run;
model.result('pg57').run;
model.result('pg27').run;
model.result('pg35').run;
model.result.create('pg58', 'PlotGroup2D');
model.result('pg58').run;
model.result('pg58').label('Microscale stress');
model.result('pg58').set('data', 'dset12');
model.result('pg58').create('surf1', 'Surface');
model.result('pg58').feature('surf1').set('expr', 'T_RR');
model.result('pg58').feature('surf1').set('descr', '');
model.result('pg58').run;
model.result('pg58').run;
model.result.dataset.remove('dset19');
model.result.dataset.remove('dset20');
model.result.dataset.remove('dset21');
model.result.dataset.remove('dset22');
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').feature('surf1').set('expr', 'T_tt');
model.result('pg58').run;
model.result.dataset.remove('int2_ds1');
model.result.dataset.remove('int2_ds2');
model.result.dataset.remove('int10_ds1');
model.result('pg20').run;
model.result.remove('pg20');
model.result.dataset.create('cln2', 'CutLine2D');
model.result.dataset('cln2').set('method', 'pointdir');
model.result.dataset('cln2').set('genparaactive', true);
model.result.dataset('cln2').set('genparadist', '1e-5');
model.result.dataset('cln2').set('pddir', [0 1]);
model.result.dataset('cln2').set('genparadist', 'range(0,1.0e-5,5.0e-5)');
model.result.dataset('cln2').set('method', 'pointdir');
model.result.dataset('cln2').set('genparaactive', false);
model.result.dataset('cln2').set('method', 'twopoint');
model.result.dataset('cln2').set('genparaactive', true);
model.result.dataset('cln2').setIndex('genpoints', 0, 1, 0);
model.result.dataset('cln2').setIndex('genpoints', 1, 1, 1);
model.result.dataset.create('cln3', 'CutLine2D');
model.result.dataset.remove('cln3');
model.result.dataset('cln2').setIndex('genpoints', 0, 0, 0);
model.result.dataset('cln2').set('bounded', true);
model.result.dataset('cln2').set('genparadist', '1e-5');
model.result.dataset('cln2').set('genparaactive', false);
model.result.dataset.remove('cln2');
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').feature.remove('surf1');
model.result('pg58').run;
model.result('pg58').create('surf1', 'Surface');
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').feature('surf1').set('expr', 'T_RR');
model.result('pg58').feature('surf1').set('descr', '');
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').run;
model.result.dataset.create('grid1', 'Grid2D');
model.result.dataset('grid1').set('source', 'data');
model.result.dataset.remove('grid1');
model.result.dataset.create('cln2', 'CutLine2D');
model.result.dataset('cln2').setIndex('genpoints', 0, 1, 0);
model.result.dataset('cln2').setIndex('genpoints', 1, 1, 1);
model.result.dataset('cln2').set('method', 'pointdir');
model.result.dataset('cln2').set('pddir', [0 1]);
model.result.dataset('cln2').set('genparaactive', true);
model.result('pg58').run;
model.result.create('pg59', 'PlotGroup1D');
model.result('pg59').run;
model.result('pg59').set('data', 'cln1');
model.result.dataset('cln2').set('data', 'dset12');
model.result('pg59').run;
model.result('pg59').set('data', 'cln2');
model.result('pg59').setIndex('looplevelinput', 'manual', 2);
model.result('pg59').setIndex('looplevelinput', 'all', 2);
model.result('pg59').setIndex('looplevelinput', 'manualindices', 0);
model.result('pg59').setIndex('looplevelindices', 50, 0);
model.result('pg59').run;
model.result('pg59').create('lngr1', 'LineGraph');
model.result('pg59').run;
model.result('pg59').feature('lngr1').set('expr', 'T_RR');
model.result('pg59').feature('lngr1').set('descr', '');
model.result('pg59').run;
model.result('pg59').run;
model.result.dataset.create('pc1', 'ParCurve2D');
model.result.dataset.remove('pc1');
model.result('pg59').run;
model.result('pg58').run;
model.result('pg59').run;
model.result('pg59').run;
model.result.dataset('cln2').set('genparadist', 'range(0,1.0e-5,5.0e-5)');
model.result('pg59').feature('lngr1').set('evalmethodactive', false);
model.result('pg59').feature('lngr1').set('xdataevalmethodactive', false);
model.result('pg59').feature('lngr1').set('showlayerlocation', false);
model.result('pg59').feature('lngr1').set('showlocationinput', false);
model.result('pg59').feature('lngr1').set('olddataset', 'cln2');
model.result('pg59').feature('lngr1').set('evalmethodactive', false);
model.result('pg59').feature('lngr1').set('xdataevalmethodactive', false);
model.result('pg59').feature('lngr1').set('showlayerlocation', false);
model.result('pg59').feature('lngr1').set('showlocationinput', false);
model.result('pg59').feature('lngr1').set('olddataset', 'cln2');
model.result('pg59').feature('lngr1').set('evalmethodactive', false);
model.result('pg59').feature('lngr1').set('xdataevalmethodactive', false);
model.result('pg59').feature('lngr1').set('showlayerlocation', false);
model.result('pg59').feature('lngr1').set('showlocationinput', false);
model.result('pg59').feature('lngr1').set('olddataset', 'cln2');
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').setIndex('looplevelinput', 'manual', 2);
model.result('pg59').setIndex('looplevel', [2], 2);
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').feature('lngr1').set('legend', true);
model.result('pg59').feature('lngr1').set('autodescr', false);
model.result('pg59').feature('lngr1').set('autosolution', false);
model.result('pg59').feature('lngr1').set('cutline', 'cln2');
model.result('pg59').feature('lngr1').set('linefirst', [2.499999936844688E-5 0 0]);
model.result('pg59').feature('lngr1').set('linesecond', [2.499999936844688E-5 2.6899999738816405E-6 0]);
model.result('pg59').feature('lngr1').set('lineisinit', true);
model.result.dataset('cln2').set('method', 'twopoint');
model.result.dataset('cln2').set('genpoints', [2.5E-5 0; 2.5E-5 2.69E-6]);
model.result('pg59').feature('lngr1').set('cutmode', false);
model.result('pg59').run;
model.result('pg59').setIndex('looplevel', [3], 2);
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').feature('lngr1').set('autodescr', true);
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').feature('lngr1').set('cutline', 'cln2');
model.result.dataset('cln2').set('method', 'twopoint');
model.result.dataset('cln2').set('genpoints', [2.5E-5 0; 2.5E-5 2.69E-6]);
model.result('pg59').feature('lngr1').set('cutmode', false);
model.result.dataset('cln2').setIndex('genpoints', 0, 0, 0);
model.result.dataset('cln2').setIndex('genpoints', 0, 1, 0);
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').feature('lngr1').set('cutline', 'cln2');
model.result.dataset('cln2').set('method', 'twopoint');
model.result.dataset('cln2').set('genpoints', [2.5E-5 0; 2.5E-5 2.69E-6]);
model.result('pg59').feature('lngr1').set('cutmode', true);
model.result('pg59').feature('lngr1').set('linefirst', [-6.193045010149945E-8 1.4167080735205673E-6 -1]);
model.result.dataset('cln2').set('method', 'twopoint');
model.result.dataset('cln2').set('genpoints', [-6.193E-8 1.41672E-6; 2.5E-5 2.69E-6]);
model.result('pg59').feature('lngr1').set('linefirst', [8.148549568431918E-8 -8.915867510950193E-8 -1]);
model.result.dataset('cln2').set('method', 'twopoint');
model.result.dataset('cln2').set('genpoints', [8.14855E-8 -8.91588E-8; 2.5E-5 2.69E-6]);
model.result('pg59').feature('lngr1').set('linefirst', [9.777522791409865E-9 2.564036549301818E-6 -1]);
model.result.dataset('cln2').set('method', 'twopoint');
model.result.dataset('cln2').set('genpoints', [9.77752E-9 2.56404E-6; 2.5E-5 2.69E-6]);
model.result('pg59').feature('lngr1').set('linefirst', [9.777522791409865E-9 2.564036549301818E-6 -1]);
model.result.dataset('cln2').set('method', 'twopoint');
model.result.dataset('cln2').set('genpoints', [9.77752E-9 2.56404E-6; 2.5E-5 2.69E-6]);
model.result('pg59').feature('lngr1').set('linefirst', [-2.0534639588731807E-7 1.976741259568371E-7 -1]);
model.result.dataset('cln2').set('method', 'twopoint');
model.result.dataset('cln2').set('genpoints', [-2.05346E-7 1.97674E-7; 2.5E-5 2.69E-6]);
model.result('pg59').feature('lngr1').set('linefirst', [-4.921782874589553E-7 2.564036549301818E-6 -1]);
model.result.dataset('cln2').set('method', 'twopoint');
model.result.dataset('cln2').set('genpoints', [-4.92178E-7 2.56404E-6; 2.5E-5 2.69E-6]);
model.result('pg59').feature('lngr1').set('linefirst', [9.777522791409865E-9 -2.3257416614796966E-7 -1]);
model.result.dataset('cln2').set('method', 'twopoint');
model.result.dataset('cln2').set('genpoints', [9.77752E-9 -2.32574E-7; 2.5E-5 2.69E-6]);
model.result('pg59').feature('lngr1').set('inputmode', 'linesecond');
model.result('pg59').feature('lngr1').set('linesecond', [8.148549568431918E-8 2.564036549301818E-6 -1]);
model.result.dataset('cln2').set('method', 'twopoint');
model.result.dataset('cln2').set('genpoints', [9.77752E-9 -2.32574E-7; 8.14855E-8 2.56404E-6]);
model.result('pg59').feature('lngr1').set('cutmode', false);
model.result('pg59').feature('lngr1').set('cutline', 'cln2');
model.result.dataset('cln2').set('method', 'twopoint');
model.result.dataset('cln2').set('genpoints', [9.77752E-9 -2.32574E-7; 8.14855E-8 2.56404E-6]);
model.result('pg59').feature('lngr1').set('cutmode', false);
model.result('pg59').run;
model.result('pg59').run;
model.result.dataset('cln2').setIndex('genpoints', 0, 0, 0);
model.result.dataset('cln2').setIndex('genpoints', 0, 0, 1);
model.result.dataset('cln2').setIndex('genpoints', 0, 1, 0);
model.result.dataset('cln2').setIndex('genpoints', 1, 1, 1);
model.result.dataset('cln2').setIndex('genpoints', '2.69e-6', 1, 1);
model.result.dataset('cln2').setIndex('genpoints', '2.5e-6', 1, 1);
model.result.dataset('cln2').setIndex('genpoints', '2.7e-6', 1, 1);
model.result.dataset('cln2').set('genparadist', '1e-5');
model.result.dataset('cln2').set('method', 'pointdir');
model.result.dataset('cln2').set('genparadist', 'range(0,1.0e-5,5.0e-5)');
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').feature('lngr1').set('cutline', 'cln2');
model.result.dataset('cln2').set('method', 'twopoint');
model.result.dataset('cln2').set('genpoints', [9.77752E-9 -2.32574E-7; 8.14855E-8 2.56404E-6]);
model.result('pg59').feature('lngr1').set('cutmode', true);
model.result('pg59').feature('lngr1').set('inputmode', 'linesecond');
model.result('pg59').feature('lngr1').set('cutmode', false);
model.result('pg59').run;
model.result.dataset('cln2').setIndex('genpoints', 0, 0, 0);
model.result.dataset('cln2').setIndex('genpoints', 0, 0, 1);
model.result.dataset('cln2').setIndex('genpoints', 0, 1, 0);
model.result.dataset('cln2').setIndex('genpoints', 1, 1, 1);
model.result.dataset('cln2').set('genparadist', '1e-6');
model.result.dataset('cln2').set('snapping', 'none');
model.result.dataset('cln2').set('genparaactive', false);
model.result.dataset('cln2').setIndex('genpoints', '1e-5', 0, 0);
model.result.dataset('cln2').setIndex('genpoints', '1e-5', 1, 0);
model.result.dataset('cln2').set('genparaactive', true);
model.result.dataset('cln2').setIndex('genpoints', '5e-5', 0, 0);
model.result.dataset('cln2').setIndex('genpoints', '5e-5', 1, 0);
model.result.dataset('cln2').set('genparadist', 'range(0,1.0e-5,5.0e-5)');
model.result('pg59').run;
model.result('pg59').set('showlegends', true);
model.result('pg59').run;
model.result('pg59').feature('lngr1').set('autosolution', true);
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').set('legendpos', 'upperleft');
model.result('pg59').run;
model.result('pg58').run;
model.result('pg58').run;
model.result('pg59').run;
model.result.dataset('cln2').set('genparadist', 'range(1.0e-5,1.0e-5,5.0e-5)');
model.result('pg59').run;
model.result('pg59').setIndex('looplevel', [4], 2);
model.result('pg59').run;
model.result('pg59').setIndex('looplevel', [5], 2);
model.result('pg59').run;
model.result('pg58').run;
model.result('pg59').run;
model.result('pg29').run;
model.result('pg58').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').feature('lngr1').set('expr', 'T_tt');
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').setIndex('looplevelinput', 'all', 0);
model.result.dataset('cln2').set('genparaactive', false);
model.result('pg59').run;
model.result('pg58').run;
model.result('pg27').run;
model.result('pg57').run;
model.result('pg57').run;
model.result('pg57').feature('lngr1').set('linecolor', 'cycle');
model.result('pg57').feature('lngr1').set('linewidth', 2);
model.result('pg57').run;
model.result('pg57').feature('lngr1').set('legend', true);
model.result('pg57').feature('lngr1').set('legendmethod', 'manual');
model.result('pg57').feature('lngr1').setIndex('legends', 'C=1', 0);
model.result('pg57').feature('lngr1').setIndex('legends', 'C=2', 1);
model.result('pg57').feature('lngr1').setIndex('legends', 'C=5', 2);
model.result('pg57').feature('lngr1').setIndex('legends', 'C=10', 3);
model.result('pg57').feature('lngr1').setIndex('legends', 'C=14', 4);
model.result('pg57').run;
model.result('pg57').run;
model.result('pg57').feature('lngr1').set('legendmethod', 'automatic');
model.result('pg57').run;
model.result('pg57').setIndex('looplevelindices', 52, 0);
model.result('pg57').run;
model.result('pg57').setIndex('looplevelindices', 51, 0);
model.result('pg57').run;
model.result('pg57').run;
model.result('pg57').run;
model.result('pg57').set('legendpos', 'lowerright');
model.result('pg57').run;
model.result('pg57').feature('lngr1').set('legendmethod', 'manual');
model.result('pg57').feature('lngr1').setIndex('legends', 'C=1', 0);
model.result('pg57').feature('lngr1').setIndex('legends', 'C=2', 1);
model.result('pg57').feature('lngr1').setIndex('legends', 'C=5', 2);
model.result('pg57').feature('lngr1').setIndex('legends', 'C=10', 3);
model.result('pg57').feature('lngr1').setIndex('legends', 'C=14', 4);
model.result('pg57').run;
model.result('pg57').setIndex('looplevelindices', 76, 0);
model.result('pg57').run;
model.result('pg57').setIndex('looplevelindices', 90, 0);
model.result('pg57').run;
model.result('pg57').setIndex('looplevelindices', 10, 0);
model.result('pg57').run;
model.result('pg57').run;
model.result('pg57').feature('lngr1').set('expr', 'T_xx_M');
model.result('pg57').run;
model.result('pg57').run;
model.result('pg57').run;
model.result('pg57').feature('lngr1').set('expr', 'T_h_M');
model.result('pg57').run;
model.result('pg57').feature('lngr1').set('expr', 'T_yy_M');
model.result('pg57').run;
model.result('pg57').run;
model.result.dataset.create('cpt4', 'CutPoint1D');
model.result.dataset('cpt4').set('pointx', 'range(0,10,50)');
model.result.dataset('cpt4').set('showlayerlocation', false);
model.result.dataset('cpt4').set('showlocationinput', false);
model.result.dataset('cpt4').set('showlayerlocation', false);
model.result.dataset('cpt4').set('showlocationinput', false);
model.result.dataset('cpt4').set('showlayerlocation', false);
model.result.dataset('cpt4').set('showlocationinput', false);
model.result.create('pg60', 'PlotGroup1D');
model.result('pg60').run;
model.result('pg59').run;
model.result('pg60').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg58').run;
model.result('pg59').run;
model.result('pg59').label('Microscale stress at different position');
model.result('pg59').run;
model.result('pg60').run;
model.result.move('pg60', 14);
model.result('pg57').run;
model.result('pg59').run;
model.result.move('pg59', 13);
model.result('pg60').run;
model.result('pg60').label('Macroscale stress at different position');
model.result('pg57').run;
model.result('pg60').run;
model.result('pg60').create('ptgr1', 'PointGraph');
model.result('pg60').run;
model.result('pg60').set('data', 'cpt4');
model.result.dataset('cpt4').set('data', 'dset11');
model.result('pg60').run;
model.result('pg60').setIndex('looplevelinput', 'manual', 2);
model.result('pg60').setIndex('looplevel', [5], 2);
model.result('pg60').run;
model.result('pg60').run;
model.result('pg60').feature('ptgr1').set('expr', 'T_xx_M');
model.result('pg60').run;
model.result('pg60').feature('ptgr1').set('legend', true);
model.result('pg60').feature('ptgr1').set('legendmethod', 'manual');
model.result('pg60').feature('ptgr1').setIndex('legends', 'C=14, x=0', 0);
model.result('pg60').feature('ptgr1').setIndex('legends', 'C=14, x=10', 1);
model.result('pg60').feature('ptgr1').setIndex('legends', 'x=20', 2);
model.result('pg60').feature('ptgr1').setIndex('legends', 'x=10', 1);
model.result('pg60').feature('ptgr1').setIndex('legends', 'x=0', 0);
model.result('pg60').feature('ptgr1').setIndex('legends', 'x=30', 3);
model.result('pg60').feature('ptgr1').setIndex('legends', 'x=40', 4);
model.result('pg60').feature('ptgr1').setIndex('legends', 'x=50', 5);
model.result('pg60').run;
model.result('pg60').set('legendpos', 'upperleft');
model.result('pg60').run;
model.result('pg60').feature('ptgr1').set('expr', 'T_yy_M');
model.result('pg60').run;
model.result('pg60').run;
model.result('pg57').run;
model.result('pg60').run;
model.result('pg60').setIndex('looplevel', [4], 2);
model.result('pg60').run;
model.result('pg60').run;
model.result('pg60').feature('ptgr1').set('xdata', 'expr');
model.result('pg60').feature('ptgr1').set('xdataexpr', 't/3600[s]*C');
model.result('pg60').run;
model.result('pg60').feature('ptgr1').set('refine', 5);
model.result('pg60').run;
model.result('pg60').feature('ptgr1').set('refine', 1);
model.result('pg60').feature('ptgr1').set('linewidth', 2);
model.result('pg60').run;
model.result('pg60').run;
model.result('pg59').run;
model.result('pg59').setIndex('looplevel', [1], 2);
model.result('pg59').setIndex('looplevel', [1 2 3 4 5], 2);
model.result('pg59').setIndex('looplevelinput', 'manualindices', 0);
model.result('pg59').setIndex('looplevelindices', 51, 0);
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').feature('lngr1').set('linewidth', 2);
model.result('pg59').feature('lngr1').set('expr', 'T_RR');
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').feature('lngr1').set('legendmethod', 'manual');
model.result('pg59').feature('lngr1').setIndex('legends', 'C=1', 0);
model.result('pg59').feature('lngr1').setIndex('legends', 'C=2', 1);
model.result('pg59').feature('lngr1').setIndex('legends', 'C=5', 2);
model.result('pg59').feature('lngr1').setIndex('legends', 'C=10', 3);
model.result('pg59').feature('lngr1').setIndex('legends', 'C=14', 4);
model.result('pg59').run;
model.result('pg59').set('legendpos', 'lowerright');
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').set('axisactive', false);
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').feature('lngr1').set('expr', 'T_tt');
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').set('axislimits', false);
model.result('pg59').run;
model.result('pg59').feature('lngr1').set('xdata', 'expr');
model.result('pg59').feature('lngr1').set('xdataexpr', 'x');
model.result('pg59').feature('lngr1').set('xdataunit', [native2unicode(hex2dec({'00' 'b5'}), 'unicode') 'm']);
model.result('pg59').run;
model.result('pg59').feature('lngr1').set('xdata', 'expr');
model.result('pg59').feature('lngr1').set('xdataexpr', 'X');
model.result('pg59').run;
model.result('pg59').feature('lngr1').set('xdata', 'arc');
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').feature('lngr1').set('xdata', 'spacevar');
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').feature('lngr1').set('xdata', 'expr');
model.result('pg59').feature('lngr1').set('xdataexpr', 'cln2x');
model.result('pg59').run;
model.result('pg59').feature('lngr1').set('unit', 'GPa');
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').feature('lngr1').set('xdataexpr', 'cln2x/Rp');
model.result('pg59').run;
model.result('pg59').feature('lngr1').set('xdataexpr', 'cln2x/rp_primary');
model.result('pg59').run;
model.result('pg59').feature('lngr1').label('T_tt');
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').feature.copy('lngr2', 'pg59/lngr1');
model.result('pg59').run;
model.result('pg59').feature('lngr2').label('T_rr');
model.result('pg59').feature('lngr2').set('expr', 'T_RR');
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').feature('lngr1').active(false);
model.result('pg59').run;
model.result('pg59').feature('lngr1').set('legend', false);
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').feature('lngr2').set('legend', false);
model.result('pg59').run;
model.result('pg2').run;
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').run;
model.result.dataset.create('dset17', 'Solution');
model.result.dataset('dset17').set('solution', 'sol5');
model.result.dataset('dset17').set('comp', 'comp2');
model.result.dataset.remove('dset17');
model.result('pg58').run;

model.component('comp2').view('view3').axis.set('viewscaletype', 'manual');
model.component('comp2').view('view3').axis.set('xscale', '1/50');
model.component('comp2').view('view3').axis.set('yscale', '1/2.69');

model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').feature('surf1').set('unit', 'GPa');
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [71 1 5]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [1 1 5]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [11 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [21 1 4]);
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [31 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [41 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [51 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [61 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [71 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [81 1 4]);
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [91 1 4]);
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').feature('surf1').set('colortable', 'Viridis');
model.result('pg58').feature('surf1').set('coloring', 'gradient');
model.result('pg58').feature('surf1').set('topcolor', 'cyan');
model.result('pg58').feature('surf1').set('bottomcolor', 'gray');
model.result('pg58').feature('surf1').set('topcolor', 'gray');
model.result('pg58').feature('surf1').set('bottomcolor', 'cyan');
model.result('pg58').feature('surf1').set('coloring', 'colortable');
model.result('pg58').feature('surf1').set('colortable', 'JupiterAuroraBorealis');
model.result('pg58').feature('surf1').set('colortabletrans', 'nonlinearsymmetric');
model.result('pg58').feature('surf1').set('colortable', 'WaveLight');
model.result('pg58').feature('surf1').set('colorcalibration', -0.5);
model.result('pg58').feature('surf1').set('colortabletrans', 'reverse');
model.result('pg58').feature('surf1').set('colortable', 'JupiterAuroraBorealis');
model.result('pg58').feature('surf1').set('colortabletrans', 'none');
model.result('pg58').run;
model.result('pg58').set('looplevel', [91 1 5]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [8 1 5]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [16 1 5]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [29 1 5]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [57 1 5]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [64 1 5]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [71 1 5]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [78 1 5]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [88 1 5]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [84 1 5]);
model.result('pg58').run;
model.result('pg38').run;
model.result('pg38').setIndex('looplevel', [5], 2);
model.result('pg38').run;
model.result('pg38').run;
model.result('pg38').feature('lngr1').set('resolution', 'finer');
model.result('pg38').run;
model.result('pg38').feature('lngr1').set('threshold', 'none');
model.result('pg38').feature('lngr1').set('recover', 'pprint');
model.result('pg38').run;
model.result('pg38').run;
model.result('pg38').feature('lngr1').set('recover', 'ppr');
model.result('pg38').run;
model.result('pg38').feature('lngr1').set('threshold', 'manual');
model.result('pg38').run;
model.result('pg38').feature('lngr1').set('resolution', 'extrafine');
model.result.dataset.create('cln3', 'CutLine2D');
model.result.dataset('cln3').set('data', 'dset2');
model.result('pg38').feature('lngr1').set('cutline', 'cln3');
model.result('pg38').feature('lngr1').set('linefirst', [2.499999936844688E-5 0 0]);
model.result('pg38').feature('lngr1').set('linesecond', [2.499999936844688E-5 2.6899999738816405E-6 0]);
model.result('pg38').feature('lngr1').set('lineisinit', true);
model.result.dataset('cln3').set('method', 'twopoint');
model.result.dataset('cln3').set('genpoints', [2.5E-5 0; 2.5E-5 2.69E-6]);
model.result('pg38').feature('lngr1').set('cutmode', true);
model.result('pg38').feature('lngr1').set('listen', false);
model.result('pg38').feature('lngr1').set('data', 'cln3');
model.result('pg38').feature('lngr1').set('listen', true);
model.result('pg38').feature('lngr1').set('cutmode', false);
model.result('pg38').run;
model.result('pg38').run;
model.result('pg38').feature('lngr1').set('data', 'parent');
model.result('pg38').run;
model.result('pg38').feature('lngr1').selection.set([1]);
model.result('pg38').run;
model.result('pg35').run;
model.result('pg38').run;
model.result('pg38').setIndex('looplevel', [4], 2);
model.result('pg38').run;
model.result('pg38').setIndex('looplevel', [3], 2);
model.result('pg38').run;
model.result('pg38').setIndex('looplevel', [2], 2);
model.result('pg38').run;
model.result('pg38').setIndex('looplevel', [5], 2);
model.result('pg38').run;
model.result('pg38').setIndex('looplevelinput', 'manualindices', 0);
model.result('pg38').setIndex('looplevelindices', 'range(80,1,90)', 0);
model.result('pg38').run;
model.result('pg38').setIndex('looplevelindices', 'range(70,1,90)', 0);
model.result('pg38').run;
model.result('pg38').setIndex('looplevelindices', 'range(60,1,90)', 0);
model.result('pg38').run;
model.result('pg38').setIndex('looplevelindices', 'range(60,1,70)', 0);
model.result('pg38').run;
model.result('pg38').setIndex('looplevelindices', 'range(40,1,60)', 0);
model.result('pg38').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [8 1 5]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [13 1 5]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [19 1 5]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [30 1 5]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [44 1 5]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [52 1 5]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [65 1 5]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [57 1 5]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [52 1 5]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [54 1 5]);
model.result('pg58').run;
model.result('pg38').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [2 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [6 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [11 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [16 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [21 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [26 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [31 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [36 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [46 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [51 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [52 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [55 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [58 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [61 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [66 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [72 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [76 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [83 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [87 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [90 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [92 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [95 1 4]);
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').feature('surf1').set('expr', 'T_tt');
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [6 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [11 1 4]);
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').feature('surf1').set('colortable', 'Rainbow');
model.result('pg58').feature('surf1').set('expr', 'T_h');
model.result('pg58').run;
model.result('pg58').feature('surf1').set('expr', 'T_tt');
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [16 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [26 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [51 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [56 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [66 1 4]);
model.result('pg58').run;
model.result('pg37').run;
model.result('pg38').run;
model.result('pg38').setIndex('looplevel', [3], 2);
model.result('pg38').setIndex('looplevel', [4], 2);
model.result('pg38').setIndex('looplevel', [5], 2);
model.result('pg38').setIndex('looplevel', [4], 2);
model.result('pg38').run;
model.result('pg38').setIndex('looplevelindices', 'range(1,1,20)', 0);
model.result('pg38').run;
model.result('pg58').run;
model.result.move('pg58', 24);
model.result('pg38').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [11 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [16 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [31 1 4]);
model.result('pg58').run;
model.result('pg38').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [41 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [21 1 4]);
model.result('pg58').run;
model.result('pg38').run;
model.result('pg58').run;
model.result('pg38').run;
model.result('pg38').setIndex('looplevelindices', 'range(20,1,30)', 0);
model.result('pg38').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [26 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [31 1 4]);
model.result('pg58').run;
model.result('pg38').run;
model.result('pg38').setIndex('looplevelindices', 'range(30,1,40)', 0);
model.result('pg38').run;
model.result('pg58').run;
model.result('pg38').run;
model.result('pg38').setIndex('looplevelindices', 'range(35,1,40)', 0);
model.result('pg38').run;
model.result('pg38').setIndex('looplevelindices', 'range(30,1,35)', 0);
model.result('pg38').run;
model.result('pg38').setIndex('looplevelindices', 'range(35,1,40)', 0);
model.result('pg38').run;
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [36 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [41 1 4]);
model.result('pg58').run;
model.result('pg38').run;
model.result('pg38').setIndex('looplevelindices', 'range(40,1,50)', 0);
model.result('pg38').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [46 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [49 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [51 1 4]);
model.result('pg58').run;
model.result('pg38').run;
model.result('pg58').run;
model.result('pg38').run;
model.result('pg38').setIndex('looplevelindices', 50, 0);
model.result('pg38').run;
model.result('pg38').setIndex('looplevelindices', 'range(40,1,50)', 0);
model.result('pg38').run;
model.result('pg38').setIndex('looplevelindices', 'range(51,1,60)', 0);
model.result('pg38').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [54 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [56 1 4]);
model.result('pg58').run;
model.result('pg38').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [59 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [61 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [64 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [69 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [75 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [81 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [87 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [90 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [92 1 4]);
model.result('pg58').run;
model.result('pg38').run;
model.result('pg38').set('showlegends', true);
model.result('pg58').run;
model.result('pg58').set('looplevel', [51 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [52 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [53 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [54 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [55 1 4]);
model.result('pg58').run;
model.result('pg38').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [56 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [58 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [59 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [61 1 4]);
model.result('pg58').run;
model.result('pg38').run;
model.result('pg38').setIndex('looplevelindices', 'range(61,1,70)', 0);
model.result('pg38').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [62 1 4]);
model.result('pg58').run;
model.result('pg38').run;
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').run;
model.result('pg38').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [66 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [70 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [71 1 4]);
model.result('pg58').run;
model.result('pg38').run;
model.result('pg38').setIndex('looplevelindices', 'range(71,1,80)', 0);
model.result('pg38').run;
model.result('pg58').run;
model.result('pg38').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [75 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [79 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [81 1 4]);
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').feature('surf1').set('expr', 'T_h');
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').feature('surf1').set('expr', 'T_RR');
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [51 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [52 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [53 1 4]);
model.result('pg58').run;
model.result('pg38').run;
model.result('pg38').setIndex('looplevelindices', 'range(51,1,60)', 0);
model.result('pg38').run;
model.result('pg58').run;
model.result('pg38').run;
model.result('pg58').run;
model.result('pg38').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [54 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [55 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [56 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [57 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [58 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [59 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [60 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [61 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [62 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [64 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [66 1 4]);
model.result('pg58').run;
model.result('pg38').run;
model.result('pg37').run;
model.result('pg38').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [51 1 4]);
model.result('pg58').run;
model.result('pg38').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [52 1 4]);
model.result('pg58').run;
model.result('pg38').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [53 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [54 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [55 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [56 1 4]);
model.result('pg58').run;
model.result('pg38').run;
model.result('pg38').setIndex('looplevelindices', 'range(61,1,70)', 0);
model.result('pg38').run;
model.result('pg38').setIndex('looplevelindices', 'range(51,1,70)', 0);
model.result('pg38').run;
model.result('pg38').set('showlegends', false);
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [1 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [51 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [61 1 4]);
model.result('pg58').run;
model.result('pg38').run;
model.result('pg38').setIndex('looplevelindices', 'range(71,1,80)', 0);
model.result('pg38').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [66 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [71 1 4]);
model.result('pg58').run;
model.result('pg38').run;
model.result('pg58').run;
model.result('pg38').run;
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').feature('surf1').set('expr', 'T_tt');
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').run;
model.result('pg38').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [76 1 4]);
model.result('pg58').run;
model.resul