ln3').set('genpoints', [2.5E-5 0; 2.5E-5 2.69E-6]);
model.result('pg59').feature('lngr3').set('cutmode', false);
model.result('pg59').run;
model.result('pg59').feature('lngr3').setIndex('looplevelinput', 'all', 0);
model.result('pg59').feature('lngr3').setIndex('looplevelinput', 'manualindices', 0);
model.result('pg59').feature('lngr3').setIndex('looplevelinput', 'manual', 1);
model.result('pg59').run;
model.result('pg59').feature('lngr3').set('legend', true);
model.result.dataset('cln2').set('genparaactive', false);
model.result.dataset('cln3').setIndex('genpoints', '5E-5', 0, 0);
model.result.dataset('cln3').setIndex('genpoints', '5E-5', 1, 0);
model.result.dataset('cln3').set('genparaactive', false);
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').feature('lngr3').set('unit', 'GPa');
model.result('pg59').run;
model.result('pg59').feature('lngr3').set('legendmethod', 'manual');
model.result('pg59').feature('lngr3').setIndex('legends', '20C', 0);
model.result('pg59').run;
model.result('pg59').feature('lngr1').setIndex('legends', '1C', 0);
model.result('pg59').feature('lngr1').setIndex('legends', '2C', 1);
model.result('pg59').feature('lngr1').setIndex('legends', '5C', 2);
model.result('pg59').feature('lngr1').setIndex('legends', '10C', 3);
model.result('pg59').feature('lngr1').setIndex('legends', '14C', 4);
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').feature('lngr3').set('linewidth', 2);
model.result('pg59').run;
model.result('pg59').feature('lngr1').set('xdata', 'expr');
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').feature('lngr3').set('xdata', 'expr');
model.result('pg59').feature('lngr3').set('xdataexpr', 'cln3x/rp_primary');
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').feature('lngr3').setIndex('looplevelindices', 50, 0);
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').feature('lngr2').label('T_rr_1');
model.result('pg59').run;
model.result('pg59').create('lngr4', 'LineGraph');
model.result('pg59').feature('lngr4').set('data', 'cln3');
model.result('pg59').run;
model.result('pg59').feature('lngr2').set('data', 'cln2');
model.result('pg59').feature('lngr2').setIndex('looplevelinput', 'manualindices', 0);
model.result('pg59').feature('lngr2').setIndex('looplevelindices', 51, 0);
model.result('pg59').run;
model.result('pg59').feature('lngr4').label('T_rr_2');
model.result('pg59').feature('lngr4').set('expr', 'T_RR');
model.result('pg59').feature('lngr4').set('unit', 'GPa');
model.result('pg59').feature('lngr4').active(false);
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').feature('lngr4').setIndex('looplevelinput', 'manualindices', 0);
model.result('pg59').feature('lngr4').setIndex('looplevelindices', 51, 0);
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').feature('lngr4').set('xdata', 'expr');
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').feature('lngr4').set('xdataexpr', 'cln3x/rp_primary');
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').feature('lngr3').set('legendmethod', 'automatic');
model.result('pg59').feature('lngr3').setIndex('looplevelindices', 51, 0);
model.result('pg59').run;
model.result('pg59').feature('lngr3').set('legendmethod', 'manual');
model.result('pg59').feature('lngr3').setIndex('legends', '20C', 0);
model.result('pg59').run;
model.result('pg60').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').feature('lngr1').active(false);
model.result('pg59').feature('lngr3').active(false);
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').feature('lngr2').active(true);
model.result('pg59').feature('lngr4').active(true);
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').feature('lngr4').set('linewidth', 2);
model.result('pg59').feature('lngr4').set('legend', true);
model.result('pg59').feature('lngr4').set('legendmethod', 'manual');
model.result('pg59').feature('lngr4').setIndex('legends', '20C', 0);
model.result('pg59').run;
model.result('pg59').feature('lngr2').setIndex('legends', '1C', 0);
model.result('pg59').feature('lngr2').setIndex('legends', '2C', 1);
model.result('pg59').feature('lngr2').setIndex('legends', '5C', 2);
model.result('pg59').feature('lngr2').setIndex('legends', '10C', 3);
model.result('pg59').feature('lngr2').setIndex('legends', '14C', 4);
model.result('pg59').run;
model.result('pg59').set('showlegends', false);
model.result('pg59').run;
model.result('pg59').feature('lngr2').active(false);
model.result('pg59').feature('lngr4').active(false);
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').feature('lngr1').active(true);
model.result('pg59').feature('lngr3').active(true);
model.result('pg59').run;
model.result('pg59').run;
model.result('pg38').run;
model.result('pg38').setIndex('looplevel', [5], 2);
model.result('pg38').run;
model.result('pg38').set('data', 'dset19');
model.result('pg38').run;
model.result('pg38').run;
model.result('pg58').run;
model.result('pg58').set('data', 'dset20');
model.result('pg58').set('looplevel', [2 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [4 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [6 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [11 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [16 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [21 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [26 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [31 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [36 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [41 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [46 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [51 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [56 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [61 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [66 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [6 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [11 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [16 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [21 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [26 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [31 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [36 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [41 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [46 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [51 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [56 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [61 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [66 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [69 1]);
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').feature('surf1').set('expr', 'T_tt');
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [6 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [11 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [16 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [21 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [26 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [31 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [36 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [41 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [46 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [51 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [56 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [61 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [66 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [69 1]);
model.result('pg58').run;
model.result('pg38').run;
model.result('pg38').run;
model.result.export.create('plot4', 'pg38', 'lngr1', 'Plot');
model.result.export('plot4').set('filename', 'F:\group\Research\Mechanic-electrochemic coupling method\Network model for electrode\Rate performance test 2 G5\j_react_20C.txt');
model.result.export('plot4').run;
model.result('pg38').run;
model.result('pg38').setIndex('looplevelinput', 'first', 0);
model.result('pg38').run;
model.result('pg38').setIndex('looplevelinput', 'last', 0);
model.result('pg38').run;
model.result('pg38').setIndex('looplevelinput', 'all', 0);
model.result('pg38').run;
model.result('pg38').setIndex('looplevelinput', 'last', 0);
model.result('pg38').run;
model.result('pg38').setIndex('looplevelinput', 'all', 0);
model.result('pg58').run;
model.result('pg37').run;
model.result('pg37').setIndex('looplevelinput', 'all', 0);
model.result('pg37').setIndex('looplevelinput', 'manual', 2);
model.result('pg37').setIndex('looplevel', [4], 2);
model.result('pg37').run;
model.result('pg37').run;
model.result.export.create('plot5', 'pg37', 'lngr1', 'Plot');
model.result.export.remove('plot2');
model.result.export.remove('plot3');
model.result.export.remove('plot4');
model.result.export.remove('plot5');
model.result.export('plot1').set('plotgroup', 'pg37');
model.result.export('plot1').set('filename', 'F:\group\Research\Mechanic-electrochemic coupling method\Network model for electrode\Rate performance test 2 G5\Porosity_10C.txt');
model.result.export('plot1').run;
model.result('pg37').run;
model.result('pg37').set('data', 'dset19');
model.result('pg37').run;
model.result.export('plot1').set('filename', 'F:\group\Research\Mechanic-electrochemic coupling method\Network model for electrode\Rate performance test 2 G5\Porosity_20C.txt');
model.result.export('plot1').run;
model.result('pg37').run;
model.result('pg45').run;
model.result('pg45').set('data', 'dset19');
model.result('pg45').run;
model.result('pg45').set('data', 'dset11');
model.result('pg45').run;
model.result('pg45').set('data', 'dset19');
model.result('pg45').run;
model.result('pg45').run;
model.result('pg45').run;
model.result('pg45').set('data', 'dset11');
model.result('pg45').setIndex('looplevelinput', 'manual', 2);
model.result('pg45').setIndex('looplevel', [2], 2);
model.result('pg45').run;
model.result('pg45').setIndex('looplevel', [3], 2);
model.result('pg45').run;
model.result('pg45').setIndex('looplevel', [4], 2);
model.result('pg45').run;
model.result('pg45').setIndex('looplevel', [5], 2);
model.result('pg45').run;
model.result('pg45').set('data', 'dset19');
model.result('pg45').setIndex('looplevelinput', 'manual', 1);
model.result('pg45').run;
model.result('pg45').run;
model.result('pg45').setIndex('looplevelinput', 'manualindices', 0);
model.result('pg45').setIndex('looplevelindices', 1, 0);
model.result('pg45').run;
model.result('pg45').setIndex('looplevelindices', 10, 0);
model.result('pg45').run;
model.result('pg45').setIndex('looplevelindices', 15, 0);
model.result('pg45').run;
model.result('pg37').run;
model.result('pg37').run;
model.result('pg37').run;
model.result('pg37').setIndex('looplevelinput', 'manualindices', 0);
model.result('pg37').setIndex('looplevelindices', 1, 0);
model.result('pg37').run;
model.result('pg37').setIndex('looplevelindices', 10, 0);
model.result('pg37').run;
model.result('pg37').setIndex('looplevelindices', 20, 0);
model.result('pg37').run;
model.result('pg37').setIndex('looplevelindices', 30, 0);
model.result('pg37').run;
model.result('pg37').setIndex('looplevelindices', 40, 0);
model.result('pg37').run;
model.result('pg37').setIndex('looplevelindices', 50, 0);
model.result('pg37').run;
model.result('pg37').setIndex('looplevelinput', 'all', 0);
model.result('pg37').run;
model.result('pg45').run;
model.result('pg45').setIndex('looplevelinput', 'all', 0);
model.result('pg45').run;
model.result('pg45').set('data', 'dset11');
model.result('pg45').run;
model.result('pg45').set('data', 'dset19');
model.result('pg45').run;
model.result('pg37').run;
model.result('pg45').run;
model.result('pg45').setIndex('looplevelinput', 'manual', 1);
model.result('pg45').setIndex('looplevelinput', 'all', 1);
model.result('pg45').set('data', 'dset11');
model.result('pg45').setIndex('looplevelinput', 'manual', 2);
model.result('pg45').setIndex('looplevel', [5], 2);
model.result('pg45').run;
model.result('pg45').setIndex('looplevel', [4], 2);
model.result('pg45').run;
model.result('pg45').set('data', 'dset20');
model.result('pg45').run;
model.result('pg45').set('data', 'dset19');
model.result('pg45').run;
model.result('pg45').run;
model.result('pg45').run;
model.result('pg45').run;
model.result('pg45').feature('lngr1').selection.set([1]);
model.result('pg45').run;
model.result('pg37').run;
model.result('pg37').set('showlegends', false);
model.result('pg45').run;
model.result('pg45').setIndex('looplevelinput', 'last', 0);
model.result('pg45').run;
model.result('pg45').setIndex('looplevelinput', 'all', 0);
model.result('pg45').run;
model.result('pg45').run;
model.result.export('plot1').set('plotgroup', 'pg45');
model.result.export('plot1').set('filename', 'F:\group\Research\Mechanic-electrochemic coupling method\Network model for electrode\Rate performance test 2 G5\uM_20C.txt');
model.result.export('plot1').run;
model.result('pg45').run;
model.result('pg37').run;
model.result('pg35').run;
model.result('pg35').set('data', 'dset19');
model.result('pg35').run;
model.result.export('plot1').set('plotgroup', 'pg35');
model.result.export('plot1').set('filename', 'F:\group\Research\Mechanic-electrochemic coupling method\Network model for electrode\Rate performance test 2 G5\Rp_20C.txt');
model.result.export('plot1').run;
model.result.export('plot1').set('plotgroup', 'pg55');
model.result('pg35').run;
model.result('pg55').run;
model.result.export('plot1').set('filename', 'F:\group\Research\Mechanic-electrochemic coupling method\Network model for electrode\Rate performance test 2 G5\cl_20C.txt');
model.result.export('plot1').run;
model.result('pg55').run;
model.result('pg55').set('data', 'dset11');
model.result('pg55').setIndex('looplevelinput', 'manual', 2);
model.result('pg55').setIndex('looplevel', [3], 2);
model.result('pg55').setIndex('looplevel', [4], 2);
model.result('pg55').run;
model.result('pg55').run;
model.result('pg55').feature('lngr1').selection.set([1]);
model.result('pg55').run;
model.result('pg55').run;
model.result('pg55').setIndex('looplevel', [5], 2);
model.result('pg55').run;
model.result('pg55').setIndex('looplevel', [4], 2);
model.result('pg55').run;
model.result.export('plot1').set('filename', 'F:\group\Research\Mechanic-electrochemic coupling method\Network model for electrode\Rate performance test 2 G5\cl_10C.txt');
model.result.export('plot1').run;
model.result('pg55').run;
model.result('pg37').run;
model.result('pg37').set('data', 'dset11');
model.result('pg37').run;
model.result('pg37').setIndex('looplevelinput', 'manual', 2);
model.result('pg37').setIndex('looplevel', [4], 2);
model.result('pg37').run;
model.result('pg37').setIndex('looplevel', [5], 2);
model.result('pg37').run;
model.result('pg37').setIndex('looplevel', [4], 2);
model.result('pg37').run;
model.result('pg37').setIndex('looplevelinput', 'manualindices', 0);
model.result('pg37').setIndex('looplevelindices', 51, 0);
model.result('pg37').run;
model.result('pg37').setIndex('looplevelindices', 31, 0);
model.result('pg37').run;
model.result('pg19').run;
model.result('pg24').run;
model.result('pg30').run;
model.result('pg55').run;
model.result('pg27').run;
model.result('pg27').setIndex('looplevelindices', 51, 0);
model.result('pg27').setIndex('looplevelinput', 'first', 2);
model.result('pg27').setIndex('looplevelinput', 'manual', 2);
model.result('pg27').setIndex('looplevelinput', 'all', 0);
model.result('pg59').run;
model.result('pg60').run;
model.result('pg57').run;
model.result('pg57').run;
model.result('pg60').run;
model.result('pg60').setIndex('looplevelinput', 'all', 2);
model.result('pg60').run;
model.result('pg60').setIndex('looplevelinput', 'manual', 2);
model.result('pg60').run;
model.result.dataset('cpt4').set('data', 'dset19');
model.result('pg60').run;
model.result('pg60').run;
model.result('pg60').run;
model.result('pg60').feature('ptgr1').set('expr', 'T_yy_M');
model.result('pg60').run;
model.result('pg59').run;
model.result('pg57').run;
model.result('pg60').run;
model.result('pg60').run;
model.result('pg60').feature('ptgr1').set('expr', 'T_xx_M');
model.result('pg60').run;
model.result('pg60').feature('ptgr1').set('expr', 'T_yy_M');
model.result('pg60').run;
model.result('pg57').run;
model.result('pg57').setIndex('looplevel', [5], 2);
model.result('pg57').run;
model.result('pg57').set('data', 'dset19');
model.result('pg57').run;
model.result('pg59').run;
model.result('pg60').run;
model.result('pg60').run;
model.result('pg60').run;
model.result('pg59').run;
model.result('pg57').run;
model.result('pg57').run;
model.result.export('plot1').set('plotgroup', 'pg57');
model.result.export('plot1').set('filename', 'F:\group\Research\Mechanic-electrochemic coupling method\Network model for electrode\Rate performance test 2 G5\T_yy_M_20C.txt');
model.result.export('plot1').run;
model.result('pg57').run;
model.result('pg57').set('data', 'dset11');
model.result('pg57').setIndex('looplevelinput', 'manual', 2);
model.result('pg57').setIndex('looplevel', [4], 2);
model.result('pg57').run;
model.result.export('plot1').set('filename', 'F:\group\Research\Mechanic-electrochemic coupling method\Network model for electrode\Rate performance test 2 G5\T_yy_M_10C.txt');
model.result.export('plot1').run;
model.result('pg57').run;
model.result('pg57').run;
model.result('pg57').feature('lngr1').set('expr', 'T_xx_M');
model.result('pg57').run;
model.result.export('plot1').set('filename', 'F:\group\Research\Mechanic-electrochemic coupling method\Network model for electrode\Rate performance test 2 G5\T_xx_M_10C.txt');
model.result.export('plot1').run;
model.result('pg57').run;
model.result('pg57').run;
model.result('pg57').set('data', 'dset19');
model.result('pg57').run;
model.result.export('plot1').set('filename', 'F:\group\Research\Mechanic-electrochemic coupling method\Network model for electrode\Rate performance test 2 G5\T_xx_M_20C.txt');
model.result.export('plot1').run;
model.result('pg57').run;
model.result('pg60').run;
model.result('pg38').run;
model.result('pg38').set('data', 'dset11');
model.result('pg38').setIndex('looplevelinput', 'manual', 2);
model.result('pg38').setIndex('looplevel', [3], 2);
model.result('pg38').run;
model.result('pg38').setIndex('looplevel', [2], 2);
model.result('pg38').run;
model.result('pg38').setIndex('looplevel', [1], 2);
model.result('pg38').run;
model.result('pg38').setIndex('looplevel', [5], 2);
model.result('pg38').run;
model.result('pg58').run;
model.result('pg58').set('data', 'dset12');
model.result('pg58').set('looplevel', [92 1 2]);
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [21 1 2]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [41 1 2]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [61 1 2]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [81 1 2]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [11 1 2]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [21 1 2]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [21 1 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [11 1 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [21 1 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [31 1 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [41 1 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [51 1 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [61 1 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [71 1 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [81 1 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [91 1 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [100 1 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [11 1 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [51 1 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [91 1 1]);
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').feature('surf1').set('expr', 'T_RR');
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [51 1 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [11 1 1]);
model.result('pg58').run;
model.result('pg61').run;
model.result('pg61').set('data', 'dset11');
model.result('pg61').setIndex('looplevelinput', 'manual', 2);
model.result('pg61').setIndex('looplevel', [4], 2);
model.result('pg61').run;
model.result('pg61').set('data', 'dset19');
model.result('pg61').run;
model.result.export('plot1').set('plotgroup', 'pg61');
model.result.export('plot1').set('filename', 'F:\group\Research\Mechanic-electrochemic coupling method\Network model for electrode\Rate performance test 2 G5\phil_20C.txt');
model.result.export('plot1').run;
model.result('pg61').run;
model.result('pg61').set('data', 'dset11');
model.result('pg61').setIndex('looplevelinput', 'manual', 2);
model.result('pg61').setIndex('looplevel', [4], 2);
model.result('pg61').run;
model.result.export('plot1').set('filename', 'F:\group\Research\Mechanic-electrochemic coupling method\Network model for electrode\Rate performance test 2 G5\phil_10C.txt');
model.result.export('plot1').run;
model.result.export('plot1').run;
model.result.export('plot1').run;
model.result.export('plot1').run;
model.result.export('plot1').set('plotgroup', 'pg57');
model.result('pg57').run;
model.result('pg57').set('data', 'dset11');
model.result('pg57').setIndex('looplevelinput', 'manual', 2);
model.result('pg57').setIndex('looplevel', [4], 2);
model.result('pg57').run;

model.label('Electrode_model_with_experiment_deLi_constant_thickness.mph');

model.result('pg57').run;

model.component('comp2').variable('var5').set('F_h', 'comp1.linext2(comp1.T_h_M)');

model.component('comp2').physics('g3').feature('cons4').active(false);
model.component('comp2').physics('g3').feature('cons5').active(true);

model.component('comp2').variable('var5').rename('F_h', 't_h');

model.component('comp2').physics('g3').feature('cons5').setIndex('R', 'T_RR-t_h', 0);

model.component('comp1').variable('var3').set('R_p_1', 'comp2.linext1(comp2.u)+rp_primary');
model.component('comp1').variable('var3').set('F_m', '(R_p_1/rp_primary)^(1/3)');

model.component('comp1').physics('dode').feature('aleq1').setIndex('f', 'epsl_l-(1-0.1-F_m*epsl_s_0/det_F_M)', 0);

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.component('comp2').mesh('mesh3').feature('map1').feature('dis1').set('numelem', 25);
model.component('comp2').mesh('mesh3').run;
model.component('comp2').mesh('mesh3').feature('map1').feature('dis1').set('numelem', 50);
model.component('comp2').mesh('mesh3').run;
model.component('comp2').mesh('mesh3').run;
model.component('comp2').mesh('mesh3').feature('map1').feature('dis2').set('numelem', 50);
model.component('comp2').mesh('mesh3').run;

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');
model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.component('comp2').mesh('mesh3').feature('map1').feature('dis1').set('numelem', 15);
model.component('comp2').mesh('mesh3').run;
model.component('comp2').mesh('mesh3').feature('map1').feature('dis2').set('numelem', 100);
model.component('comp2').mesh('mesh3').run;

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.sol('sol1').feature('t1').feature('fc1').set('ntolfact', 1);

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.sol('sol1').runAll;

model.result('pg34').run;
model.result('pg57').run;
model.result('pg57').set('data', 'dset1');
model.result('pg57').run;
model.result('pg58').run;
model.result('pg58').set('data', 'dset2');
model.result('pg58').set('looplevel', [3]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [5]);
model.result('pg58').run;
model.result('pg57').run;
model.result('pg60').run;
model.result('pg57').run;
model.result('pg57').feature('lngr1').set('expr', 'T_h_M');
model.result('pg57').run;
model.result('pg57').run;
model.result('pg58').run;
model.result('pg58').run;
model.result.table('evl2').addRow([7.941640433273278E-6 2.6681491362978704E-6 0.043977776891525724], [0 0 0]);
model.result.table('evl2').addRow([1.688485463091638E-5 2.6859693207370583E-6 -0.0018247210254989134], [0 0 0]);
model.result.table('evl2').addRow([2.350946124352049E-5 2.6503289518586826E-6 0.08975763418787913], [0 0 0]);
model.result.table('evl2').addRow([3.0299686841317452E-5 2.6235986751999008E-6 0.15894458475208442], [0 0 0]);
model.result.table('evl2').addRow([3.2949523301795125E-5 2.6235986751999008E-6 0.15890553254166223], [0 0 0]);
model.result('pg58').run;
model.result('pg58').run;
model.result('pg57').run;
model.result('pg57').run;
model.result('pg58').run;

model.sol('sol1').feature('t1').set('tout', 'tsteps');

model.result('pg57').run;
model.result('pg57').run;
model.result('pg57').feature('lngr1').set('expr', 'T_xx_M');
model.result('pg57').run;
model.result('pg57').run;
model.result('pg27').run;
model.result('pg27').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').run;

model.sol('sol1').feature('t1').feature('fc1').set('ntolfact', 0.1);

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.sol('sol1').runAll;

model.result('pg34').run;
model.result('pg34').run;
model.result('pg34').run;
model.result('pg34').run;
model.result('pg34').run;
model.result('pg34').feature('lngr1').active(true);
model.result('pg34').run;
model.result('pg34').feature('lngr1').active(false);
model.result('pg34').run;
model.result('pg34').run;
model.result('pg27').run;
model.result('pg59').run;
model.result('pg27').run;
model.result('pg59').run;
model.result('pg57').run;
model.result('pg60').run;
model.result('pg57').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [119]);
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').run;
model.result.table('evl2').addRow([2.235015381302219E-5 2.6325087674194947E-6 0.10682004369082398], [0 0 0]);
model.result('pg19').run;
model.result('pg58').run;
model.result('pg58').run;
model.result('pg37').run;
model.result('pg37').set('data', 'dset1');
model.result('pg37').run;
model.result('pg35').run;
model.result('pg37').run;
model.result('pg1').run;
model.result('pg1').set('data', 'dset1');
model.result('pg1').run;
model.result('pg55').run;
model.result('pg55').set('data', 'dset1');
model.result('pg55').run;
model.result('pg55').run;
model.result('pg55').feature('lngr1').selection.set([1]);
model.result('pg55').run;
model.result('pg55').run;
model.result('pg61').run;
model.result('pg61').set('data', 'dset1');
model.result('pg61').run;
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').feature('surf1').set('expr', 'T_tt');
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').feature('surf1').set('expr', 'T_RR');
model.result('pg58').run;
model.result('pg58').run;
model.result('pg37').run;
model.result('pg61').run;
model.result('pg34').run;
model.result('pg34').run;
model.result('pg34').feature('glob1').active(false);
model.result('pg34').run;
model.result('pg34').run;
model.result('pg34').feature('lngr1').active(true);
model.result('pg34').run;
model.result('pg34').run;

model.sol('sol1').feature('t1').feature('fc1').set('ntolfact', 0.01);
model.sol('sol1').feature('t1').feature('fc1').set('maxiter', 250);

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.sol('sol1').runAll;

model.result('pg34').run;
model.result('pg38').run;
model.result('pg38').set('data', 'dset1');
model.result('pg38').run;
model.result('pg38').setIndex('looplevelinput', 'manual', 0);
model.result('pg38').setIndex('looplevel', [86], 0);
model.result('pg38').setIndex('looplevel', [56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86], 0);
model.result('pg38').run;
model.result('pg38').setIndex('looplevel', [124], 0);
model.result('pg38').setIndex('looplevel', [124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151], 0);
model.result('pg38').run;
model.result('pg58').run;
model.result('pg62').run;
model.result('pg2').run;
model.result('pg2').set('data', 'dset2');
model.result('pg2').run;
model.result('pg2').set('looplevel', [109]);
model.result('pg2').run;
model.result('pg58').run;
model.result('pg2').run;
model.result('pg2').run;
model.result('pg2').feature('surf1').set('expr', 'u');
model.result('pg2').run;
model.result('pg2').feature('surf1').set('expr', 'cs/cs_max_neg');
model.result('pg2').run;
model.result('pg2').run;
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').run;
model.result('pg2').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [50]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [59]);
model.result('pg58').run;
model.result('pg58').run;
model.result('pg2').run;
model.result('pg2').set('looplevel', [67]);
model.result('pg2').run;
model.result('pg2').set('looplevel', [44]);
model.result('pg2').run;
model.result('pg2').set('looplevel', [59]);
model.result('pg2').run;
model.result('pg2').set('looplevel', [61]);
model.result('pg2').run;

model.component('comp2').mesh('mesh3').feature('map1').feature('dis1').set('numelem', 50);
model.component('comp2').mesh('mesh3').feature('map1').feature('dis2').set('numelem', 50);
model.component('comp2').mesh('mesh3').run;

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.sol('sol1').feature('t1').feature('fc1').set('ntolfact', 0.1);
model.sol('sol1').feature('t1').feature('fc1').set('maxiter', 25);
model.sol('sol1').feature('t1').feature('fc1').set('ntolfact', 1);
model.sol('sol1').feature('t1').feature('fc1').set('dtech', 'const');

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.component('comp2').mesh('mesh3').feature('map1').feature('dis2').set('numelem', 100);
model.component('comp2').mesh('mesh3').run;

model.sol('sol1').feature('t1').feature('fc1').set('dtech', 'auto');

model.component('comp2').mesh('mesh3').feature('map1').feature('dis1').set('numelem', 15);
model.component('comp2').mesh('mesh3').run;

model.component('comp2').physics('g3').feature('cons5').setIndex('constraintType', 'unidirectionalConstraint', 0);

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.component('comp2').mesh('mesh3').feature('map1').feature('dis2').set('numelem', 25);
model.component('comp2').mesh('mesh3').run;
model.component('comp2').mesh('mesh3').run;

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.component('comp2').physics('g3').feature('cons5').setIndex('constraintType', 'symmetricConstraint', 0);

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.sol('sol1').runAll;

model.result('pg34').run;
model.result('pg34').run;
model.result('pg34').run;
model.result('pg34').run;
model.result('pg34').feature('glob1').active(true);
model.result('pg34').run;
model.result('pg34').run;
model.result('pg2').run;
model.result('pg2').set('looplevel', [57]);
model.result('pg2').run;
model.result('pg2').set('looplevel', [62]);
model.result('pg2').run;
model.result('pg2').run;
model.result('pg2').set('looplevel', [78]);
model.result('pg2').run;
model.result('pg2').run;
model.result('pg2').set('looplevel', [95]);
model.result('pg2').run;
model.result('pg34').run;
model.result('pg34').run;
model.result('pg35').run;
model.result('pg38').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [128]);
model.result('pg58').run;
model.result('pg37').run;
model.result('pg24').run;
model.result('pg35').run;
model.result('pg35').set('data', 'dset1');
model.result('pg35').run;
model.result('pg35').setIndex('looplevelinput', 'manual', 0);
model.result('pg35').setIndex('looplevel', [2], 0);
model.result('pg35').setIndex('looplevel', [137], 0);
model.result('pg35').run;
model.result('pg38').run;
model.result('pg38').setIndex('looplevel', [2], 0);
model.result('pg38').setIndex('looplevel', [72], 0);
model.result('pg38').run;
model.result('pg38').setIndex('looplevel', [96], 0);
model.result('pg38').run;
model.result('pg58').run;
model.result('pg35').run;
model.result('pg35').setIndex('looplevel', [128], 0);
model.result('pg35').setIndex('looplevel', [137], 0);
model.result('pg35').run;
model.result('pg35').set('data', 'dset11');
model.result('pg35').run;
model.result('pg57').run;
model.result('pg27').run;
model.result('pg27').run;
model.result('pg27').feature('lngr1').set('expr', 'comp2.linext1(comp2.T_RR)');
model.result('pg27').run;
model.result('pg27').run;

model.component('comp2').physics('g3').feature('cons5').setIndex('constraintType', 'unidirectionalVar', 0);
model.component('comp2').physics('g3').feature('cons5').setIndex('constraintType', 'symmetricConstraint', 0);

model.component('comp2').mesh('mesh3').feature('map1').feature('dis1').set('numelem', 50);
model.component('comp2').mesh('mesh3').feature('map1').feature('dis2').set('numelem', 100);
model.component('comp2').mesh('mesh3').run;

model.result('pg37').run;
model.result('pg37').run;
model.result('pg37').feature('lngr1').set('expr', 'F_m');
model.result('pg37').run;
model.result('pg37').feature('lngr1').set('expr', 'det_F_M');
model.result('pg37').run;
model.result('pg37').run;
model.result('pg2').run;
model.result('pg2').run;
model.result('pg2').feature('surf1').set('expr', 'u');
model.result('pg2').run;
model.result.table('evl2').addRow([2.2745948626834434E-6 2.687442474780255E-6 3.112892888328387E-7], [0 0 0]);
model.result('pg2').run;
model.result('pg2').run;
model.result('pg2').feature('surf1').set('expr', 'cs/cs_max_neg');
model.result('pg2').run;

model.component('comp1').physics('dode').feature('aleq1').setIndex('f', 'epsl_l-(1-epsl_b-F_m*epsl_s_0/det_F_M)', 0);

model.param.set('C', '0.1');

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.component('comp2').physics('g3').feature('cons5').setIndex('R', 'T_RR', 0);

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.component('comp2').physics('g3').feature('cons5').setIndex('R', 'T_RR-t_h', 0);
model.component('comp2').physics('g3').feature('cons4').active(true);
model.component('comp2').physics('g3').feature('cons5').active(false);
model.component('comp2').physics('g3').feature('cons4').active(false);
model.component('comp2').physics('g3').feature('cons5').active(true);

model.param.set('C', '0.05');

model.component('comp2').physics('g3').feature('cons5').setIndex('R', '(J_c)^(-1/3)*E_int1(cs/cs_max_neg)/(2*(1+gamma)*(1-2*gamma))*((1-gamma)*(uy+1)^2+2*gamma*(u_y+1)^2-(1+gamma)*(J_c)^(2/3))*(uy+1)-t_h', 0);

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.sol('sol1').runAll;

model.result('pg34').run;
model.result('pg2').run;
model.result('pg2').set('looplevel', [66]);
model.result('pg2').run;

model.component('comp2').physics('g3').feature('cons5').setIndex('weakConstraints', 0, 0);

model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [61]);
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').feature('surf1').set('expr', 'T_tt');
model.result('pg58').run;
model.result('pg58').feature('surf1').set('expr', 'F_e_RR');
model.result('pg58').feature('surf1').set('descr', '');
model.result('pg58').run;
model.result('pg58').feature('surf1').set('expr', 'F_e_tt');
model.result('pg58').run;
model.result('pg58').feature('surf1').set('expr', 'omega1');
model.result('pg58').feature('surf1').set('descr', '');
model.result('pg58').run;
model.result('pg58').feature('surf1').set('expr', 'T_RR');
model.result('pg58').run;
model.result('pg2').run;
model.result('pg58').run;
model.result('pg2').run;

model.component('comp2').physics('g3').feature('cons5').setIndex('R', 'T_RR-t_h', 0);

model.result('pg57').run;
model.result('pg57').run;
model.result('pg57').feature('lngr1').set('expr', 'T_h_M');
model.result('pg57').run;
model.result('pg57').run;

model.component('comp2').physics('g3').feature('cons5').setIndex('constraintType', 'unidirectionalConstraint', 0);

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.sol('sol1').runAll;

model.result('pg34').run;
model.result('pg2').run;
model.result('pg2').set('looplevel', [202]);
model.result('pg2').run;
model.result('pg2').set('looplevel', [225]);
model.result('pg2').run;
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [225]);
model.result('pg58').run;
model.result('pg37').run;
model.result('pg37').run;
model.result('pg37').feature('lngr1').set('expr', 'epsl_l');
model.result('pg37').run;
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').run;
model.result('pg37').run;
model.result('pg35').run;
model.result('pg35').set('data', 'dset1');
model.result('pg35').run;
model.result('pg45').run;
model.result('pg45').set('data', 'dset1');
model.result('pg45').run;

model.component('comp1').variable('var3').set('F_m', '(R_p_1/rp_primary)^3');

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.sol('sol1').runAll;

model.result('pg34').run;
model.result('pg45').run;
model.result('pg34').run;
model.result('pg37').run;
model.result.create('pg63', 'PlotGroup1D');
model.result('pg63').set('data', 'dset15');
model.result('pg63').create('lngr1', 'LineGraph');
model.result('pg63').feature('lngr1').set('xdata', 'expr');
model.result('pg63').feature('lngr1').set('xdataexpr', 'x');
model.result('pg63').feature('lngr1').selection.all;
model.result('pg63').feature('lngr1').set('expr', 'cl');
model.result.create('pg64', 'PlotGroup2D');
model.result('pg64').set('data', 'dset16');
model.result('pg64').create('surf1', 'Surface');
model.result('pg64').feature('surf1').set('expr', 'u');
model.result.create('pg65', 'PlotGroup2D');
model.result('pg65').set('data', 'dset16');
model.result('pg65').create('surf1', 'Surface');
model.result('pg65').feature('surf1').set('expr', 'cs');
model.result.create('pg66', 'PlotGroup1D');
model.result('pg66').set('data', 'dset15');
model.result('pg66').create('lngr1', 'LineGraph');
model.result('pg66').feature('lngr1').set('xdata', 'expr');
model.result('pg66').feature('lngr1').set('xdataexpr', 'x');
model.result('pg66').feature('lngr1').selection.all;
model.result('pg66').feature('lngr1').set('expr', 'uM');
model.result.create('pg67', 'PlotGroup1D');
model.result('pg67').set('data', 'dset15');
model.result('pg67').create('lngr1', 'LineGraph');
model.result('pg67').feature('lngr1').set('xdata', 'expr');
model.result('pg67').feature('lngr1').set('xdataexpr', 'x');
model.result('pg67').feature('lngr1').selection.all;
model.result('pg67').feature('lngr1').set('expr', 'epsl_l');

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.batch('p3').run('compute');

model.result('pg63').run;

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.batch('p2').run('compute');

model.result('pg23').run;
model.result('pg19').run;

model.param.set('k_kl', '5');

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.batch('p2').run('compute');

model.result('pg23').run;
model.result('pg61').run;
model.result('pg19').run;
model.result('pg37').run;

model.param.set('k_kl', '7.5');

model.result('pg35').run;
model.result('pg35').set('data', 'dset11');
model.result('pg35').setIndex('looplevelinput', 'manual', 2);
model.result('pg35').setIndex('looplevel', [4], 2);
model.result('pg35').run;
model.result('pg38').run;
model.result('pg38').set('data', 'dset11');
model.result('pg38').setIndex('looplevelinput', 'manual', 2);
model.result('pg38').setIndex('looplevel', [4], 2);
model.result('pg38').run;
model.result('pg58').run;
model.result('pg58').set('data', 'dset12');
model.result('pg58').set('looplevel', [26 1 4]);
model.result('pg58').run;

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.batch('p2').run('compute');

model.result('pg23').run;
model.result('pg19').run;

model.func('an2').set('funcname', 'kl_an1');
model.func('an5').set('funcname', 'Dl_an1');
model.func('an4').set('funcname', 'kl_an1_1');
model.func('an3').set('funcname', 'Dl_an1_1');

model.param.set('k_kl', '2.5');

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.batch('p2').run('compute');

model.result('pg23').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').feature('tblp5').set('scalingx', '1/0.86');
model.result('pg19').run;
model.result('pg19').feature('tblp5').set('scalingx', '1/0.855');
model.result('pg19').run;

model.func('an2').set('funcname', 'kl_an1_0');
model.func('an5').set('funcname', 'Dl_an1_0');
model.func('an4').set('funcname', 'kl_an1');
model.func('an3').set('funcname', 'Dl_an1');

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.batch('p4').run('compute');

model.result('pg60').run;
model.result('pg19').run;
model.result('pg58').run;
model.result('pg37').run;
model.result('pg37').set('data', 'dset11');
model.result('pg37').setIndex('looplevelinput', 'manual', 2);
model.result('pg37').setIndex('looplevel', [3], 2);
model.result('pg37').setIndex('looplevel', [4], 2);
model.result('pg37').run;
model.result('pg37').set('data', 'dset19');
model.result('pg37').run;
model.result('pg58').run;
model.result('pg38').run;
model.result('pg38').set('data', 'dset19');
model.result('pg38').run;
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [41 1 4]);
model.result('pg58').run;
model.result('pg58').set('data', 'dset20');
model.result('pg58').run;
model.result.table('evl2').addRow([2.7075471734860912E-5 2.651426484590047E-6 -1.289304517904835E8], [0 0 0]);

model.label('Electrode_model_with_experiment_deLi_constant_thickness_1.mph');

model.result('pg58').run;
model.result('pg55').run;
model.result('pg55').set('data', 'dset11');
model.result('pg55').setIndex('looplevelinput', 'manual', 2);
model.result('pg55').setIndex('looplevel', [4], 2);
model.result('pg55').run;
model.result('pg55').set('data', 'dset19');
model.result('pg55').run;
model.result('pg61').run;
model.result('pg61').set('data', 'dset11');
model.result('pg61').setIndex('looplevelinput', 'manual', 2);
model.result('pg61').setIndex('looplevel', [4], 2);
model.result('pg61').run;
model.result('pg61').set('data', 'dset19');
model.result('pg61').run;
model.result('pg38').run;
model.result('pg38').set('data', 'dset11');
model.result('pg38').setIndex('looplevelinput', 'manual', 2);
model.result('pg38').setIndex('looplevel', [4], 2);
model.result('pg38').run;
model.result('pg38').set('data', 'dset19');
model.result('pg38').run;
model.result('pg55').run;
model.result('pg37').run;
model.result('pg37').set('data', 'dset11');
model.result('pg37').setIndex('looplevelinput', 'manual', 2);
model.result('pg37').setIndex('looplevel', [4], 2);
model.result('pg37').run;
model.result('pg57').run;
model.result('pg57').set('data', 'dset11');
model.result('pg57').setIndex('looplevelinput', 'manual', 2);
model.result('pg57').setIndex('looplevel', [4], 2);
model.result('pg57').run;
model.result('pg57').run;
model.result('pg57').feature('lngr1').set('expr', 'T_xx_M');
model.result('pg57').run;
model.result('pg57').feature('lngr1').set('expr', 'T_yy_M');
model.result('pg57').run;
model.result('pg57').run;
model.result('pg57').set('data', 'dset19');
model.result('pg57').run;
model.result('pg57').run;
model.result('pg57').feature('lngr1').set('expr', 'T_xx_M');
model.result('pg57').run;
model.result('pg57').run;
model.result('pg53').set('window', 'window1');
model.result('pg53').run;
model.result.remove('pg53');
model.result.remove('pg54');
model.result.remove('pg63');
model.result.remove('pg64');
model.result.remove('pg65');
model.result.remove('pg66');
model.result.remove('pg67');
model.result('pg24').run;
model.result('pg45').run;
model.result('pg45').set('data', 'dset11');
model.result('pg45').setIndex('looplevelinput', 'manual', 2);
model.result('pg45').setIndex('looplevel', [4], 2);
model.result('pg45').run;
model.result('pg45').set('data', 'dset19');
model.result('pg45').run;
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').set('data', 'dset12');
model.result('pg58').set('looplevel', [11 1 1]);
model.result('pg58').run;
model.result('pg19').run;
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').feature('surf1').set('unit', 'GPa');
model.result('pg58').run;
model.result('pg58').feature('surf1').set('expr', 'T_tt');
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [51 1 1]);
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').feature('surf1').set('expr', 'T_RR');
model.result('pg58').run;
model.result('pg58').feature('surf1').set('expr', 'T_tt');
model.result('pg58').run;
model.result('pg38').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [91 1 1]);
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').feature('surf1').set('expr', 'T_RR');
model.result('pg58').run;
model.result('pg38').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [51 1 1]);
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').feature('surf1').set('expr', 'T_tt');
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [11 1 4]);
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').feature('surf1').set('expr', 'T_RR');
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [21 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [31 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [41 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [51 1 4]);
model.result('pg58').run