 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [81], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [121], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [122], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [121], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [115], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [116], 0);
model.result('pg18').setIndex('looplevel', [114], 0);
model.result('pg18').setIndex('looplevel', [111], 0);
model.result('pg18').setIndex('looplevel', [111 112 113 114 115 116 117 118 119 120], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [111 112 113 114 115 116 117 118 119 120 121], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [111 112 113 114 115 116 117 118 119 120 121 122], 0);
model.result('pg18').run;
model.result('pg24').run;
model.result('pg18').run;
model.result('pg10').run;
model.result('pg21').run;
model.result('pg21').setIndex('looplevelinput', 'all', 0);
model.result('pg21').run;

model.component('comp1').mesh('mesh2').autoMeshSize(4);
model.component('comp1').mesh('mesh2').run;

model.result('pg17').run;

model.component('comp1').variable('var3').set('epsl_l_1', 'max(epsl_l,1e-4)');

model.result('pg8').run;
model.result('pg8').run;
model.result('pg8').feature('ptgr1').set('expr', 'epsl_l');
model.result('pg8').run;
model.result('pg8').feature('ptgr1').set('expr', 'epsl_l_1');
model.result('pg8').run;
model.result('pg17').run;

model.component('comp1').variable('var3').set('epsl_l_1', 'max(epsl_l,eps)');

model.component('comp1').mesh('mesh2').autoMeshSize(2);
model.component('comp1').mesh('mesh2').run;

model.result('pg17').run;
model.result('pg8').run;
model.result('pg6').run;
model.result('pg6').setIndex('looplevelinput', 'all', 0);
model.result('pg6').run;
model.result('pg23').run;
model.result('pg17').run;
model.result('pg8').run;
model.result('pg8').run;
model.result('pg8').feature('ptgr1').set('expr', 'epsl_l');
model.result('pg8').run;
model.result('pg8').feature('ptgr1').set('expr', 'epsl_l_1');
model.result('pg8').run;

model.component('comp1').mesh('mesh2').autoMeshSize(1);
model.component('comp1').mesh('mesh2').run;
model.component('comp1').mesh('mesh2').automatic(false);
model.component('comp1').mesh('mesh2').feature('size').set('table', 'cfd');
model.component('comp1').mesh('mesh2').run;

model.result('pg17').run;
model.result('pg8').run;
model.result('pg8').feature('ptgr1').set('expr', 'epsl_l');
model.result('pg8').run;
model.result('pg7').run;

model.param.set('epsl_l_0', '0.2');

model.sol('sol1').runAll;

model.result('pg17').run;
model.result('pg15').run;
model.result('pg8').run;
model.result('pg21').run;
model.result('pg7').run;
model.result('pg2').run;
model.result('pg2').setIndex('looplevel', 361, 0);
model.result('pg2').run;
model.result('pg24').run;
model.result('pg10').run;
model.result('pg7').run;
model.result('pg21').run;
model.result('pg16').run;
model.result('pg22').run;
model.result('pg22').run;
model.result('pg22').feature('ptgr1').set('expr', 'det_F_M');
model.result('pg22').run;
model.result('pg22').run;
model.result('pg15').run;
model.result('pg6').run;
model.result('pg7').run;

model.study('std1').feature('time').set('tlist', 'range(0,1,36)');

model.result.dataset('cpt1').set('pointx', 'Rp_secondary');

model.study('std1').create('param', 'Parametric');
model.study('std1').feature('param').setIndex('pname', 'T', 0);
model.study('std1').feature('param').setIndex('plistarr', '', 0);
model.study('std1').feature('param').setIndex('punit', '', 0);
model.study('std1').feature('param').setIndex('pname', 'T', 0);
model.study('std1').feature('param').setIndex('plistarr', '', 0);
model.study('std1').feature('param').setIndex('punit', '', 0);
model.study('std1').feature('param').setIndex('pname', 'epsl_l_0', 0);
model.study('std1').feature('param').setIndex('plistarr', '0.2 0', 0);
model.study('std1').feature('param').setIndex('plistarr', '0.2 0.19 0.18 0.17 0.16 0.15', 0);

model.batch.create('p1', 'Parametric');
model.batch('p1').study('std1');
model.batch('p1').create('so1', 'Solutionseq');
model.batch('p1').feature('so1').set('seq', 'sol1');
model.batch('p1').feature('so1').set('store', 'on');
model.batch('p1').feature('so1').set('clear', 'on');
model.batch('p1').feature('so1').set('psol', 'none');
model.batch('p1').set('pname', {'epsl_l_0'});
model.batch('p1').set('plistarr', {'0.2 0.19 0.18 0.17 0.16 0.15'});
model.batch('p1').set('sweeptype', 'sparse');
model.batch('p1').set('probesel', 'all');
model.batch('p1').set('probes', {});
model.batch('p1').set('plot', 'off');
model.batch('p1').set('err', 'on');
model.batch('p1').attach('std1');
model.batch('p1').set('control', 'param');

model.sol.create('sol2');
model.sol('sol2').study('std1');
model.sol('sol2').label([native2unicode(hex2dec({'53' 'c2'}), 'unicode')  native2unicode(hex2dec({'65' '70'}), 'unicode')  native2unicode(hex2dec({'53' '16'}), 'unicode')  native2unicode(hex2dec({'89' 'e3'}), 'unicode') ' 1']);

model.batch('p1').feature('so1').set('psol', 'sol2');

model.result.create('pg25', 'PlotGroup2D');
model.result('pg25').set('data', 'dset4');
model.result('pg25').create('surf1', 'Surface');
model.result('pg25').feature('surf1').set('expr', 'u');
model.result.create('pg26', 'PlotGroup2D');
model.result('pg26').set('data', 'dset4');
model.result('pg26').create('surf1', 'Surface');
model.result('pg26').feature('surf1').set('expr', 'cs');
model.result.create('pg27', 'PlotGroup1D');
model.result('pg27').set('data', 'dset3');
model.result('pg27').create('lngr1', 'LineGraph');
model.result('pg27').feature('lngr1').set('xdata', 'expr');
model.result('pg27').feature('lngr1').set('xdataexpr', 'x');
model.result('pg27').feature('lngr1').selection.all;
model.result('pg27').feature('lngr1').set('expr', 'cl');
model.result.create('pg28', 'PlotGroup1D');
model.result('pg28').set('data', 'dset3');
model.result('pg28').create('lngr1', 'LineGraph');
model.result('pg28').feature('lngr1').set('xdata', 'expr');
model.result('pg28').feature('lngr1').set('xdataexpr', 'x');
model.result('pg28').feature('lngr1').selection.all;
model.result('pg28').feature('lngr1').set('expr', 'uM');
model.result.create('pg29', 'PlotGroup1D');
model.result('pg29').set('data', 'dset3');
model.result('pg29').create('lngr1', 'LineGraph');
model.result('pg29').feature('lngr1').set('xdata', 'expr');
model.result('pg29').feature('lngr1').set('xdataexpr', 'x');
model.result('pg29').feature('lngr1').selection.all;
model.result('pg29').feature('lngr1').set('expr', 'epsl_l');
model.result.remove('pg27');
model.result.remove('pg28');
model.result.remove('pg29');
model.result.remove('pg25');
model.result.remove('pg26');
model.result('pg19').run;
model.result('pg19').setIndex('looplevelinput', 'all', 0);
model.result('pg19').set('data', 'dset3');
model.result('pg19').run;
model.result('pg7').run;
model.result('pg7').set('data', 'dset3');
model.result('pg7').run;
model.result('pg7').feature('ptgr1').selection.set([2]);
model.result('pg7').run;
model.result('pg17').run;
model.result('pg19').run;
model.result('pg17').run;
model.result('pg19').run;
model.result('pg17').run;
model.result('pg19').run;
model.result('pg17').run;
model.result('pg17').run;
model.result('pg17').set('data', 'dset3');
model.result('pg17').run;
model.result('pg17').feature('ptgr1').selection.set([1]);
model.result('pg17').run;
model.result('pg14').run;
model.result('pg8').run;
model.result('pg8').set('data', 'dset3');
model.result('pg8').run;
model.result('pg8').feature('ptgr1').selection.set([2]);
model.result('pg6').run;
model.result('pg8').run;
model.result('pg17').run;
model.result('pg17').set('data', 'cpt1');
model.result('pg17').run;
model.result('pg17').set('data', 'dset1');
model.result('pg17').run;
model.result('pg17').feature('ptgr1').selection.set([1]);
model.result('pg17').run;
model.result('pg19').run;
model.result('pg20').run;
model.result('pg1').run;
model.result('pg1').setIndex('looplevelinput', 'all', 0);
model.result('pg1').run;
model.result('pg6').run;
model.result('pg8').run;
model.result('pg22').run;
model.result('pg8').run;
model.result('pg6').run;
model.result('pg6').set('data', 'dset3');
model.result('pg6').run;
model.result('pg6').feature('ptgr1').selection.set([2]);
model.result('pg6').run;
model.result('pg6').run;
model.result('pg21').run;
model.result('pg21').set('data', 'dset3');
model.result('pg21').run;
model.result('pg21').feature('ptgr1').selection.set([2]);
model.result('pg21').run;
model.result('pg23').run;
model.result('pg23').run;
model.result('pg23').run;
model.result('pg23').set('data', 'dset3');
model.result('pg23').run;
model.result('pg23').feature('ptgr1').selection.set([2]);
model.result('pg23').run;
model.result('pg23').run;
model.result('pg8').run;
model.result('pg17').run;
model.result('pg23').run;
model.result('pg23').run;

model.param.set('cl_ref', '1[mol/m^3]');

model.result('pg17').run;
model.result('pg23').run;
model.result('pg23').set('data', 'dset1');
model.result('pg23').run;
model.result('pg23').run;
model.result('pg23').run;

model.param.set('cl_ref', '1000[mol/m^3]');

model.study('std1').feature('param').setIndex('plistarr', '0.2 0.19 0.18 0.17', 0);

model.batch('p1').run;

model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').feature('ptgr1').selection.set([2]);
model.result('pg19').run;
model.result('pg23').run;
model.result('pg23').run;
model.result('pg23').run;
model.result('pg23').set('data', 'dset3');
model.result('pg23').run;
model.result('pg23').run;
model.result('pg17').run;
model.result('pg17').set('data', 'dset3');
model.result('pg17').run;
model.result('pg6').run;
model.result('pg8').run;
model.result('pg18').run;
model.result('pg18').set('data', 'dset3');
model.result('pg18').setIndex('looplevelinput', 'manual', 0);
model.result('pg18').setIndex('looplevel', [1], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [11], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [21], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [1], 0);
model.result('pg18').setIndex('looplevel', [2], 0);
model.result('pg18').setIndex('looplevel', [1], 0);
model.result('pg18').run;
model.result('pg18').run;
model.result('pg18').feature('lngr1').set('legend', true);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [5], 0);
model.result('pg18').setIndex('looplevel', [6], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [11], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [16], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [21], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [26], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [31], 0);
model.result('pg18').run;
model.result.create('pg25', 'PlotGroup1D');
model.result('pg25').run;
model.result.move('pg25', 16);
model.result('pg25').label('i0 of the domain');
model.result('pg25').set('data', 'dset3');
model.result('pg25').setIndex('looplevelinput', 'manual', 0);
model.result('pg25').create('ptgr1', 'PointGraph');
model.result('pg25').feature('ptgr1').selection.set([2]);
model.result('pg25').feature('ptgr1').set('expr', 'i0');
model.result('pg25').run;
model.result('pg25').feature.remove('ptgr1');
model.result('pg25').run;
model.result('pg25').create('lngr1', 'LineGraph');
model.result('pg25').feature('lngr1').selection.set([1]);
model.result('pg25').feature('lngr1').set('expr', 'i0');
model.result('pg25').run;
model.result('pg25').run;
model.result('pg25').setIndex('looplevel', [2], 0);
model.result('pg25').run;
model.result('pg25').setIndex('looplevel', [3], 0);
model.result('pg25').run;
model.result('pg25').run;
model.result('pg25').feature('lngr1').set('legend', true);
model.result('pg25').feature('lngr1').set('linewidth', 2);
model.result('pg24').run;
model.result('pg25').run;
model.result('pg25').setIndex('looplevel', [5], 0);
model.result('pg25').setIndex('looplevel', [6], 0);
model.result('pg25').run;
model.result('pg25').setIndex('looplevel', [11], 0);
model.result('pg25').run;
model.result('pg25').setIndex('looplevel', [15], 0);
model.result('pg25').run;
model.result('pg25').setIndex('looplevel', [12], 0);
model.result('pg25').run;
model.result('pg25').setIndex('looplevel', [13], 0);
model.result('pg25').run;
model.result.create('pg26', 'PlotGroup1D');
model.result('pg26').run;
model.result.move('pg26', 17);
model.result('pg26').label('Electrochemo-mechanical overpotential of the domain');
model.result('pg26').create('lngr1', 'LineGraph');
model.result('pg26').feature('lngr1').selection.set([1]);
model.result('pg26').feature('lngr1').set('linewidth', 2);
model.result('pg1').run;
model.result('pg6').run;
model.result('pg1').run;
model.result('pg1').run;
model.result('pg1').run;
model.result('pg2').run;
model.result('pg26').run;
model.result('pg26').feature('lngr1').set('expr', 'eta-T_h_micro*omega/J_c_micro^(2/3)/F_const');
model.result('pg26').run;
model.result('pg26').set('data', 'dset3');
model.result('pg26').setIndex('looplevelinput', 'manual', 0);
model.result('pg26').setIndex('looplevel', [1], 0);
model.result('pg26').run;
model.result('pg26').setIndex('looplevel', [6], 0);
model.result('pg26').run;
model.result('pg26').setIndex('looplevel', [1], 0);
model.result('pg26').run;
model.result('pg26').setIndex('looplevel', [2], 0);
model.result('pg26').run;
model.result('pg26').setIndex('looplevel', [3], 0);
model.result('pg26').run;
model.result('pg26').setIndex('looplevel', [4], 0);
model.result('pg26').run;
model.result('pg26').setIndex('looplevel', [5], 0);
model.result('pg26').run;
model.result('pg26').setIndex('looplevel', [6], 0);
model.result('pg26').run;
model.result('pg26').setIndex('looplevel', [7], 0);
model.result('pg26').run;
model.result('pg26').run;
model.result('pg26').feature('lngr1').set('expr', 'eta');
model.result('pg26').run;
model.result('pg25').run;
model.result('pg26').run;
model.result('pg26').setIndex('looplevel', [11], 0);
model.result('pg26').run;
model.result('pg26').setIndex('looplevel', [12], 0);
model.result('pg26').run;
model.result('pg26').run;
model.result('pg26').feature('lngr1').set('expr', 'T_h_micro*omega/J_c_micro^(2/3)/F_const');
model.result('pg26').run;
model.result('pg26').feature('lngr1').set('expr', '-T_h_micro*omega/J_c_micro^(2/3)/F_const');
model.result('pg26').run;
model.result('pg26').run;
model.result('pg26').setIndex('looplevel', [1], 0);
model.result('pg26').run;
model.result('pg26').setIndex('looplevel', [6], 0);
model.result('pg26').run;
model.result('pg26').setIndex('looplevel', [11], 0);
model.result('pg26').run;
model.result('pg26').setIndex('looplevel', [16], 0);
model.result('pg26').run;
model.result('pg26').setIndex('looplevel', [21], 0);
model.result('pg26').run;
model.result('pg26').setIndex('looplevel', [26], 0);
model.result('pg26').run;
model.result('pg26').run;
model.result('pg26').feature('lngr1').set('expr', 'eta-T_h_micro*omega/J_c_micro^(2/3)/F_const');
model.result('pg26').run;
model.result.create('pg27', 'PlotGroup1D');
model.result('pg27').run;
model.result.move('pg27', 18);
model.result('pg27').label('Macroscale stress of the domain');
model.result('pg27').create('lngr1', 'LineGraph');
model.result('pg27').feature('lngr1').selection.set([1]);
model.result('pg27').feature('lngr1').set('expr', 'T_h_micro');
model.result('pg27').feature('lngr1').set('descr', '');
model.result('pg27').run;
model.result('pg27').run;
model.result('pg27').set('data', 'dset3');
model.result('pg27').setIndex('looplevelinput', 'manual', 0);
model.result('pg27').setIndex('looplevel', [1], 0);
model.result('pg27').run;
model.result('pg27').setIndex('looplevel', [2], 0);
model.result('pg27').run;
model.result('pg27').setIndex('looplevel', [3], 0);
model.result('pg27').run;
model.result('pg27').setIndex('looplevel', [4], 0);
model.result('pg27').run;
model.result('pg27').setIndex('looplevel', [5], 0);
model.result('pg27').run;
model.result('pg27').run;
model.result('pg26').run;
model.result('pg27').run;
model.result('pg26').run;
model.result('pg27').run;
model.result('pg27').run;
model.result('pg27').label('Microscale stress of the domain');
model.result('pg27').run;
model.result('pg27').run;
model.result('pg27').setIndex('looplevel', [6], 0);
model.result('pg27').run;
model.result('pg27').setIndex('looplevel', [9], 0);
model.result('pg27').run;
model.result('pg27').setIndex('looplevel', [11], 0);
model.result('pg27').run;
model.result('pg27').run;
model.result('pg27').setIndex('looplevel', [16], 0);
model.result('pg27').run;
model.result('pg27').setIndex('looplevel', [21], 0);
model.result('pg27').run;
model.result('pg27').setIndex('looplevel', [11], 0);
model.result('pg27').run;
model.result('pg27').run;
model.result.create('pg28', 'PlotGroup1D');
model.result('pg28').run;
model.result.move('pg28', 19);
model.result('pg28').label('Macroscale stress of the domain');
model.result('pg28').set('data', 'dset3');
model.result('pg28').setIndex('looplevelinput', 'manual', 0);
model.result('pg28').setIndex('looplevel', [2], 0);
model.result('pg28').create('lngr1', 'LineGraph');
model.result('pg28').feature('lngr1').selection.set([1]);
model.result('pg28').feature('lngr1').set('expr', 'T_h_M');
model.result('pg28').feature('lngr1').set('descr', '');
model.result('pg28').run;
model.result('pg28').feature('lngr1').set('expr', 'sigma_h_M');
model.result('pg28').run;
model.result('pg28').feature('lngr1').set('expr', 'T_h_M');
model.result('pg28').run;
model.result('pg27').run;
model.result('pg27').feature('lngr1').set('expr', 'comp2.linext1(comp2.T_tt)');
model.result('pg27').run;
model.result('pg27').feature('lngr1').set('expr', 'comp2.linext1(comp2.T_RR)');
model.result('pg27').run;
model.result('pg27').feature('lngr1').set('expr', 'comp2.linext1(comp2.T_tt)');
model.result('pg27').run;
model.result('pg27').feature('lngr1').set('expr', 'comp2.linext1(comp2.T_h)');
model.result('pg27').run;
model.result('pg27').run;
model.result('pg27').setIndex('looplevel', [1], 0);
model.result('pg27').run;
model.result('pg27').setIndex('looplevel', [2], 0);
model.result('pg27').run;
model.result('pg27').setIndex('looplevel', [3], 0);
model.result('pg27').run;
model.result('pg27').setIndex('looplevel', [4], 0);
model.result('pg27').run;
model.result('pg27').run;
model.result('pg27').setIndex('looplevel', [6], 0);
model.result('pg27').run;
model.result('pg27').setIndex('looplevel', [9], 0);
model.result('pg27').run;
model.result('pg27').setIndex('looplevel', [12], 0);
model.result('pg27').run;
model.result('pg27').setIndex('looplevelinput', 'manual', 1);
model.result('pg27').setIndex('looplevel', [1], 1);
model.result('pg27').run;
model.result('pg27').setIndex('looplevel', [18], 0);
model.result('pg27').run;
model.result('pg27').setIndex('looplevel', [1], 0);
model.result('pg27').setIndex('looplevel', [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], 0);
model.result('pg27').run;
model.result('pg27').setIndex('looplevel', [30], 0);
model.result('pg27').run;
model.result('pg27').setIndex('looplevel', [33], 0);
model.result('pg27').setIndex('looplevel', [22], 0);
model.result('pg27').setIndex('looplevel', [31], 0);
model.result('pg27').run;
model.result('pg27').setIndex('looplevel', [21 22 23 24 25 26 27 28 29 30 31], 0);
model.result('pg27').run;
model.result('pg27').setIndex('looplevel', [31 32], 0);
model.result('pg27').run;
model.result('pg27').setIndex('looplevel', [31 32 33 34 35 36 37], 0);
model.result('pg27').run;
model.result('pg22').run;
model.result.create('pg29', 'PlotGroup1D');
model.result('pg29').run;
model.result('pg29').create('lngr1', 'LineGraph');
model.result('pg29').feature('lngr1').selection.set([1]);
model.result('pg29').feature('lngr1').set('expr', 'det_F_M_dt');
model.result('pg29').feature('lngr1').set('descr', '');
model.result('pg29').run;
model.result('pg29').label('Volume change of the RVE of the domain');
model.result('pg29').run;
model.result('pg29').run;
model.result('pg29').set('data', 'dset3');
model.result('pg29').setIndex('looplevelinput', 'manual', 0);
model.result('pg29').setIndex('looplevel', [3], 0);
model.result('pg29').run;
model.result('pg29').setIndex('looplevel', [5], 0);
model.result('pg29').run;
model.result('pg29').setIndex('looplevel', [9], 0);
model.result('pg29').run;
model.result('pg29').setIndex('looplevel', [10], 0);
model.result('pg29').setIndex('looplevel', [11], 0);
model.result('pg29').run;
model.result('pg29').setIndex('looplevel', [15], 0);
model.result('pg29').run;
model.result('pg29').setIndex('looplevel', [21], 0);
model.result('pg29').run;
model.result('pg29').setIndex('looplevel', [24], 0);
model.result('pg29').run;
model.result('pg29').setIndex('looplevel', [30], 0);
model.result('pg29').run;
model.result('pg29').setIndex('looplevel', [34], 0);
model.result('pg29').run;
model.result('pg29').setIndex('looplevel', [37], 0);
model.result('pg29').run;
model.result('pg28').run;
model.result('pg27').run;
model.result('pg26').run;
model.result('pg25').run;
model.result('pg26').run;
model.result('pg27').run;
model.result('pg22').run;
model.result('pg22').run;
model.result('pg22').feature('ptgr1').set('expr', 'det_F_M_dt');
model.result('pg22').run;
model.result('pg22').run;
model.result('pg22').set('data', 'dset3');
model.result('pg22').run;
model.result('pg22').run;
model.result('pg22').feature('ptgr1').selection.set([2]);
model.result('pg22').run;
model.result('pg22').feature('ptgr1').set('expr', 'det_F_M');
model.result('pg22').run;
model.result('pg22').run;
model.result('pg15').run;
model.result('pg24').run;
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [23], 0);
model.result('pg18').run;
model.result('pg18').run;
model.result('pg18').run;
model.result('pg23').run;
model.result.create('pg30', 'PlotGroup1D');
model.result('pg30').run;
model.result.move('pg30', 15);
model.result('pg30').label('cs_surface of the domain');
model.result('pg30').set('data', 'dset3');
model.result('pg30').setIndex('looplevelinput', 'manual', 0);
model.result('pg30').setIndex('looplevel', [4], 0);
model.result('pg30').create('lngr1', 'LineGraph');
model.result('pg30').feature('lngr1').selection.set([1]);
model.result('pg30').feature('lngr1').set('expr', 'cs_surf');
model.result('pg30').run;
model.result('pg30').feature('lngr1').set('expr', 'cs_surf/cs_max_neg');
model.result('pg30').run;
model.result('pg30').setIndex('looplevel', [12], 0);
model.result('pg30').run;
model.result('pg30').setIndex('looplevel', [23], 0);
model.result('pg30').run;
model.result('pg30').setIndex('looplevel', [27], 0);
model.result('pg30').run;

model.component('comp1').variable('var3').set('i0', 'max(eps^2,F_const*kr_neg*cs_max_neg*(max(1-cs_surf/cs_max_neg,eps^2))^aa_neg*(min(cs_surf/cs_max_neg,1))^ac_neg*(max(cl[mol/m^3]/cl_ref,eps^2))^aa_neg)');

model.result('pg19').run;
model.result('pg25').run;
model.result('pg8').run;
model.result('pg16').run;
model.result('pg21').run;
model.result('pg7').run;
model.result('pg8').run;
model.result('pg15').run;
model.result('pg25').run;
model.result('pg23').run;
model.result('pg8').run;
model.result('pg6').run;
model.result('pg20').run;
model.result('pg1').run;

model.component('comp2').physics('g3').feature('cons1').setIndex('R', 'sigma_RR-comp1.linext2(comp1.sigma_h_M/comp1.epsl_s)', 0);

model.result('pg8').run;
model.result('pg14').run;
model.result('pg1').run;
model.result('pg6').run;
model.result('pg8').run;

model.func('an1').set('expr', '1*(1-epsl_s_1)^(1.2)*(epsl_s_1)');

model.component('comp1').variable('var3').set('a_v_1', 'a*(epsl_l_1)^(1.2)*(b*epsl_s_1+1-b)');

model.result('pg17').run;
model.result('pg18').run;
model.result('pg18').set('data', 'dset1');
model.result('pg18').run;

model.func('an1').set('expr', '1*(1-epsl_s_1)^(0.25)*(epsl_s_1)');

model.component('comp1').variable('var3').set('a_v_1', 'a*(epsl_l_1)^(0.25)*(b*epsl_s_1+1-b)');

model.func('an1').set('expr', '1*(1-epsl_s_1)^(0.5)*(epsl_s_1)');

model.component('comp1').variable('var3').set('a_v_1', 'a*sqrt(epsl_l_1)*(b*epsl_s_1+1-b)');

model.func('an1').set('expr', '1*sqrt(1-epsl_s_1)*(epsl_s_1)');

model.component('comp1').variable('var3').set('epsl_l_1', 'max(epsl_l,eps^2)');

model.study('std1').feature('param').setIndex('plistarr', '0.3 0.25', 0);

model.batch('p1').run;

model.result('pg17').run;
model.result('pg1').run;
model.result('pg18').run;
model.result('pg18').set('data', 'dset3');
model.result('pg18').setIndex('looplevelinput', 'manual', 0);
model.result('pg18').setIndex('looplevel', [2], 0);
model.result('pg18').run;
model.result('pg30').run;
model.result('pg24').run;
model.result('pg26').run;
model.result('pg7').run;

model.study('std1').feature('param').setIndex('plistarr', '0.3 0.25 0.225 0.2', 0);

model.result('pg19').run;
model.result('pg20').run;
model.result('pg19').run;
model.result('pg16').run;
model.result('pg8').run;
model.result('pg21').run;
model.result('pg8').run;
model.result('pg23').run;
model.result('pg26').run;
model.result('pg29').run;
model.result('pg25').run;
model.result('pg30').run;
model.result('pg30').setIndex('looplevelinput', 'manual', 0);
model.result('pg30').setIndex('looplevel', [36], 0);
model.result('pg30').run;
model.result('pg30').setIndex('looplevel', [37], 0);
model.result('pg30').run;
model.result('pg18').run;
model.result('pg8').run;
model.result('pg24').run;
model.result('pg25').run;
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [11], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [12], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [13], 0);
model.result('pg18').run;
model.result('pg30').run;
model.result('pg30').setIndex('looplevel', [2], 0);
model.result('pg30').setIndex('looplevel', [12], 0);
model.result('pg30').run;
model.result('pg30').setIndex('looplevel', [13], 0);
model.result('pg30').run;
model.result('pg25').run;
model.result('pg25').setIndex('looplevelinput', 'manual', 0);
model.result('pg25').setIndex('looplevel', [11], 0);
model.result('pg25').run;
model.result('pg25').setIndex('looplevel', [12], 0);
model.result('pg25').run;
model.result('pg25').setIndex('looplevel', [13], 0);
model.result('pg25').run;
model.result('pg26').run;
model.result('pg26').setIndex('looplevelinput', 'manual', 0);
model.result('pg26').setIndex('looplevel', [12], 0);
model.result('pg26').run;
model.result('pg26').setIndex('looplevel', [10], 0);
model.result('pg26').run;
model.result('pg7').run;
model.result('pg8').run;
model.result('pg22').run;
model.result('pg21').run;
model.result('pg7').run;
model.result('pg18').run;
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [14], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [15], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [16], 0);
model.result('pg18').setIndex('looplevel', [17], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [18], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [19], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [20], 0);
model.result('pg18').run;
model.result('pg20').run;
model.result('pg20').run;
model.result('pg20').run;
model.result('pg20').set('data', 'dset3');
model.result('pg20').run;
model.result('pg20').feature('ptgr1').selection.set([2]);
model.result('pg20').run;
model.result('pg20').run;
model.result('pg6').run;
model.result('pg7').run;
model.result('pg30').run;
model.result.create('pg31', 'PlotGroup1D');
model.result('pg31').run;
model.result.move('pg31', 12);
model.result.remove('pg31');
model.result('pg26').run;
model.result('pg27').run;
model.result('pg27').setIndex('looplevelinput', 'manual', 0);
model.result('pg27').setIndex('looplevel', [1], 0);
model.result('pg27').setIndex('looplevel', [1 2 3 4 5 6 7 8 9 10 11], 0);
model.result('pg27').setIndex('looplevel', [11], 0);
model.result('pg27').run;
model.result('pg27').run;
model.result('pg27').run;
model.result('pg27').setIndex('looplevel', [1], 0);
model.result('pg27').run;
model.result('pg27').setIndex('looplevel', [2], 0);
model.result('pg27').run;
model.result('pg27').setIndex('looplevel', [3], 0);
model.result('pg27').run;
model.result('pg27').setIndex('looplevel', [4], 0);
model.result('pg27').run;
model.result('pg27').setIndex('looplevel', [5], 0);
model.result('pg27').run;
model.result('pg27').setIndex('looplevel', [6], 0);
model.result('pg27').run;
model.result('pg27').setIndex('looplevel', [7], 0);
model.result('pg27').run;
model.result('pg27').setIndex('looplevel', [8], 0);
model.result('pg27').run;
model.result('pg27').setIndex('looplevel', [9], 0);
model.result('pg27').run;
model.result('pg27').setIndex('looplevel', [10], 0);
model.result('pg27').run;
model.result('pg27').setIndex('looplevel', [11], 0);
model.result('pg27').run;
model.result('pg27').setIndex('looplevel', [12], 0);
model.result('pg27').run;
model.result('pg27').setIndex('looplevel', [13], 0);
model.result('pg27').run;
model.result('pg27').setIndex('looplevel', [14], 0);
model.result('pg27').run;
model.result.create('pg31', 'PlotGroup1D');
model.result('pg31').run;
model.result('pg31').label('epsl_lt of the domain');
model.result('pg31').set('data', 'dset3');
model.result('pg31').setIndex('looplevelinput', 'manual', 0);
model.result('pg31').setIndex('looplevel', [1], 0);
model.result('pg31').create('ptgr1', 'PointGraph');
model.result('pg31').feature('ptgr1').selection.set([2]);
model.result('pg31').feature('ptgr1').set('expr', 'epsl_lt');
model.result('pg31').run;
model.result('pg31').run;
model.result('pg31').setIndex('looplevelinput', 'all', 0);
model.result('pg31').run;
model.result('pg31').setIndex('looplevelinput', 'manual', 1);
model.result('pg31').setIndex('looplevel', [1], 1);
model.result('pg31').run;
model.result('pg31').run;
model.result('pg31').feature('ptgr1').label('epsl_lt');
model.result('pg31').run;
model.result('pg31').create('ptgr2', 'PointGraph');
model.result('pg31').feature('ptgr2').label('reaction');
model.result('pg31').run;
model.result('pg31').feature('ptgr2').set('expr', 'omega*j_react_macro*a_v/F_const');
model.result('pg31').run;
model.result('pg31').feature('ptgr1').set('expr', 'epsl_lt*det_F_M');
model.result('pg31').run;
model.result('pg31').run;
model.result('pg31').create('ptgr3', 'PointGraph');
model.result('pg16').run;
model.result('pg31').run;
model.result('pg31').feature('ptgr3').label('contraction of RVE');
model.result('pg31').run;
model.result('pg31').run;
model.result('pg31').feature('ptgr3').set('expr', 'det_F_M_dt*(1-epsl_l)');
model.result('pg31').run;
model.result('pg31').run;
model.result('pg31').feature('ptgr2').selection.set([2]);
model.result('pg31').run;
model.result('pg31').feature('ptgr3').selection.set([2]);
model.result('pg31').feature('ptgr3').set('linewidth', 2);
model.result('pg31').run;
model.result('pg31').feature('ptgr2').set('linewidth', 2);
model.result('pg31').run;
model.result('pg31').feature('ptgr1').set('linewidth', 2);
model.result('pg31').run;
model.result('pg31').run;
model.result('pg31').feature('ptgr1').set('legend', true);
model.result('pg31').run;
model.result('pg31').feature('ptgr2').set('legend', true);
model.result('pg31').run;
model.result('pg31').feature('ptgr3').set('legend', true);
model.result('pg31').run;
model.result('pg31').run;
model.result('pg31').feature('ptgr1').active(false);
model.result('pg31').feature('ptgr2').active(false);
model.result('pg31').run;
model.result('pg29').run;
model.result('pg31').run;
model.result('pg31').setIndex('looplevel', [1 2 3], 1);
model.result('pg31').run;
model.result('pg31').run;
model.result('pg31').feature('ptgr3').active(false);
model.result('pg31').run;
model.result('pg31').run;
model.result('pg31').feature('ptgr2').active(true);
model.result('pg31').run;
model.result('pg31').feature('ptgr2').active(false);
model.result('pg31').run;
model.result('pg31').run;
model.result('pg31').setIndex('looplevel', [3], 1);
model.result('pg31').run;
model.result('pg31').feature('ptgr1').active(true);
model.result('pg31').feature('ptgr2').active(true);
model.result('pg31').feature('ptgr3').active(true);
model.result('pg31').run;
model.result('pg31').feature('ptgr1').set('legendprefix', 'all');
model.result('pg31').run;
model.result('pg31').run;
model.result('pg31').feature('ptgr1').set('legendprefix', 'all, ');
model.result('pg31').run;
model.result('pg31').feature('ptgr2').set('legendprefix', 'reaction, ');
model.result('pg31').run;
model.result('pg31').feature('ptgr3').set('legendprefix', 'volume change, ');
model.result('pg29').run;
model.result('pg31').run;
model.result('pg31').setIndex('looplevel', [2], 1);
model.result('pg31').run;
model.result('pg31').setIndex('looplevel', [1], 1);
model.result('pg31').run;
model.result('pg31').setIndex('looplevel', [2], 1);
model.result('pg31').run;
model.result('pg31').setIndex('looplevel', [3], 1);
model.result('pg31').run;
model.result('pg23').run;
model.result('pg23').run;
model.result('pg17').run;
model.result('pg19').run;
model.result('pg20').run;
model.result('pg1').run;
model.result('pg6').run;
model.result('pg8').run;
model.result.create('pg32', 'PlotGroup1D');
model.result('pg32').run;
model.result.move('pg32', 5);
model.result('pg32').label('cs_surface');
model.result('pg32').set('data', 'dset3');
model.result('pg32').create('ptgr1', 'PointGraph');
model.result('pg32').feature('ptgr1').selection.set([2]);
model.result('pg32').feature('ptgr1').set('legend', true);
model.result('pg32').feature('ptgr1').set('expr', 'cs_surface');
model.result('pg30').run;
model.result('pg30').run;
model.result('pg32').run;
model.result('pg32').feature('ptgr1').set('expr', 'cs_surf/cs_max_neg');
model.result('pg32').run;
model.result('pg32').run;
model.result('pg32').run;
model.result('pg32').run;
model.result('pg32').feature('ptgr1').set('expr', '(max(1-cs_surf/cs_max_neg,eps^2))^aa_neg*(min(cs_surf/cs_max_neg,1))^ac_neg');
model.result('pg32').run;
model.result('pg8').run;
model.result('pg32').run;
model.result('pg32').feature('ptgr1').set('expr', 'cs_surf/cs_max_neg');
model.result('pg32').run;
model.result('pg32').run;
model.result('pg8').run;
model.result('pg15').run;
model.result('pg23').run;
model.result('pg6').run;
model.result('pg1').run;
model.result('pg1').set('data', 'dset3');
model.result('pg1').run;
model.result('pg1').feature('ptgr1').selection.set([2]);
model.result('pg1').run;
model.result('pg1').run;
model.result('pg1').feature('ptgr1').set('expr', 'eta');
model.result('pg1').run;
model.result('pg1').feature('ptgr1').set('expr', 'T_h_micro*omega/J_c_micro^(2/3)/F_const');
model.result('pg1').run;
model.result('pg1').feature('ptgr1').set('expr', 'eta-T_h_micro*omega/J_c_micro^(2/3)/F_const');
model.result('pg1').run;
model.result('pg1').run;
model.result('pg1').feature('ptgr1').set('expr', '-T_h_micro*omega/J_c_micro^(2/3)/F_const');
model.result('pg1').run;
model.result('pg1').feature('ptgr1').set('expr', 'eta');
model.result('pg1').run;
model.result('pg29').run;
model.result('pg26').run;
model.result('pg26').run;
model.result('pg1').run;
model.result('pg1').feature('ptgr1').set('expr', 'eta-T_h_micro*omega/J_c_micro^(2/3)/F_const');
model.result('pg1').run;
model.result('pg20').run;
model.result('pg1').run;
model.result('pg20').run;
model.result('pg20').run;
model.result('pg20').run;
model.result('pg19').run;
model.result('pg1').run;
model.result('pg20').run;
model.result.create('pg33', 'PlotGroup1D');
model.result('pg33').run;
model.result('pg33').label('Dphi of the domain');
model.result('pg33').create('lngr1', 'LineGraph');
model.result('pg33').feature('lngr1').selection.set([1]);
model.result('pg33').run;
model.result('pg33').set('data', 'dset3');
model.result('pg33').setIndex('looplevelinput', 'manual', 0);
model.result('pg33').setIndex('looplevel', [2], 0);
model.result('pg33').run;
model.result('pg33').feature('lngr1').set('expr', 'Dphi');
model.result('pg33').run;
model.result('pg33').run;
model.result('pg33').setIndex('looplevel', [9], 0);
model.result('pg33').run;
model.result('pg33').run;
model.result('pg33').feature('lngr1').set('legend', true);
model.result('pg33').run;
model.result('pg20').run;
model.result('pg29').run;
model.result('pg33').run;
model.result('pg33').run;
model.result('pg33').setIndex('looplevel', [13], 0);
model.result('pg33').run;
model.result('pg33').setIndex('looplevel', [14], 0);
model.result('pg33').run;
model.result('pg33').setIndex('looplevel', [15], 0);
model.result('pg33').run;
model.result('pg33').setIndex('looplevel', [18], 0);
model.result('pg33').run;
model.result('pg33').setIndex('looplevel', [14], 0);
model.result('pg33').run;
model.result('pg33').setIndex('looplevel', [15], 0);
model.result('pg33').run;
model.result('pg33').setIndex('looplevel', [16], 0);
model.result('pg33').run;
model.result('pg33').setIndex('looplevel', [17], 0);
model.result('pg33').run;
model.result('pg33').setIndex('looplevel', [20], 0);
model.result('pg33').run;
model.result('pg33').setIndex('looplevel', [23], 0);
model.result('pg33').run;
model.result('pg33').setIndex('looplevel', [24], 0);
model.result('pg33').setIndex('looplevel', [25], 0);
model.result('pg33').run;
model.result('pg33').run;

model.label('Agglomerate.mph');

model.result('pg33').run;

model.component('comp1').variable('var3').set('i0', 'max(eps^2,F_const*kr_neg*cs_max_neg*(max(1-cs_surf/cs_max_neg,eps^2))^aa_neg*(cs_surf/cs_max_neg)^ac_neg*(max(cl[mol/m^3]/cl_ref,eps^2))^aa_neg)');

model.result('pg27').run;
model.result('pg14').run;
model.result('pg8').run;
model.result('pg8').set('data', 'dset1');
model.result('pg8').run;
model.result('pg15').run;
model.result('pg8').run;
model.result('pg20').run;
model.result('pg20').set('data', 'dset1');
model.result('pg20').run;
model.result('pg20').set('data', 'dset3');
model.result('pg20').run;
model.result('pg8').run;
model.result('pg8').set('data', 'dset3');
model.result('pg8').run;
model.result('pg8').set('data', 'dset1');
model.result('pg8').run;
model.result('pg8').run;
model.result('pg8').feature('ptgr1').selection.set([2]);
model.result('pg8').run;
model.result('pg31').run;
model.result('pg18').run;
model.result('pg18').set('data', 'dset1');
model.result('pg18').run;
model.result('pg18').run;
model.result('pg18').run;
model.result('pg18').setIndex('looplevelinput', 'manual', 0);
model.result('pg18').setIndex('looplevel', [3], 0);
model.result('pg18').run;
model.result('pg8').run;
model.result('pg18').run;
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [14], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [15], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [16], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [17], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [18], 0);
model.result('pg18').run;
model.result('pg18').set('data', 'dset3');
model.result('pg18').setIndex('looplevelinput', 'manual', 1);
model.result('pg18').setIndex('looplevel', [2], 1);
model.result('pg18').setIndex('looplevel', [3], 1);
model.result('pg18').run;
model.result('pg18').setIndex('looplevelinput', 'manual', 0);
model.result('pg18').setIndex('looplevel', [34], 0);
model.result('pg18').run;
model.result('pg8').run;
model.result('pg8').set('data', 'dset3');
model.result('pg8').run;

model.study('std1').feature('param').setIndex('plistarr', '0.25 0.225 0.2', 0);
model.study('std1').feature('param').setIndex('plistarr', '0.25 0.24 0.23 0.225 0.2', 0);
model.study('std1').feature('param').setIndex('plistarr', '0.25 0.245 0.24 0.235 0.23 0.225 0.2', 0);
model.study('std1').feature('param').setIndex('plistarr', '0.25 0.245 0.24 0.235 0.23 0.225 0.22 0.215 0.21 0.205 0.2', 0);

model.result('pg1').run;
model.result('pg8').run;
model.result('pg20').run;
model.result('pg6').run;
model.result('pg23').run;
model.result('pg7').run;
model.result('pg10').run;
model.result('pg16').run;
model.result('pg14').run;
model.result('pg8').run;
model.result('pg15').run;
model.result('pg1').run;
model.result('pg20').run;
model.result('pg19').run;
model.result('pg1').run;
model.result('pg6').run;
model.result('pg32').run;
model.result('pg14').run;
model.result('pg21').run;
model.result('pg16').run;
model.result('pg22').run;
model.result('pg18').run;
model.result('pg18').set('data', 'dset1');
model.result('pg18').run;
model.result('pg18').setIndex('looplevelinput', 'manual', 0);
model.result('pg18').setIndex('looplevel', [36], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [37], 0);
model.result('pg18').setIndex('looplevel', [32 33 34 35 36 37], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [36], 0);
model.result('pg33').run;
model.result('pg31').run;
model.result('pg29').run;
model.result('pg8').run;
model.result('pg8').set('data', 'dset1');
model.result('pg8').run;
model.result('pg8').set('data', 'dset3');
model.result('pg8').run;
model.result('pg18').run;
model.result('pg18').set('data', 'dset3');
model.result('pg18').setIndex('looplevelinput', 'manual', 1);
model.result('pg18').setIndex('looplevel', [9], 1);
model.result('pg18').run;
model.result('pg18').setIndex('looplevelinput', 'manual', 0);
model.result('pg18').setIndex('looplevel', [37], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [35], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [33 34 35], 0);
model.result('pg18').setIndex('looplevel', [33], 0);
model.result('pg18').setIndex('looplevel', [32], 0);
model.result('pg18').setIndex('looplevel', [32 33 34 35 36 37], 0);
model.result('pg18').run;
model.result('pg18').set('data', 'dset1');
model.result('pg18').run;
model.result('pg17').run;
model.result('pg17').set('data', 'dset1');
model.result('pg17').run;
model.result('pg17').set('data', 'dset3');
model.result('pg17').run;

model.label('Agglomerate.mph');

model.result('pg17').run;
model.result('pg20').run;
model.result('pg6').run;
model.result('pg32').run;
model.result('pg20').run;
model.result('pg29').run;
model.result('pg16').run;
model.result('pg22').run;
model.result('pg8').run;
model.result('pg8').set('data', 'dset1');
model.result('pg8').run;
model.result('pg8').set('data', 'dset3');
model.result('pg8').run;
model.result('pg8').run;
model.result('pg8').setIndex('looplevelinput', 'manual', 1);
model.result('pg8').run;
model.result('pg22').run;
model.result('pg20').run;
model.result('pg8').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').setIndex('looplevelinput', 'manual', 1);
model.result('pg19').setIndex('looplevel', [1], 1);
model.result('pg19').run;
model.result('pg19').setIndex('looplevel', [3], 1);
model.result('pg19').run;
model.result('pg17').run;
model.result('pg20').run;
model.result('pg19').run;
model.result('pg8').run;
model.result('pg14').run;
model.result('pg15').run;
model.result('pg22').run;
model.result('pg16').run;
model.result('pg21').run;
model.result('pg18').run;
model.result('pg18').set('data', 'dset3');
model.result('pg18').setIndex('looplevelinput', 'manual', 1);
model.result('pg18').setIndex('looplevel', [3], 1);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [9], 1);
model.result('pg18').run;
model.result('pg18').set('data', 'dset1');
model.result('pg18').run;
model.result('pg30').run;
model.result('pg24').run;
model.result('pg25').run;
model.result('pg20').run;
model.result('pg29').run;
model.result('pg31').run;
model.result('pg18').run;
model.result('pg24').run;
model.result('pg24').run;
model.result('pg24').run;
model.result('pg24').run;
model.result('pg24').set('data', 'dset3');
model.result('pg24').run;
model.result('pg24').run;
model.result('pg24').feature('ptgr1').selection.set([2]);
model.result('pg24').run;
model.result('pg24').run;
model.result('pg24').setIndex('looplevelinput', 'manual', 1);
model.result('pg24').setIndex('looplevel', [8], 1);
model.result('pg24').setIndex('looplevel', [9], 1);
model.result('pg24').setIndex('looplevel', [7 9], 1);
model.result('pg24').setIndex('looplevel', [5 7 9], 1);
model.result('pg24').setIndex('looplevel', [3 5 7 9], 1);
model.result('pg24').setIndex('looplevel', [1], 1);
model.result('pg24').setIndex('looplevel', [1 3], 1);
model.result('pg24').setIndex('looplevel', [1 3 5], 1);
model.result('pg24').setIndex('looplevel', [1 3 5 7], 1);
model.result('pg24').setIndex('looplevel', [1 3 5 7 9], 1);
model.result('pg24').run;
model.result('pg24').run;
model.result('pg24').feature('ptgr1').set('legend', false);
model.result('pg24').run;
model.result('pg24').feature('ptgr1').set('legend', true);
model.result('pg24').feature('ptgr1').set('legendmethod', 'manual');
model.result('pg24').feature('ptgr1').setIndex('legends', ['\epsilon_l_0=0.25, ' native2unicode(hex2dec({'70' 'b9'}), 'unicode') '=2'], 0);
model.result('pg24').run;
model.result('pg24').feature('ptgr1').setIndex('legends', ['\epsilon\_l\_0=0.25, ' native2unicode(hex2dec({'70' 'b9'}), 'unicode') '=2'], 0);
model.result('pg24').run;
model.result('pg24').run;
model.result('pg24').feature('ptgr1').setIndex('legends', ['\''epsilon_l_0''=0.25, ' native2unicode(hex2dec({'70' 'b9'}), 'unicode') '=2'], 0);
model.result('pg24').run;
model.result('pg24').run;
model.result('pg24').run;
model.result('pg24').feature('ptgr1').setIndex('legends', ['\epsilon_l=0.25, ' native2unicode(hex2dec({'70' 'b9'}), 'unicode') '=2'], 0);
model.result('pg24').run;
model.result('pg24').feature('ptgr1').setIndex('legends', ['\epsilon\_l=0.25, ' native2unicode(hex2dec({'70' 'b9'}), 'unicode') '=2'], 0);
model.result('pg24').run;
model.result('pg24').run;
model.result('pg24').run;
model.result('pg24').feature('ptgr1').setIndex('legends', ['\epsilon=0.25, ' native2unicode(hex2dec({'70' 'b9'}), 'unicode') '=2'], 0);
model.result('pg24').run;
model.result('pg24').feature('ptgr1').setIndex('legends', ['\epsilon_\l=0.25, ' native2unicode(hex2dec({'70' 'b9'}), 'unicode') '=2'], 0);
model.result('pg24').run;
model.result('pg24').run;
model.result('pg24').run;
model.result('pg24').feature('ptgr1').setIndex('legends', ['\epsilon_l=0.25, ' native2unicode(hex2dec({'70' 'b9'}), 'unicode') '=2'], 0);
model.result('pg24').feature('ptgr1').setIndex('legends', ['\carepsilon_l=0.25, ' native2unicode(hex2dec({'70' 'b9'}), 'unicode') '=2'], 0);
model.result('pg24').feature('ptgr1').setIndex('legends', ['\varepsilon_l=0.25, ' native2unicode(hex2dec({'70' 'b9'}), 'unicode') '=2'], 0);
model.result('pg24').run;
model.result('pg24').feature('ptgr1').setIndex('legends', ['0.2epsl_l_0=4, ' native2unicode(hex2dec({'70' 'b9'}), 'unicode') '=2'], 1);
model.result('pg24').feature('ptgr1').setIndex('legends', '\varepsilon_l=0.25', 0);
model.result('pg24').feature('ptgr1').setIndex('legends', '0.2epsl_l_0=4', 1);
model.result('pg24').feature('ptgr1').setIndex('legends', 'epsl_l_0=0.23', 2);
model.result('pg24').feature('ptgr1').setIndex('legends', 'epsl_l_0=0.22', 3);
model.result('pg24').feature('ptgr1').setIndex('legends', 'epsl_l_0=0.21', 4);
model.result('pg24').feature('ptgr1').setIndex('legends', 'epsl_l_0=0.24', 1);
model.result('pg24').feature('ptgr1').setIndex('legends', '\varepsilon_l=0.24', 1);
model.result('pg24').feature('ptgr1').setIndex('legends', '\varepsilon_l=0.23', 2);
model.result('pg24').feature('ptgr1').setIndex('legends', '\varepsilon_l=0.22', 3);
model.result('pg24').feature('ptgr1').setIndex('legends', '\varepsilon_l=0.21', 4);
model.result('pg24').feature('ptgr1').setIndex('legends', '\varepsilon''_l''=0.25', 0);
model.result('pg24').feature('ptgr1').setIndex('legends', '\varepsilon_l=0.25', 0);
model.result('pg24').feature('ptgr1').setIndex('legends', '\varepsilon _l=0.25', 0);
model.result('pg24').feature('ptgr1').setIndex('legends', '\varepsilon^l=0.25', 0);
model.result('pg24').feature('ptgr1').setIndex('legends', '\varepsilon_l=0.25', 0);
model.result('pg24').feature('ptgr1').setIndex('legends', '\varepsilon_l''=0.25', 0);
model.result('pg24').feature('ptgr1').setIndex('legends', '\varepsilon''_l''=0.25', 0);
model.result('pg24').feature('ptgr1').setIndex('legends', '''\varepsilon_l''=0.25', 0);
model.result('pg24').feature('ptgr1').setIndex('legends', '\varepsilon_l=0.25', 0);
model.result('pg24').feature('ptgr1').setIndex('legends', '\varepsilon__l=0.25', 0);
model.result('pg24').feature('ptgr1').setIndex('legends', '\varepsilon l=0.25', 0);
model.result('pg24').feature('ptgr1').setIndex('legends', '\varepsilonl=0.25', 0);
model.result('pg24').feature('ptgr1').setIndex('legends', '\varepsilon l=0.25', 0);
model.result('pg24').feature('ptgr1').setIndex('legends', '\varepsilon_l=0.25', 0);
model.result('pg24').feature('ptgr1').setIndex('legends', '\varepsilon(_l)=0.25', 0);
model.result('pg24').feature('ptgr1').setIndex('legends', '\varepsilon_l=0.25', 0);
model.result('pg19').run;
model.result('pg19').setIndex('looplevel', [1], 1);
mode