
model.component('comp2').geom('geom3').feature('r1').set('size', {'L' 'rp_primary'});

model.param.set('rp_primary', '1[um]');

model.component('comp2').geom('geom3').runPre('fin');
model.component('comp2').geom('geom3').run;

model.component('comp2').mesh('mesh3').run;

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.component('comp1').physics('g2').feature('gfeq1').setIndex('Ga', 'T_xx_M', 0);

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.component('comp1').physics('g2').feature('cons1').setIndex('R', 'T_xx_M', 0);

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.result('pg1').run;
model.result('pg32').run;

model.component('comp1').physics('g').feature('dir1').setIndex('useDirichletCondition', 1, 2);
model.component('comp1').physics('g').feature('dir1').setIndex('useDirichletCondition', 0, 2);
model.component('comp1').physics('g').feature('init1').set('phis', 'mat1.elpot.Eeq_int1(cs_surf/cs_max_neg)');

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.result('pg17').run;
model.result('pg20').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').feature('ptgr1').set('expr', 'phis-phil');
model.result('pg19').run;
model.result('pg19').run;
model.result('pg8').run;

model.component('comp1').physics('g').feature('flux1').active(false);

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.result('pg6').run;
model.result('pg8').run;
model.result('pg14').run;
model.result('pg14').run;
model.result('pg17').run;
model.result('pg23').run;
model.result('pg23').run;
model.result('pg23').run;
model.result('pg25').run;
model.result('pg26').run;
model.result('pg27').run;
model.result('pg28').run;
model.result('pg29').run;
model.result('pg31').run;
model.result('pg35').run;
model.result('pg35').run;
model.result('pg35').run;
model.result('pg34').run;
model.result('pg2').run;
model.result('pg38').run;
model.result('pg38').run;
model.result('pg38').feature('glob1').setIndex('expr', 'phis', 0);
model.result('pg38').run;
model.result('pg38').run;
model.result('pg38').feature('glob1').setIndex('expr', '', 0);
model.result('pg38').feature.remove('glob1');
model.result('pg38').run;
model.result('pg39').set('window', 'window1');
model.result('pg39').run;
model.result('pg38').run;
model.result('pg38').create('lngr1', 'LineGraph');
model.result('pg38').feature('lngr1').selection.set([1]);
model.result('pg38').feature('lngr1').set('expr', 'phis');
model.result('pg38').run;

model.component('comp1').physics('g').feature('flux2').setIndex('g', 'i_input', 2);

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.component('comp1').physics('g').feature('flux1').active(true);

model.result('pg27').run;
model.result('pg28').run;
model.result('pg38').run;
model.result('pg38').run;
model.result('pg38').feature('lngr1').set('expr', 'phil');
model.result('pg38').run;
model.result('pg38').feature('lngr1').set('expr', 'j_react_micro');
model.result('pg38').feature('lngr1').set('descr', 'reaction current for reference configuration in macroscale');
model.result('pg38').run;
model.result('pg38').feature('lngr1').set('expr', 'eta');
model.result('pg38').run;

model.component('comp1').physics('g').feature('flux2').setIndex('g', '-i_input', 2);

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.sol('sol1').feature('t1').feature('fc1').set('dtech', 'hnlin');

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.sol('sol1').feature.move('t1', 0);
model.sol('sol1').feature.move('t1', 2);

model.result('pg38').run;
model.result('pg38').run;

model.component('comp1').physics('g').feature.move('flux1', 5);

model.result('pg38').run;
model.result('pg38').feature('lngr1').set('expr', 'T_xx_M');
model.result('pg38').run;
model.result('pg38').feature('lngr1').set('expr', 'T_yy_M');
model.result('pg38').run;
model.result('pg2').run;
model.result('pg2').run;
model.result('pg2').run;

model.component('comp1').physics('g').feature('dir1').setIndex('weakConstraints', 1, 0);

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.result('pg38').run;
model.result('pg38').feature('lngr1').set('expr', 'i0');
model.result('pg38').run;
model.result('pg38').feature('lngr1').set('expr', 'j_react_micro');
model.result('pg38').run;

model.sol('sol1').feature('t1').set('control', 'time');

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.label('Electrode_model.mph');

model.result('pg26').run;

model.label('Electrode_model.mph');

model.component('comp1').physics('g').feature('flux1').active(false);
model.component('comp1').physics('g').feature.remove('flux1');

model.param.set('I_input', 'Q_total*C/3600[s]');
model.param.set('C', '1');
model.param.set('ks', '1[S/m]');

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.sol('sol1').feature('t1').feature('st1').setIndex('stopcondarr', 'comp1.phis-comp1.phil<0', 0);
model.sol('sol1').feature('t1').feature('st1').setIndex('stopcondarr', 'comp1.ppb1<0', 0);

model.component('comp1').probe('pdom1').feature('ppb1').set('expr', 'phis-phil');
model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.sol('sol1').feature('t1').feature('fc1').set('dtech', 'const');

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.sol('sol1').runAll;

model.result('pg17').run;
model.result('pg38').run;
model.result('pg19').run;
model.result('pg20').run;
model.result('pg1').run;
model.result('pg6').run;
model.result('pg32').run;
model.result('pg25').run;
model.result('pg24').run;
model.result('pg30').run;
model.result('pg18').run;
model.result('pg10').run;
model.result('pg10').feature('ptgr1').set('expr', 'T_xx_M');
model.result('pg10').run;
model.result('pg10').run;
model.result('pg10').feature('ptgr2').set('expr', 'T_yy_M');
model.result('pg10').run;
model.result('pg10').run;
model.result('pg10').run;
model.result('pg10').run;
model.result('pg22').run;
model.result('pg15').run;
model.result('pg15').run;
model.result.dataset('cpt1').set('pointx', 'L range(0,L/5,L)');
model.result('pg16').feature('ptgr1').set('hasmultilevel', false);
model.result('pg16').feature('ptgr1').set('showunitcombo', true);
model.result('pg16').feature('ptgr1').set('evalmethodactive', 'off');
model.result('pg16').feature('ptgr1').set('xdataevalmethodactive', 'off');
model.result('pg15').feature('ptgr1').set('hasmultilevel', false);
model.result('pg15').feature('ptgr1').set('showunitcombo', true);
model.result('pg15').feature('ptgr1').set('evalmethodactive', 'off');
model.result('pg15').feature('ptgr1').set('xdataevalmethodactive', 'off');
model.result('pg14').feature('ptgr1').set('hasmultilevel', false);
model.result('pg14').feature('ptgr1').set('showunitcombo', true);
model.result('pg14').feature('ptgr1').set('evalmethodactive', 'off');
model.result('pg14').feature('ptgr1').set('xdataevalmethodactive', 'off');
model.result('pg16').feature('ptgr1').set('hasmultilevel', false);
model.result('pg16').feature('ptgr1').set('showunitcombo', true);
model.result('pg16').feature('ptgr1').set('evalmethodactive', 'off');
model.result('pg16').feature('ptgr1').set('xdataevalmethodactive', 'off');
model.result('pg15').feature('ptgr1').set('hasmultilevel', false);
model.result('pg15').feature('ptgr1').set('showunitcombo', true);
model.result('pg15').feature('ptgr1').set('evalmethodactive', 'off');
model.result('pg15').feature('ptgr1').set('xdataevalmethodactive', 'off');
model.result('pg14').feature('ptgr1').set('hasmultilevel', false);
model.result('pg14').feature('ptgr1').set('showunitcombo', true);
model.result('pg14').feature('ptgr1').set('evalmethodactive', 'off');
model.result('pg14').feature('ptgr1').set('xdataevalmethodactive', 'off');
model.result('pg15').run;
model.result('pg14').run;
model.result('pg8').run;
model.result('pg8').run;
model.result('pg8').run;
model.result('pg8').run;
model.result('pg8').set('data', 'cpt1');
model.result('pg8').run;
model.result.dataset('cpt1').set('pointx', 'range(0,L/5,L)');
model.result('pg8').run;
model.result('pg8').run;
model.result('pg8').run;
model.result('pg6').run;
model.result('pg7').run;
model.result('pg7').run;
model.result('pg7').run;
model.result('pg7').run;
model.result('pg7').set('data', 'cpt1');
model.result('pg7').run;
model.result('pg27').run;
model.result('pg27').run;
model.result('pg28').run;
model.result('pg28').run;

model.component('comp1').mesh('mesh2').feature('size').set('table', 'cfd');
model.component('comp1').mesh('mesh2').run;
model.component('comp2').mesh('mesh3').feature('map1').feature('dis2').set('numelem', 30);
model.component('comp2').mesh('mesh3').run;
model.component('comp2').mesh('mesh3').feature('map1').feature('dis2').set('numelem', 100);
model.component('comp2').mesh('mesh3').run;
model.component('comp2').mesh('mesh3').run;

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.sol('sol1').runAll;

model.result('pg17').run;
model.result('pg29').run;
model.result('pg28').run;
model.result('pg28').setIndex('looplevelinput', 'manual', 0);
model.result('pg28').setIndex('looplevel', [2], 0);
model.result('pg28').run;
model.result('pg28').setIndex('looplevel', [1], 0);
model.result('pg28').run;
model.result('pg28').setIndex('looplevel', [9], 0);
model.result('pg28').run;
model.result('pg28').setIndex('looplevel', [21], 0);
model.result('pg28').run;
model.result('pg28').setIndex('looplevel', [33], 0);
model.result('pg28').run;
model.result('pg19').run;
model.result('pg35').run;
model.result('pg35').run;
model.result('pg35').run;
model.result('pg35').run;
model.result('pg35').run;
model.result('pg35').setIndex('looplevel', [3], 0);
model.result('pg35').setIndex('looplevel', [36], 0);
model.result('pg35').run;
model.result('pg34').run;
model.result.move('pg34', 3);
model.result.move('pg34', 0);
model.result('pg17').run;
model.result('pg17').run;
model.result('pg17').run;
model.result('pg35').run;
model.result('pg2').run;
model.result('pg2').label('Insertion ratio');
model.result.move('pg2', 28);
model.result('pg35').run;
model.result('pg35').run;
model.result('pg35').run;
model.result('pg35').run;
model.result.move('pg35', 28);
model.result('pg35').label([native2unicode(hex2dec({'98' '97'}), 'unicode')  native2unicode(hex2dec({'7c' '92'}), 'unicode')  native2unicode(hex2dec({'81' 'a8'}), 'unicode')  native2unicode(hex2dec({'80' 'c0'}), 'unicode') ]);
model.result('pg38').run;
model.result('pg38').run;
model.result('pg38').run;
model.result('pg38').label([native2unicode(hex2dec({'53' 'cd'}), 'unicode')  native2unicode(hex2dec({'5e' '94'}), 'unicode')  native2unicode(hex2dec({'75' '35'}), 'unicode')  native2unicode(hex2dec({'6d' '41'}), 'unicode')  native2unicode(hex2dec({'5b' 'c6'}), 'unicode')  native2unicode(hex2dec({'5e' 'a6'}), 'unicode') ]);
model.result('pg38').run;
model.result('pg39').set('window', 'window1');
model.result('pg39').run;
model.result.remove('pg39');
model.result('pg15').run;
model.result.create('pg39', 'PlotGroup1D');
model.result('pg39').run;
model.result('pg39').label('phil of the domain');
model.result('pg39').run;
model.result('pg39').run;
model.result('pg39').run;
model.result('pg39').create('lngr1', 'LineGraph');
model.result('pg39').feature('lngr1').selection.set([1]);
model.result('pg39').feature('lngr1').set('expr', 'phil');
model.result('pg39').run;
model.result('pg39').run;
model.result.move('pg39', 29);
model.result.create('pg40', 'PlotGroup1D');
model.result('pg40').run;
model.result.move('pg40', 30);
model.result('pg40').label('phis of the domian');
model.result('pg40').create('lngr1', 'LineGraph');
model.result('pg40').feature('lngr1').selection.set([1]);
model.result('pg40').feature('lngr1').set('expr', 'phis');
model.result('pg40').run;
model.result('pg40').run;
model.result('pg39').run;
model.result.move('pg39', 18);
model.result.move('pg40', 19);
model.result('pg30').run;
model.result('pg18').run;
model.result('pg30').run;
model.result('pg25').run;
model.result('pg24').run;
model.result('pg25').run;
model.result('pg25').setIndex('looplevel', [2], 0);
model.result('pg25').setIndex('looplevel', [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36], 0);
model.result('pg25').run;
model.result('pg24').run;
model.result('pg24').run;
model.result('pg24').run;
model.result.move('pg24', 17);
model.result.move('pg24', 15);
model.result('pg24').run;
model.result('pg24').run;
model.result('pg24').run;
model.result('pg24').run;
model.result('pg1').run;

model.component('comp1').physics('g2').feature('cons1').active(false);

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.sol('sol1').runAll;

model.result('pg34').run;
model.result('pg7').run;
model.result('pg7').run;
model.result('pg7').run;
model.result('pg28').run;
model.result('pg28').setIndex('looplevel', [3], 0);
model.result('pg28').setIndex('looplevel', [36], 0);
model.result('pg28').run;
model.result('pg28').setIndex('looplevel', [1], 0);
model.result('pg28').run;
model.result('pg27').run;
model.result('pg28').run;
model.result('pg27').run;
model.result('pg27').run;
model.result('pg28').run;
model.result('pg28').setIndex('looplevel', [2], 0);
model.result('pg28').setIndex('looplevel', [14], 0);
model.result('pg28').run;
model.result('pg28').setIndex('looplevel', [27], 0);
model.result('pg28').run;
model.result('pg28').setIndex('looplevel', [35], 0);
model.result('pg28').run;
model.result('pg27').run;
model.result('pg28').run;
model.result('pg27').run;
model.result('pg27').run;
model.result('pg27').run;
model.result('pg28').run;
model.result('pg2').run;
model.result('pg2').set('looplevel', [35]);
model.result('pg2').run;
model.result('pg2').set('allowtableupdate', false);
model.result('pg2').set('xlabel', '');
model.result('pg2').set('ylabel', '');
model.result('pg2').feature('surf1').set('rangeunit', '1');
model.result('pg2').feature('surf1').set('rangecolormin', 6.62710463208527E-4);
model.result('pg2').feature('surf1').set('rangecolormax', 0.15669325609071416);
model.result('pg2').feature('surf1').set('rangecoloractive', 'off');
model.result('pg2').feature('surf1').set('rangedatamin', 6.62710463208527E-4);
model.result('pg2').feature('surf1').set('rangedatamax', 0.15669325609071416);
model.result('pg2').feature('surf1').set('rangedataactive', 'off');
model.result('pg2').feature('surf1').set('rangeactualminmax', [6.62710463208527E-4 0.15669325609071416]);
model.result('pg2').set('allowtableupdate', true);

model.param.set('E', '10[GPa]');
model.param.set('epsl_l_0', '0.5');

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.sol('sol1').runAll;

model.result('pg34').run;
model.result('pg28').run;
model.result('pg28').setIndex('looplevel', [258], 0);
model.result('pg28').run;
model.result('pg28').setIndex('looplevel', [359], 0);
model.result('pg28').run;
model.result('pg28').setIndex('looplevel', [360], 0);
model.result('pg28').run;
model.result('pg17').run;
model.result('pg2').run;
model.result('pg2').set('looplevel', [359]);
model.result('pg2').run;
model.result('pg2').set('allowtableupdate', false);
model.result('pg2').set('xlabel', '');
model.result('pg2').set('ylabel', '');
model.result('pg2').feature('surf1').set('rangeunit', '1');
model.result('pg2').feature('surf1').set('rangecolormin', 0.0012869206785759658);
model.result('pg2').feature('surf1').set('rangecolormax', 0.9340585137881575);
model.result('pg2').feature('surf1').set('rangecoloractive', 'off');
model.result('pg2').feature('surf1').set('rangedatamin', 0.0012869206785759658);
model.result('pg2').feature('surf1').set('rangedatamax', 0.9340585137881575);
model.result('pg2').feature('surf1').set('rangedataactive', 'off');
model.result('pg2').feature('surf1').set('rangeactualminmax', [0.0012869206785759658 0.9340585137881575]);
model.result('pg2').set('allowtableupdate', true);
model.result('pg35').run;
model.result('pg35').setIndex('looplevel', [359], 0);
model.result('pg35').run;
model.result('pg35').setIndex('looplevel', [360], 0);
model.result('pg35').run;
model.result('pg37').run;
model.result('pg37').run;
model.result('pg37').run;
model.result('pg33').run;
model.result('pg33').feature('lngr1').set('expr', 'phis-phil');
model.result('pg33').run;
model.result('pg33').run;
model.result('pg18').run;
model.result('pg18').setIndex('looplevelinput', 'manual', 0);
model.result('pg18').setIndex('looplevel', [360], 0);
model.result('pg18').run;

model.param.set('epsl_l_0', '0.6');

model.study('std1').feature('time').set('tlist', 'range(0,1,3600)');
model.study('std1').create('param', 'Parametric');
model.study('std1').feature('param').setIndex('pname', 'T', 0);
model.study('std1').feature('param').setIndex('plistarr', '', 0);
model.study('std1').feature('param').setIndex('punit', '', 0);
model.study('std1').feature('param').setIndex('pname', 'T', 0);
model.study('std1').feature('param').setIndex('plistarr', '', 0);
model.study('std1').feature('param').setIndex('punit', '', 0);
model.study('std1').feature('param').setIndex('pname', 'C', 0);
model.study('std1').feature('param').setIndex('plistarr', '1 2 3', 0);

model.batch.create('p1', 'Parametric');
model.batch('p1').study('std1');
model.batch('p1').create('so1', 'Solutionseq');
model.batch('p1').feature('so1').set('seq', 'sol1');
model.batch('p1').feature('so1').set('store', 'on');
model.batch('p1').feature('so1').set('clear', 'on');
model.batch('p1').feature('so1').set('psol', 'none');
model.batch('p1').set('pname', {'C'});
model.batch('p1').set('plistarr', {'1 2 3'});
model.batch('p1').set('sweeptype', 'sparse');
model.batch('p1').set('probesel', 'all');
model.batch('p1').set('probes', {'pdom1' 'dom1'});
model.batch('p1').set('plot', 'off');
model.batch('p1').set('err', 'on');
model.batch('p1').attach('std1');
model.batch('p1').set('control', 'param');

model.sol.create('sol2');
model.sol('sol2').study('std1');
model.sol('sol2').label([native2unicode(hex2dec({'53' 'c2'}), 'unicode')  native2unicode(hex2dec({'65' '70'}), 'unicode')  native2unicode(hex2dec({'53' '16'}), 'unicode')  native2unicode(hex2dec({'89' 'e3'}), 'unicode') ' 1']);

model.batch('p1').feature('so1').set('psol', 'sol2');

model.result.create('pg42', 'PlotGroup2D');
model.result('pg42').set('data', 'dset8');
model.result('pg42').create('surf1', 'Surface');
model.result('pg42').feature('surf1').set('expr', 'u');
model.result.create('pg43', 'PlotGroup2D');
model.result('pg43').set('data', 'dset8');
model.result('pg43').create('surf1', 'Surface');
model.result('pg43').feature('surf1').set('expr', 'cs');
model.result.create('pg44', 'PlotGroup1D');
model.result('pg44').set('data', 'dset7');
model.result('pg44').create('lngr1', 'LineGraph');
model.result('pg44').feature('lngr1').set('xdata', 'expr');
model.result('pg44').feature('lngr1').set('xdataexpr', 'x');
model.result('pg44').feature('lngr1').selection.all;
model.result('pg44').feature('lngr1').set('expr', 'cl');
model.result.create('pg45', 'PlotGroup1D');
model.result('pg45').set('data', 'dset7');
model.result('pg45').create('lngr1', 'LineGraph');
model.result('pg45').feature('lngr1').set('xdata', 'expr');
model.result('pg45').feature('lngr1').set('xdataexpr', 'x');
model.result('pg45').feature('lngr1').selection.all;
model.result('pg45').feature('lngr1').set('expr', 'uM');
model.result.create('pg46', 'PlotGroup1D');
model.result('pg46').set('data', 'dset7');
model.result('pg46').create('lngr1', 'LineGraph');
model.result('pg46').feature('lngr1').set('xdata', 'expr');
model.result('pg46').feature('lngr1').set('xdataexpr', 'x');
model.result('pg46').feature('lngr1').selection.all;
model.result('pg46').feature('lngr1').set('expr', 'epsl_l');

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.batch('p1').run;

model.result('pg42').run;
model.result('pg19').run;
model.result('pg19').set('data', 'dset7');
model.result('pg19').run;
model.result('pg7').run;
model.result('pg7').setIndex('looplevelinput', 'manual', 0);
model.result('pg34').run;
model.result('pg34').setIndex('looplevelinput', 'manual', 0);
model.result('pg34').set('data', 'dset7');
model.result('pg34').run;
model.result('pg34').run;
model.result('pg34').run;
model.result('pg34').run;
model.result('pg34').run;
model.result('pg17').run;
model.result.dataset('cpt1').set('data', 'dset7');
model.result('pg21').run;
model.result('pg8').run;
model.result('pg8').setIndex('looplevelinput', 'manual', 1);
model.result('pg8').setIndex('looplevel', [2], 1);
model.result('pg8').run;
model.result('pg8').setIndex('looplevel', [3], 1);
model.result('pg8').run;
model.result('pg8').setIndex('looplevel', [1], 1);
model.result('pg8').run;
model.result('pg32').run;
model.result('pg37').run;
model.result('pg37').setIndex('looplevelinput', 'manual', 0);
model.result('pg37').setIndex('looplevel', [1], 0);
model.result('pg37').run;
model.result('pg37').set('data', 'dset7');
model.result('pg37').setIndex('looplevelinput', 'manual', 1);
model.result('pg37').setIndex('looplevel', [2], 1);
model.result('pg37').run;
model.result('pg37').setIndex('looplevel', [3], 1);
model.result('pg37').run;
model.result('pg37').setIndex('looplevelinput', 'last', 0);
model.result('pg37').run;
model.result('pg37').setIndex('looplevel', [1], 1);
model.result('pg37').run;
model.result('pg35').run;
model.result('pg35').set('data', 'dset7');
model.result('pg35').setIndex('looplevelinput', 'manual', 1);
model.result('pg35').setIndex('looplevel', [2], 1);
model.result('pg35').run;
model.result('pg35').run;
model.result('pg35').run;
model.result('pg35').run;
model.result('pg35').setIndex('looplevel', [1], 1);
model.result('pg35').run;
model.result('pg35').run;
model.result('pg35').run;
model.result('pg35').run;
model.result('pg35').run;
model.result('pg35').run;
model.result('pg35').feature('lngr1').selection.set([1]);
model.result('pg35').run;
model.result('pg35').setIndex('looplevel', [2], 1);
model.result('pg35').run;
model.result('pg35').setIndex('looplevel', [3], 1);
model.result('pg35').run;
model.result('pg44').run;
model.result('pg45').run;
model.result('pg46').run;
model.result('pg44').run;
model.result('pg39').run;
model.result('pg40').run;
model.result('pg25').run;
model.result('pg27').run;
model.result('pg27').set('data', 'dset7');
model.result('pg27').setIndex('looplevelinput', 'manual', 1);
model.result('pg27').setIndex('looplevel', [2], 1);
model.result('pg27').run;
model.result('pg27').setIndex('looplevel', [3], 1);
model.result('pg27').run;
model.result('pg28').run;
model.result('pg28').set('data', 'dset7');
model.result('pg28').setIndex('looplevelinput', 'manual', 1);
model.result('pg28').setIndex('looplevel', [2], 1);
model.result('pg28').run;
model.result('pg28').setIndex('looplevel', [3], 1);
model.result('pg28').setIndex('looplevel', [2], 1);
model.result('pg28').setIndex('looplevel', [1], 1);
model.result('pg28').setIndex('looplevel', [2], 1);
model.result('pg28').setIndex('looplevel', [3], 1);
model.result('pg28').run;
model.result('pg28').setIndex('looplevel', [1], 1);
model.result('pg28').run;
model.result('pg28').setIndex('looplevel', [2], 1);
model.result('pg28').run;
model.result('pg30').run;
model.result('pg30').set('data', 'dset7');
model.result('pg30').run;
model.result('pg30').setIndex('looplevelinput', 'manual', 1);
model.result('pg30').setIndex('looplevel', [3], 1);
model.result('pg30').setIndex('looplevel', [1], 1);
model.result('pg30').run;
model.result('pg30').run;
model.result('pg30').setIndex('looplevel', [2], 1);
model.result('pg30').run;
model.result('pg17').run;
model.result('pg14').run;
model.result('pg8').run;
model.result('pg32').run;
model.result('pg38').run;
model.result('pg44').run;
model.result.remove('pg44');
model.result('pg30').run;
model.result('pg18').run;
model.result('pg18').set('data', 'dset7');
model.result('pg18').setIndex('looplevelinput', 'manual', 1);
model.result('pg18').setIndex('looplevel', [2], 1);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [3], 1);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [1], 1);
model.result('pg18').run;
model.result('pg45').run;
model.result('pg45').run;
model.result('pg45').run;
model.result('pg45').setIndex('looplevelinput', 'manual', 1);
model.result('pg24').run;
model.result('pg24').run;
model.result('pg24').run;
model.result('pg24').set('data', 'dset7');
model.result('pg24').run;
model.result('pg24').feature('ptgr1').set('legend', true);
model.result('pg24').feature('ptgr1').set('legendmethod', 'automatic');
model.result('pg24').run;
model.result('pg22').run;
model.result('pg20').run;
model.result.create('pg47', 'PlotGroup1D');
model.result('pg47').run;
model.result('pg47').label('Deformation gradient of the domain');
model.result.move('pg47', 25);
model.result('pg47').create('lngr1', 'LineGraph');
model.result('pg47').feature('lngr1').selection.set([1]);
model.result('pg47').feature('lngr1').set('expr', 'det_F_M');
model.result('pg47').feature('lngr1').set('descr', '');
model.result('pg47').run;
model.result('pg47').run;
model.result('pg47').run;
model.result('pg47').feature('lngr1').set('data', 'parent');
model.result('pg47').run;
model.result('pg47').set('data', 'dset7');
model.result('pg47').run;
model.result('pg47').setIndex('looplevelinput', 'manual', 1);
model.result('pg47').setIndex('looplevel', [3], 1);
model.result('pg47').setIndex('looplevel', [1], 1);
model.result('pg47').run;
model.result.create('pg48', 'PlotGroup1D');
model.result('pg48').run;
model.result('pg48').label('Strain of the domain');
model.result.move('pg48', 22);
model.result('pg46').run;
model.result('pg43').run;
model.result('pg45').run;
model.result.move('pg45', 32);
model.result('pg45').label('uM of the domain');
model.result.move('pg45', 28);
model.result('pg29').run;
model.result('pg45').run;
model.result.move('pg45', 27);
model.result('pg47').run;
model.result('pg45').run;
model.result('pg47').run;
model.result('pg45').run;
model.result('pg45').setIndex('looplevel', [1], 1);
model.result('pg45').run;
model.result('pg28').run;
model.result('pg27').run;
model.result('pg43').run;
model.result('pg43').set('looplevel', [56 1]);
model.result('pg43').run;
model.result('pg42').run;
model.result('pg43').run;
model.result('pg43').run;
model.result('pg43').run;
model.result.move('pg43', 35);
model.result('pg43').label('stress');
model.result('pg43').run;
model.result('pg43').feature('surf1').set('expr', 'T_RR');
model.result('pg43').feature('surf1').set('descr', '');
model.result('pg43').run;
model.result('pg43').run;
model.result('pg43').set('looplevel', [626 1]);
model.result('pg43').run;
model.result('pg30').run;
model.result('pg2').run;
model.result('pg43').run;
model.result('pg43').set('allowtableupdate', false);
model.result('pg43').set('xlabel', '');
model.result('pg43').set('ylabel', '');
model.result('pg43').feature('surf1').set('rangeunit', 'Pa');
model.result('pg43').feature('surf1').set('rangecolormin', -3026399.739920168);
model.result('pg43').feature('surf1').set('rangecolormax', 1.179490759697087E9);
model.result('pg43').feature('surf1').set('rangecoloractive', 'off');
model.result('pg43').feature('surf1').set('rangedatamin', -3026399.739920168);
model.result('pg43').feature('surf1').set('rangedatamax', 1.179490759697087E9);
model.result('pg43').feature('surf1').set('rangedataactive', 'off');
model.result('pg43').feature('surf1').set('rangeactualminmax', [-3026399.739920168 1.179490759697087E9]);
model.result('pg43').set('allowtableupdate', true);
model.result.table('evl2').addRow([7.322815508814529E-5 8.934741799748736E-7 2.3286471284913254E8], [0 0 0]);
model.result.table('evl2').clearTableData;
model.result.table('evl2').setTableData([]);
model.result.table('evl2').addRow([6.985919026192278E-5 9.268303529097466E-7 1.5816298185565162E8], [0 0 0]);
model.result('pg43').run;
model.result('pg43').feature('surf1').set('expr', 'T_tt');
model.result('pg43').run;
model.result('pg43').run;
model.result('pg48').run;
model.result.move('pg48', 25);
model.result('pg28').run;
model.result('pg28').run;
model.result('pg28').feature('lngr1').set('expr', 'T_yy_M');
model.result('pg28').run;
model.result('pg28').run;
model.result('pg28').setIndex('looplevel', [1], 1);
model.result('pg28').run;
model.result('pg27').run;
model.result('pg43').run;
model.result('pg43').label('radial stress');
model.result('pg43').set('allowtableupdate', false);
model.result('pg43').set('xlabel', '');
model.result('pg43').set('ylabel', '');
model.result('pg43').feature('surf1').set('rangeunit', 'Pa');
model.result('pg43').feature('surf1').set('rangecolormin', -1.2145438571297095E9);
model.result('pg43').feature('surf1').set('rangecolormax', 1.176971578731505E9);
model.result('pg43').feature('surf1').set('rangecoloractive', 'off');
model.result('pg43').feature('surf1').set('rangedatamin', -1.2145438571297095E9);
model.result('pg43').feature('surf1').set('rangedatamax', 1.176971578731505E9);
model.result('pg43').feature('surf1').set('rangedataactive', 'off');
model.result('pg43').feature('surf1').set('rangeactualminmax', [-1.2145438571297095E9 1.176971578731505E9]);
model.result('pg43').set('allowtableupdate', true);
model.result.table('evl2').addRow([7.377728252322413E-6 8.214963145292131E-7 -6.392749366346262E7], [0 0 0]);
model.result.table('evl2').addRow([7.014780749159399E-6 9.553027666697744E-7 -7.723233245065269E7], [0 0 0]);
model.result.table('evl2').addRow([7.138102773751598E-6 2.413323443306581E-7 1.6911257976685104E8], [0 0 0]);
model.result('pg46').run;
model.result('pg42').run;
model.result.move('pg42', 36);
model.result('pg42').label('Tangential stress');
model.result('pg42').run;
model.result('pg42').feature('surf1').set('expr', 'T_tt');
model.result('pg42').feature('surf1').set('descr', '');
model.result('pg42').run;
model.result('pg42').set('allowtableupdate', false);
model.result('pg42').set('xlabel', '');
model.result('pg42').set('ylabel', '');
model.result('pg42').feature('surf1').set('rangeunit', 'Pa');
model.result('pg42').feature('surf1').set('rangecolormin', -5.829775760146642E9);
model.result('pg42').feature('surf1').set('rangecolormax', 1.3663339949997227E9);
model.result('pg42').feature('surf1').set('rangecoloractive', 'off');
model.result('pg42').feature('surf1').set('rangedatamin', -5.829775760146642E9);
model.result('pg42').feature('surf1').set('rangedatamax', 1.3663339949997227E9);
model.result('pg42').feature('surf1').set('rangedataactive', 'off');
model.result('pg42').feature('surf1').set('rangeactualminmax', [-5.829775760146642E9 1.3663339949997227E9]);
model.result('pg42').set('allowtableupdate', true);
model.result.table('evl2').addRow([3.355668013682589E-5 9.819116257858695E-7 -1.7675225935585093E8], [0 0 0]);
model.result.table('evl2').addRow([3.355668013682589E-5 9.819116257858695E-7 -1.7675225935585093E8], [0 0 0]);
model.result.table('evl2').addRow([7.460048800567165E-5 2.2971835278440267E-7 1.3588627030958264E9], [0 0 0]);
model.result.table('evl2').addRow([2.513989238650538E-5 8.722927304916084E-7 -9.430844924861515E7], [0 0 0]);
model.result('pg42').run;
model.result('pg38').run;
model.result.move('pg38', 34);
model.result('pg38').run;
model.result('pg38').run;
model.result('pg35').run;

model.param.set('E', '50[GPa]');
model.param.set('epsl_l_0', '0.3');

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.study('std1').feature('param').setIndex('pname', 'epsl_l_0', 0);
model.study('std1').feature('param').setIndex('plistarr', '0.2 0.4 0.6', 0);

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.component('comp1').variable('var3').set('T_h_all', 'T_h_micro+T_h_M/epsl_s');

model.param.set('rp_primary', '5[um]');

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.batch('p1').run;

model.result('pg34').run;
model.result('pg34').setIndex('looplevelinput', 'manual', 1);
model.result('pg34').setIndex('looplevel', [1], 1);
model.result('pg34').run;
model.result('pg34').setIndex('looplevel', [3], 1);
model.result('pg34').run;
model.result('pg7').run;
model.result('pg28').run;
model.result('pg28').run;
model.result('pg28').feature('lngr1').set('expr', 'T_xx_M');
model.result('pg28').run;

model.component('comp1').physics('g2').create('cons2', 'Constraint', 0);
model.component('comp1').physics('g2').feature('cons2').setIndex('R', 'uM', 0);
model.component('comp1').physics('g2').feature('cons2').selection.set([2]);
model.component('comp1').physics('g2').feature('cons2').setIndex('weakConstraints', 1, 0);
model.component('comp1').physics('g2').feature('cons2').setIndex('weakConstraints', 0, 0);

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.batch('p1').run;

model.result('pg34').run;
model.result('pg19').run;
model.result('pg8').run;
model.result('pg7').run;

model.label('Electrode_model.mph');

model.result('pg7').run;
model.result('pg7').set('showlegends', false);
model.result('pg28').run;
model.result('pg28').setIndex('looplevelinput', 'manual', 1);
model.result('pg28').setIndex('looplevel', [2], 1);
model.result('pg28').run;
model.result('pg28').setIndex('looplevel', [3], 1);
model.result('pg28').run;
model.result('pg28').setIndex('looplevel', [1], 1);
model.result('pg28').run;
model.result('pg28').setIndex('looplevel', [3], 1);
model.result('pg28').run;
model.result('pg45').run;
model.result('pg47').run;
model.result('pg47').run;
model.result('pg47').run;
model.result('pg25').run;
model.result('pg1').run;
model.result('pg20').run;
model.result('pg1').run;
model.result('pg1').run;
model.result('pg1').feature('ptgr1').set('expr', 'T_h_all*omega/J_c_micro^(2/3)/F_const');
model.result('pg1').run;
model.result('pg1').run;
model.result('pg6').run;
model.result('pg32').run;
model.result('pg8').run;
model.result('pg37').run;

model.component('comp1').physics('g2').feature('cons2').active(false);
model.component('comp1').physics('g2').feature('cons1').active(true);

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.batch('p1').run;

model.result('pg34').run;
model.result('pg1').run;
model.result('pg20').run;
model.result('pg20').run;
model.result('pg20').feature('ptgr1').selection.set([1]);
model.result('pg20').run;
model.result('pg20').run;
model.result('pg20').run;
model.result('pg20').run;
model.result('pg20').run;
model.result('pg20').run;
model.result('pg1').run;
model.result('pg1').run;
model.result('pg1').run;
model.result('pg1').set('data', 'dset7');
model.result('pg1').run;
model.result('pg7').run;
model.result('pg28').run;
model.result('pg28').setIndex('looplevel', [1], 1);
model.result('pg28').run;
model.result('pg27').run;
model.result('pg27').setIndex('looplevelinput', 'manual', 1);
model.result('pg27').setIndex('looplevel', [2], 1);
model.result('pg27').setIndex('looplevel', [3], 1);
model.result('pg27').setIndex('looplevel', [2], 1);
model.result('pg27').setIndex('looplevel', [1], 1);
model.result('pg27').setIndex('looplevel', [2], 1);
model.result('pg27').setIndex('looplevel', [3], 1);
model.result('pg27').run;
model.result('pg27').setIndex('looplevel', [1], 1);
model.result('pg27').run;
model.result('pg37').run;

model.param.set('rp_primary', '1[um]');

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.batch('p1').run;

model.result('pg34').run;
model.result('pg34').setIndex('looplevel', [1], 1);
model.result('pg34').run;
model.result('pg7').run;
model.result('pg28').run;
model.result('pg28').run;
model.result('pg28').run;
model.result('pg28').setIndex('looplevel', [3], 1);
model.result('pg28').run;

model.sol('sol1').feature('t1').feature('fc1').set('ntolfact', 0.1);
model.sol('sol1').feature('t1').feature('fc1').set('dtech', 'auto');

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.batch('p1').run;

model.result('pg34').run;

model.label('Electrode_model.mph');

model.setGroupByType(false);
model.component('comp1').setGroupByType(false);
model.component('comp2').setGroupByType(false);

model.component('comp2').physics('g3').setGroupBySpaceDimension(false);
model.component('comp2').physics('g4').setGroupBySpaceDimension(false);
model.component('comp1').physics('g').setGroupBySpaceDimension(false);
model.component('comp1').physics('g2').setGroupBySpaceDimension(false);
model.component('comp1').physics('dode').setGroupBySpaceDimension(false);

model.result('pg34').run;
model.result('pg17').run;
model.result('pg20').run;
model.result('pg20').run;
model.result('pg20').run;
model.result('pg20').run;

model.component('comp1').probe('pdom1').setIndex('coords1', 0, 0);
model.component('comp1').probe('pdom1').feature('ppb1').set('expr', 'phis');

model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').label('Phis');
model.result('pg20').run;
model.result('pg19').run;
model.result('pg19').feature('ptgr1').selection.set([1]);
model.result('pg19').run;
model.result('pg19').feature('ptgr1').set('expr', 'phis');
model.result('pg19').run;
model.result('pg19').run;
model.result('pg1').run;
model.result('pg1').run;
model.result('pg6').run;
model.result('pg32').run;
model.result('pg8').run;
model.result('pg8').setIndex('looplevelinput', 'manual', 1);
model.result('pg8').setIndex('looplevel', [1], 1);
model.result('pg8').run;
model.result('pg8').setIndex('looplevel', [2], 1);
model.result('pg8').run;
model.result('pg8').setIndex('looplevel', [3], 1);
model.result('pg8').run;
model.result('pg8').setIndex('looplevel', [2], 1);
model.result('pg8').setIndex('looplevel', [1], 1);
model.result('pg8').run;
model.result('pg15').run;
model.result('pg23').run;
model.result('pg24').run;
model.result('pg24').setIndex('looplevelinput', 'manual', 1);
model.result('pg24').setIndex('looplevel', [3], 1);
model.result('pg24').run;
model.result('pg24').setIndex('looplevel', [2], 1);
model.result('pg24').run;
model.result('pg24').setIndex('looplevel', [3], 1);
model.result('pg24').run;
model.result('pg24').setIndex('looplevel', [1], 1);
model.result('pg24').run;
model.result('pg18').run;
model.result('pg18').run;
model.result('pg18').run;
model.result('pg18').setIndex('looplevelinput', 'manual', 1);
model.result('pg18').setIndex('looplevel', [1], 1);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [2], 1);
model.result('pg18').run;
model.result('pg10').run;
model.result('pg18').run;
model.result('pg28').run;
model.result('pg27').run;
model.result('pg28').run;
model.result('pg28').setIndex('looplevel', [1], 1);
model.result('pg28').run;
model.result('pg28').run;
model.result('pg28').run;
model.result('pg28').run;
model.result('pg28').run;
model.result('pg28').run;
model.result('pg28').setIndex('looplevelinput', 'manualindices', 0);
model.result('pg28').setIndex('looplevelindices', 1, 0);
model.result('pg28').run;
model.result('pg28').setIndex('looplevelindices', 11, 0);
model.result('pg28').run;
model.result('pg28').setIndex('looplevel', [3], 1);
model.result('pg28').run;
model.result('pg28').setIndex('looplevelindices', 880, 0);
model.result('pg28').run;
model.result('pg27').run;
model.result('pg27').setIndex('looplevel', [3], 1);
model.result('pg27').run;
model.result('pg45').run;
model.result('pg47').run;
model.result('pg35').run;
model.result('pg35').run;
model.result('pg37').run;
model.result('pg35').run;
model.result('pg35').setIndex('looplevelinput', 'manual', 1);
model.result('pg35').setIndex('looplevel', [2], 1);
model.result('pg35').run;
model.result('pg35').setIndex('looplevel', [3], 1);
model.result('pg35').run;
model.result('pg2').run;
model.result('pg2').set('data', 'dset8');
model.result('pg2').set('looplevel', [11 1]);
model.result('pg2').run;
model.result('pg2').set('looplevel', [11 2]);
model.result('pg2').run;
model.result('pg2').set('looplevel', [137 2]);
model.result('pg2').run;
model.result('pg2').set('looplevel', [137 3]);
model.result('pg2').run;
model.result('pg2').set('looplevel', [879 3]);
model.result('pg2').run;
model.result('pg38').run;
model.result('pg38').set('data', 'dset7');
model.result('pg38').setIndex('looplevelinput', 'manual', 1);
model.result('pg38').setIndex('looplevel', [2], 1);
model.result('pg38').run;
model.result('pg38').setIndex('looplevel', [1], 1);
model.result('pg38').run;
model.result('pg38').setIndex('looplevelinput', 'manualindices', 0);
model.result('pg38').setIndex('looplevelindices', 9, 0);
model.result('pg38').run;
model.result('pg38').setIndex('looplevelindices', 1, 0);
model.result('pg38').run;
model.result('pg38').setIndex('looplevelindices', 2, 0);
model.result('pg38').run;
model.result('pg38').setIndex('looplevelindices', 3, 0);
model.result('pg38').run;
model.result('pg38').setIndex('looplevelindices', '3 range(5,1,11)', 0);
model.result('pg38').setIndex('looplevelindices', 'range(5,1,11)', 0);
model.result('pg38').run;
model.result('pg38').setIndex('looplevelindices', 'range(8,1,11)', 0);
model.result('pg38').run;
model.result('pg38').run;
model.result('pg38').run;

model.label('Electrode_model_with_3_electrode.mph');

model.result('pg19').run;

model.param.set('omega', '(3-1)/cs_max_neg');
model.param.set('cs_max_neg', '2e5[mol/m^3]');
model.param.set('epsl_l_0', '0.55');
model.param.set('epsl_s_0', '1-epsl_l_0-0.08');
model.param.remove('eta_0');

model.component('comp1').variable('var4').remove({'epsl_0' 'epsl_1'});

model.func.create('int1', 'Interpolation');
model.func('int1').set('funcname', 'Ds_int1');
model.func('int1').setIndex('table', '6.09586713866797e-14', 0, 0);
model.func('int1').setIndex('table', '', 0, 1);
model.func('int1').setIndex('table', '1.41719267253605e-14', 1, 0);
model.func('int1').setIndex('table', '', 1, 1);
model.func('int1').setIndex('table', '8.98091362343611e-15', 2, 0);
model.func('int1').setIndex('table', '', 2, 1);
model.func('int1').setIndex('table', '7.20479226621999e-15', 3, 0);
model.func('int1').setIndex('table', '', 3, 1);
model.func('int1').setIndex('table', '5.89264611468891e-15', 4, 0);
model.func('int1').setIndex('table', '', 4, 1);
model.func('int1').setIndex('table', '3.78555280845809e-15', 5, 0);
model.func('int1').setIndex('table', '', 5, 1);
model.func('int1').setIndex('table', '3.11938895891955e-15', 6, 0);
model.func('int1').setIndex('table', '', 6, 1);
model.func('int1').setIndex('table', '1.02571391147464e-15', 7, 0);
model.func('int1').setIndex('table', '', 7, 1);
model.func('int1').setIndex('table', '6.42146029324720e-16', 8, 0);
model.func('int1').setIndex('table', '', 8, 1);
model.func('int1').setIndex('table', '4.46598588237730e-16', 9, 0);
model.func('int1').setIndex('table', '', 9, 1);
model.func('int1').setIndex('table', '', 0, 0);
model.func('int1').setIndex('table', '6.09586713866797e-14', 0, 1);
model.func('int1').setIndex('table', '', 1, 0);
model.func('int1').setIndex('table', '1.41719267253605e-14', 1, 1);
model.func('int1').setIndex('table', '', 2, 0);
model.func('int1').setIndex('table', '8.98091362343611e-15', 2, 1);
model.func('int1').setIndex('table', '', 3, 0);
model.func('int1').setIndex('table', '7.20479226621999e-15', 3, 1);
model.func('int1').setIndex('table', '', 4, 0);
model.func('int1').setIndex('table', '5.89264611468891e-15', 4, 1);
model.func('int1').setIndex('table', '', 5, 0);
model.func('int1').setIndex('table', '3.78555280845809e-15', 5, 1);
model.func('int1').setIndex('table', '', 6, 0);
model.func('int1').setIndex('table', '3.11938895891955e-15', 6, 1);
model.func('int1').setIndex('table', '', 7, 0);
model.func('int1').setIndex('table', '1.02571391147464e-15', 7, 1);
model.func('int1').setIndex('table', '', 8, 0);
model.func('int1').setIndex('table', '6.42146029324720e-16', 8, 1);
model.func('int1').setIndex('table', '', 9, 0);
model.func('int1').setIndex('table', '4.46598588237730e-16', 9, 1);
model.func('int1').setIndex('table', 1, 0, 0);
model.func('int1').setIndex('table', 0.9, 0, 0);
model.func('int1').setIndex('table', 1, 0, 0);
model.func('int1').setIndex('table', 0.9, 1, 0);
model.func('int1').setIndex('table', 0.8, 2, 0);
model.func('int1').setIndex('table', 0.7, 3, 0);
model.func('int1').setIndex('table', 0.6, 4, 0);
model.func('int1').setIndex('table', 0.5, 5, 0);
model.func('int1').setIndex('table', 0.4, 6, 0);
model.func('int1').setIndex('table', 0.3, 7, 0);
model.func('int1').setIndex('table', 0.2, 8, 0);
model.func('int1').setIndex('table', 0, 8, 0);
model.func('int1').setIndex('table', 0.2, 8, 0);
model.func('int1').setIndex('table', 0.1, 9, 0);
model.func.create('int2', 'Interpolation');
model.func('int2').set('funcname', 'i0_int1');
model.func('int2').setIndex('table', 1.40694327557474, 0, 0);
model.func('int2').setIndex('table', '', 0, 1);
model.func('int2').setIndex('table', 0.818635844953175, 1, 0);
model.func('int2').setIndex('table', '', 1, 1);
model.func('int2').setIndex('table', 0.675449172152469, 2, 0);
model.func('int2').setIndex('table', '', 2, 1);
model.func('int2').setIndex('table', 0.566552545864849, 3, 0);
model.func('int2').setIndex('table', '', 3, 1);
model.func('int2').setIndex('table', 0.458349596520331, 4, 0);
model.func('int2').setIndex('table', '', 4, 1);
model.func('int2').setIndex('table', 0.358001998578781, 5, 0);
model.func('int2').setIndex('table', '', 5, 1);
model.func('int2').setIndex('table', 0.270462184856707, 6, 0);
model.func('int2').setIndex('table', '', 6, 1);
model.func('int2').setIndex('table', 0.161119331558135, 7, 0);
model.func('int2').setIndex('table', '', 7, 1);
model.func('int2').setIndex('table', 0.0627391329194658, 8, 0);
model.func('int2').setIndex('table', '', 8, 1);
model.func('int2').setIndex('table', '0.0916998500247530', 9, 0);
model.func('int2').setIndex('table', '', 9, 1);
model.func('int2').setIndex('table', 1.40694327557474, 0, 0);
model.func('int2').setIndex('table', '', 0, 1);
model.func('int2').setIndex('table', 0.818635844953175, 1, 0);
model.func('int2').setIndex('table', '', 1, 1);
model.func('int2').setIndex('table', 0.675449172152469, 2, 0);
model.func('int2').setIndex('table', '', 2, 1);
model.func('int2').setIndex('table', 0.566552545864849, 3, 0);
model.func('int2').setIndex('table', '', 3, 1);
model.func('int2').setIndex('table', 0.458349596520331, 4, 0);
model.func('int2').setIndex('table', '', 4, 1);
model.func('int2').setIndex('table', 0.358001998578781, 5, 0);
model.func('int2').setIndex('table', '', 5, 1);
model.func('int2').setIndex('table', 0.270462184856707, 6, 0);
model.func('int2').setIndex('table', '', 6, 1);
model.func('int2').setIndex('table', 0.161119331558135, 7, 0);
model.func('int2').setIndex('table', '', 7, 1);
model.func('int2').setIndex('table', 0.0627391329194658, 8, 0);
model.func('int2').setIndex('table', '', 8, 1);
model.func('int2').setIndex('table', '0.0916998500247530', 9, 0);
model.func('int2').setIndex('table', '', 9, 1);
model.func('int2').setIndex('table', '', 0, 0);
model.func('int2').setIndex('table', 1.40694327557474, 0, 1);
model.func('int2').setIndex('table', '', 1, 0);
model.func('int2').setIndex('table', 0.818635844953175, 1, 1);
model.func('int2').setIndex('table', '', 2, 0);
model.func('int2').setIndex('table', 0.675449172152469, 2, 1);
model.func('int2').setIndex('table', '', 3, 0);
model.func('int2').setIndex('table', 0.566552545864849, 3, 1);
model.func('int2').setIndex('table', '', 4, 0);
model.func('int2').setIndex('table', 0.458349596520331, 4, 1);
model.func('int2').setIndex('table', '', 5, 0);
model.func('int2').setIndex('table', 0.358001998578781, 5, 1);
model.func('int2').setIndex('table', '', 6, 0);
model.func('int2').setIndex('table', 0.270462184856707, 6, 1);
model.func('int2').setIndex('table', 0.270462184856707, 6, 1);
model.func('int2').setIndex('table', '', 7, 0);
model.func('int2').setIndex('table', 0.161119331558135, 7, 1);
model.func('int2').setIndex('table', '', 8, 0);
model.func('int2').setIndex('table', 0.0627391329194658, 8, 1);
model.func('int2').setIndex('table', 0.0627391329194658, 8, 1);
model.func('int2').setIndex('table', '', 9, 0);
model.func('int2').setIndex('table', '0.0916998500247530', 9, 1);
model.func('int2').setIndex('table', '0.0916998500247530', 9, 1);
model.func('int2').setIndex('table', 1, 0, 0);
model.func('int2').setIndex('table', 0.9, 1, 0);
model.func('int2').setIndex('table', 0.8, 2, 0);
model.func('int2').setIndex('table', 0.4, 3, 0);
model.func('int2').setIndex('table', 0.7, 3, 0);
model.func('int2').setIndex('table', 0.6, 4, 0);
model.func('int2').setIndex('table', 0.5, 5, 0);
model.func('int2').setIndex('table', 0.4, 6, 0);
model.func('int2').setIndex('table', 0.3, 7, 0);
model.func('int2').setIndex('table', 0.2, 8, 0);
model.func('int2').setIndex('table', 0.1, 9, 0);

model.component('comp1').variable('var3').set('i0', 'max(eps^2,i0_int1(cs_surf/cs_