
model.result('pg18').run;
model.result('pg37').run;
model.result('pg37').set('data', 'dset11');
model.result('pg37').setIndex('looplevelinput', 'manual', 2);
model.result('pg37').setIndex('looplevel', [3], 2);
model.result('pg37').run;
model.result('pg37').run;
model.result('pg37').run;
model.result('pg37').setIndex('looplevel', [4], 2);
model.result('pg37').run;
model.result('pg23').run;
model.result('pg25').run;
model.result('pg25').run;
model.result('pg25').setIndex('looplevelindices', 10, 0);
model.result('pg25').run;
model.result('pg30').run;
model.result('pg6').run;
model.result('pg37').run;
model.result('pg38').run;
model.result('pg38').set('data', 'dset11');
model.result('pg38').setIndex('looplevelinput', 'manual', 2);
model.result('pg38').setIndex('looplevel', [3], 2);
model.result('pg38').run;
model.result('pg38').setIndex('looplevelinput', 'manualindices', 0);
model.result('pg38').setIndex('looplevelindices', 10, 0);
model.result('pg38').run;
model.result('pg38').setIndex('looplevelindices', 5, 0);
model.result('pg38').run;
model.result('pg38').setIndex('looplevel', [4], 2);
model.result('pg38').run;
model.result('pg33').run;
model.result('pg33').run;
model.result('pg33').run;
model.result('pg33').set('data', 'dset11');
model.result('pg33').setIndex('looplevelinput', 'manual', 2);
model.result('pg33').setIndex('looplevel', [3], 2);
model.result('pg33').run;
model.result('pg33').setIndex('looplevelinput', 'manualindices', 0);
model.result('pg33').setIndex('looplevelindices', 5, 0);
model.result('pg33').run;
model.result('pg39').run;
model.result('pg39').set('data', 'dset11');
model.result('pg39').setIndex('looplevelinput', 'manual', 2);
model.result('pg39').setIndex('looplevel', [3], 2);
model.result('pg39').run;
model.result('pg39').setIndex('looplevel', [4], 2);
model.result('pg39').run;

model.func('int5').setIndex('table', 8000, 32, 0);
model.func('int5').setIndex('table', 0.001, 32, 1);

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.batch('p2').run('compute');

model.result('pg19').run;

model.func('int5').remove('table', 31);
model.func('int5').remove('table', 31);
model.func('int4').setIndex('table', 4000, 40, 0);
model.func('int4').setIndex('table', '1E-12', 40, 1);
model.func('int4').setIndex('table', '5E-13', 40, 1);

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.study('std2').feature('param').setIndex('plistarr', '0.5 1 2', 0);

model.param.remove('kl');
model.param.remove('Dl');

model.func('int4').setIndex('table', '1E-13', 40, 1);

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.func('int5').setIndex('table', 8000, 31, 0);
model.func('int5').setIndex('table', '1e-5', 31, 1);
model.func('int5').setIndex('table', 4000, 31, 0);
model.func('int5').setIndex('table', '1e-4', 31, 1);
model.func('int5').setIndex('table', 3500, 31, 0);

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.func('int5').setIndex('fununit', 'S/m', 0);

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.result('pg8').run;
model.result('pg8').setIndex('looplevel', [2], 2);
model.result('pg8').run;
model.result('pg39').run;
model.result('pg39').setIndex('looplevel', [2], 2);
model.result('pg39').run;
model.result('pg39').setIndex('looplevelinput', 'last', 0);
model.result('pg39').setIndex('looplevelinput', 'manualindices', 0);
model.result('pg39').setIndex('looplevelindices', 5, 0);
model.result('pg39').run;
model.result('pg39').setIndex('looplevelindices', 10, 0);
model.result('pg39').run;
model.result('pg39').setIndex('looplevelindices', 20, 0);
model.result('pg39').run;
model.result('pg39').setIndex('looplevelindices', 30, 0);
model.result('pg39').run;
model.result('pg39').setIndex('looplevelindices', 25, 0);
model.result('pg39').run;
model.result('pg39').setIndex('looplevelindices', 'range(1,10,30)', 0);
model.result('pg39').run;
model.result('pg10').run;
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [2], 2);
model.result('pg18').run;
model.result('pg18').set('data', 'dset1');
model.result('pg18').run;
model.result('pg18').run;
model.result('pg18').feature('lngr1').selection.set([1]);
model.result('pg18').run;
model.result('pg18').run;
model.result('pg18').set('data', 'dset9');
model.result('pg18').run;
model.result('pg33').run;
model.result('pg18').run;
model.result('pg33').run;
model.result('pg39').run;
model.result('pg39').set('data', 'dset9');
model.result('pg39').run;
model.result('pg25').run;
model.result('pg40').run;
model.result('pg39').run;
model.result('pg40').run;
model.result('pg18').run;
model.result('pg18').set('data', 'dset11');
model.result('pg18').run;
model.result('pg18').setIndex('looplevelinput', 'manual', 2);
model.result('pg18').setIndex('looplevel', [2], 2);
model.result('pg18').run;
model.result('pg18').setIndex('looplevelinput', 'interp', 0);
model.result('pg18').setIndex('looplevelinput', 'manualindices', 0);
model.result('pg18').setIndex('looplevelindices', 'range(1,5,30)', 0);
model.result('pg18').run;
model.result('pg8').run;
model.result('pg8').setIndex('looplevel', [1], 2);
model.result('pg8').run;
model.result('pg8').setIndex('looplevel', [2], 2);
model.result('pg8').run;

model.func('int5').setIndex('table', 3200, 31, 0);
model.func('int5').setIndex('table', '1e-6', 31, 1);
model.func('int5').setIndex('table', 3250, 31, 0);
model.func('int4').setIndex('table', 3500, 40, 0);
model.func('int4').setIndex('table', '1E-14', 40, 1);

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.func('int4').setIndex('fununit', 'm^2/s', 0);
model.func('int4').setIndex('table', '1E-13', 40, 1);
model.func('int5').setIndex('table', '1e-3', 31, 1);

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.result('pg18').run;
model.result('pg18').setIndex('looplevelinput', 'manual', 2);
model.result('pg18').setIndex('looplevel', [2], 2);
model.result('pg18').run;
model.result('pg18').run;
model.result('pg19').run;
model.result('pg39').run;
model.result('pg39').set('data', 'dset11');
model.result('pg39').run;
model.result('pg39').setIndex('looplevelinput', 'manual', 2);
model.result('pg39').setIndex('looplevel', [2], 2);
model.result('pg39').run;
model.result('pg39').setIndex('looplevelinput', 'manualindices', 0);
model.result('pg39').setIndex('looplevelindices', 'range(1,5,30)', 0);
model.result('pg39').run;
model.result('pg39').run;
model.result('pg39').feature('lngr1').set('legend', true);
model.result('pg39').run;
model.result('pg39').setIndex('looplevelindices', 'range(1,5,40)', 0);
model.result('pg39').run;
model.result('pg39').setIndex('looplevelinput', 'all', 0);
model.result('pg39').run;
model.result('pg8').run;
model.result('pg19').run;

model.func('int4').setIndex('table', '1E-12', 40, 1);
model.func('int5').setIndex('table', '1e-2', 31, 1);

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.batch('p2').run('compute');

model.result('pg19').run;

model.study.create('std3');
model.study('std3').create('time', 'Transient');
model.study('std3').feature('time').setSolveFor('/physics/g3', true);
model.study('std3').feature('time').setSolveFor('/physics/g4', true);
model.study('std3').feature('time').setSolveFor('/physics/g', true);
model.study('std3').feature('time').setSolveFor('/physics/g2', true);
model.study('std3').feature('time').setSolveFor('/physics/dode', true);
model.study.move('std3', 1);
model.study('std3').feature('time').set('useinitsol', true);
model.study('std3').feature('time').set('initmethod', 'sol');
model.study('std3').feature('time').set('initstudy', 'std1');
model.study('std3').feature('time').set('solnum', 101);
model.study('std3').feature('time').set('usesol', true);
model.study('std3').feature('time').set('notsolmethod', 'sol');
model.study('std3').feature('time').set('notstudy', 'std1');
model.study('std3').feature('time').set('notsolnum', 101);

model.sol.create('sol9');
model.sol('sol9').study('std3');

model.study('std3').feature('time').set('notlistsolnum', 1);
model.study('std3').feature('time').set('notsolnum', '101');
model.study('std3').feature('time').set('listsolnum', 1);
model.study('std3').feature('time').set('solnum', '101');

model.sol('sol9').create('st1', 'StudyStep');
model.sol('sol9').feature('st1').set('study', 'std3');
model.sol('sol9').feature('st1').set('studystep', 'time');
model.sol('sol9').create('v1', 'Variables');
model.sol('sol9').feature('v1').set('control', 'time');
model.sol('sol9').create('t1', 'Time');
model.sol('sol9').feature('t1').set('tlist', 'range(0,0.1,1)');
model.sol('sol9').feature('t1').set('plot', 'off');
model.sol('sol9').feature('t1').set('plotgroup', 'pg34');
model.sol('sol9').feature('t1').set('plotfreq', 'tout');
model.sol('sol9').feature('t1').set('probesel', 'all');
model.sol('sol9').feature('t1').set('probes', {'pdom1' 'dom1'});
model.sol('sol9').feature('t1').set('probefreq', 'tsteps');
model.sol('sol9').feature('t1').set('atolglobalvaluemethod', 'factor');
model.sol('sol9').feature('t1').set('endtimeinterpolation', true);
model.sol('sol9').feature('t1').set('control', 'time');
model.sol('sol9').feature('t1').create('seDef', 'Segregated');
model.sol('sol9').feature('t1').create('fc1', 'FullyCoupled');
model.sol('sol9').feature('t1').feature('fc1').set('linsolver', 'dDef');
model.sol('sol9').feature('t1').feature.remove('fcDef');
model.sol('sol9').feature('t1').feature.remove('seDef');
model.sol('sol9').attach('std3');

model.study('std3').feature('time').set('tlist', 'range(0,10,720)');
model.study('std3').create('param', 'Parametric');
model.study('std3').feature('param').setIndex('pname', 'T', 0);
model.study('std3').feature('param').setIndex('plistarr', '', 0);
model.study('std3').feature('param').setIndex('punit', 'K', 0);
model.study('std3').feature('param').setIndex('pname', 'T', 0);
model.study('std3').feature('param').setIndex('plistarr', '', 0);
model.study('std3').feature('param').setIndex('punit', 'K', 0);
model.study('std3').feature('param').setIndex('pname', 'C', 0);
model.study('std3').feature('param').setIndex('plistarr', 0, 0);

model.sol('sol9').study('std3');

model.study('std3').feature('time').set('notlistsolnum', 1);
model.study('std3').feature('time').set('notsolnum', '101');
model.study('std3').feature('time').set('listsolnum', 1);
model.study('std3').feature('time').set('solnum', '101');

model.sol('sol9').feature.remove('t1');
model.sol('sol9').feature.remove('v1');
model.sol('sol9').feature.remove('st1');
model.sol('sol9').create('st1', 'StudyStep');
model.sol('sol9').feature('st1').set('study', 'std3');
model.sol('sol9').feature('st1').set('studystep', 'time');
model.sol('sol9').create('v1', 'Variables');
model.sol('sol9').feature('v1').set('control', 'time');
model.sol('sol9').create('t1', 'Time');
model.sol('sol9').feature('t1').set('tlist', 'range(0,10,720)');
model.sol('sol9').feature('t1').set('plot', 'off');
model.sol('sol9').feature('t1').set('plotgroup', 'pg34');
model.sol('sol9').feature('t1').set('plotfreq', 'tout');
model.sol('sol9').feature('t1').set('probesel', 'all');
model.sol('sol9').feature('t1').set('probes', {'pdom1' 'dom1'});
model.sol('sol9').feature('t1').set('probefreq', 'tsteps');
model.sol('sol9').feature('t1').set('atolglobalvaluemethod', 'factor');
model.sol('sol9').feature('t1').set('endtimeinterpolation', true);
model.sol('sol9').feature('t1').set('control', 'time');
model.sol('sol9').feature('t1').create('seDef', 'Segregated');
model.sol('sol9').feature('t1').create('fc1', 'FullyCoupled');
model.sol('sol9').feature('t1').feature('fc1').set('linsolver', 'dDef');
model.sol('sol9').feature('t1').feature.remove('fcDef');
model.sol('sol9').feature('t1').feature.remove('seDef');
model.sol('sol9').attach('std3');

model.batch.create('p3', 'Parametric');
model.batch('p3').study('std3');
model.batch('p3').create('so1', 'Solutionseq');
model.batch('p3').feature('so1').set('seq', 'sol9');
model.batch('p3').feature('so1').set('store', 'on');
model.batch('p3').feature('so1').set('clear', 'on');
model.batch('p3').feature('so1').set('psol', 'none');
model.batch('p3').set('pname', {'C'});
model.batch('p3').set('plistarr', {'0'});
model.batch('p3').set('sweeptype', 'sparse');
model.batch('p3').set('probesel', 'all');
model.batch('p3').set('probes', {'pdom1' 'dom1'});
model.batch('p3').set('plot', 'off');
model.batch('p3').set('err', 'on');
model.batch('p3').attach('std3');
model.batch('p3').set('control', 'param');

model.sol.create('sol10');
model.sol('sol10').study('std3');
model.sol('sol10').label([native2unicode(hex2dec({'53' 'c2'}), 'unicode')  native2unicode(hex2dec({'65' '70'}), 'unicode')  native2unicode(hex2dec({'53' '16'}), 'unicode')  native2unicode(hex2dec({'89' 'e3'}), 'unicode') ' 1']);

model.batch('p3').feature('so1').set('psol', 'sol10');

model.result.create('pg54', 'PlotGroup2D');
model.result('pg54').set('data', 'dset16');
model.result('pg54').create('surf1', 'Surface');
model.result('pg54').feature('surf1').set('expr', 'u');
model.result.create('pg55', 'PlotGroup2D');
model.result('pg55').set('data', 'dset16');
model.result('pg55').create('surf1', 'Surface');
model.result('pg55').feature('surf1').set('expr', 'cs');
model.result.create('pg56', 'PlotGroup1D');
model.result('pg56').set('data', 'dset15');
model.result('pg56').create('lngr1', 'LineGraph');
model.result('pg56').feature('lngr1').set('xdata', 'expr');
model.result('pg56').feature('lngr1').set('xdataexpr', 'x');
model.result('pg56').feature('lngr1').selection.all;
model.result('pg56').feature('lngr1').set('expr', 'cl');
model.result.create('pg57', 'PlotGroup1D');
model.result('pg57').set('data', 'dset15');
model.result('pg57').create('lngr1', 'LineGraph');
model.result('pg57').feature('lngr1').set('xdata', 'expr');
model.result('pg57').feature('lngr1').set('xdataexpr', 'x');
model.result('pg57').feature('lngr1').selection.all;
model.result('pg57').feature('lngr1').set('expr', 'uM');
model.result.create('pg58', 'PlotGroup1D');
model.result('pg58').set('data', 'dset15');
model.result('pg58').create('lngr1', 'LineGraph');
model.result('pg58').feature('lngr1').set('xdata', 'expr');
model.result('pg58').feature('lngr1').set('xdataexpr', 'x');
model.result('pg58').feature('lngr1').selection.all;
model.result('pg58').feature('lngr1').set('expr', 'epsl_l');

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.result.remove('pg54');
model.result.remove('pg55');
model.result.remove('pg56');
model.result.remove('pg57');
model.result.remove('pg58');

model.study('std3').feature('time').set('tlist', 'range(0,10,100)');

model.sol('sol9').study('std3');

model.study('std3').feature('time').set('notlistsolnum', 1);
model.study('std3').feature('time').set('notsolnum', '101');
model.study('std3').feature('time').set('listsolnum', 1);
model.study('std3').feature('time').set('solnum', '101');

model.sol('sol9').feature.remove('t1');
model.sol('sol9').feature.remove('v1');
model.sol('sol9').feature.remove('st1');
model.sol('sol9').create('st1', 'StudyStep');
model.sol('sol9').feature('st1').set('study', 'std3');
model.sol('sol9').feature('st1').set('studystep', 'time');
model.sol('sol9').create('v1', 'Variables');
model.sol('sol9').feature('v1').set('control', 'time');
model.sol('sol9').create('t1', 'Time');
model.sol('sol9').feature('t1').set('tlist', 'range(0,10,100)');
model.sol('sol9').feature('t1').set('plot', 'off');
model.sol('sol9').feature('t1').set('plotgroup', 'pg34');
model.sol('sol9').feature('t1').set('plotfreq', 'tout');
model.sol('sol9').feature('t1').set('probesel', 'all');
model.sol('sol9').feature('t1').set('probes', {'pdom1' 'dom1'});
model.sol('sol9').feature('t1').set('probefreq', 'tsteps');
model.sol('sol9').feature('t1').set('atolglobalvaluemethod', 'factor');
model.sol('sol9').feature('t1').set('endtimeinterpolation', true);
model.sol('sol9').feature('t1').set('control', 'time');
model.sol('sol9').feature('t1').create('seDef', 'Segregated');
model.sol('sol9').feature('t1').create('fc1', 'FullyCoupled');
model.sol('sol9').feature('t1').feature('fc1').set('linsolver', 'dDef');
model.sol('sol9').feature('t1').feature.remove('fcDef');
model.sol('sol9').feature('t1').feature.remove('seDef');
model.sol('sol9').attach('std3');

model.batch('p3').feature.remove('so1');
model.batch('p3').create('so1', 'Solutionseq');
model.batch('p3').feature('so1').set('seq', 'sol9');
model.batch('p3').feature('so1').set('store', 'on');
model.batch('p3').feature('so1').set('clear', 'on');
model.batch('p3').feature('so1').set('psol', 'sol10');
model.batch('p3').set('pname', {'C'});
model.batch('p3').set('plistarr', {'0'});
model.batch('p3').set('sweeptype', 'sparse');
model.batch('p3').set('probesel', 'all');
model.batch('p3').set('probes', {'pdom1' 'dom1'});
model.batch('p3').set('plot', 'off');
model.batch('p3').set('err', 'on');
model.batch('p3').attach('std3');
model.batch('p3').set('control', 'param');

model.result.create('pg54', 'PlotGroup2D');
model.result('pg54').set('data', 'dset16');
model.result('pg54').create('surf1', 'Surface');
model.result('pg54').feature('surf1').set('expr', 'u');
model.result.create('pg55', 'PlotGroup2D');
model.result('pg55').set('data', 'dset16');
model.result('pg55').create('surf1', 'Surface');
model.result('pg55').feature('surf1').set('expr', 'cs');
model.result.create('pg56', 'PlotGroup1D');
model.result('pg56').set('data', 'dset15');
model.result('pg56').create('lngr1', 'LineGraph');
model.result('pg56').feature('lngr1').set('xdata', 'expr');
model.result('pg56').feature('lngr1').set('xdataexpr', 'x');
model.result('pg56').feature('lngr1').selection.all;
model.result('pg56').feature('lngr1').set('expr', 'cl');
model.result.create('pg57', 'PlotGroup1D');
model.result('pg57').set('data', 'dset15');
model.result('pg57').create('lngr1', 'LineGraph');
model.result('pg57').feature('lngr1').set('xdata', 'expr');
model.result('pg57').feature('lngr1').set('xdataexpr', 'x');
model.result('pg57').feature('lngr1').selection.all;
model.result('pg57').feature('lngr1').set('expr', 'uM');
model.result.create('pg58', 'PlotGroup1D');
model.result('pg58').set('data', 'dset15');
model.result('pg58').create('lngr1', 'LineGraph');
model.result('pg58').feature('lngr1').set('xdata', 'expr');
model.result('pg58').feature('lngr1').set('xdataexpr', 'x');
model.result('pg58').feature('lngr1').selection.all;
model.result('pg58').feature('lngr1').set('expr', 'epsl_l');

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.batch('p3').run('compute');

model.result('pg54').run;
model.result('pg46').run;
model.result('pg48').run;
model.result('pg49').run;
model.result.remove('pg49');
model.result.remove('pg50');
model.result.remove('pg51');
model.result.remove('pg52');
model.result.remove('pg53');
model.result.remove('pg54');
model.result.remove('pg55');
model.result.remove('pg56');
model.result.remove('pg57');
model.result.remove('pg58');

model.study('std2').feature('time').set('initstudy', 'std3');
model.study('std2').feature('time').set('notstudy', 'std3');
model.study('std2').feature('time').set('solnum', 'last');
model.study('std2').feature('time').set('notsolnum', 'last');

model.result('pg8').run;
model.result('pg8').run;

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.batch('p2').run('compute');

model.result('pg19').run;

model.label('Electrode_model_with_3_electrode.mph');

model.result('pg19').run;
model.result.table.remove('tbl3');
model.result.table.remove('tbl4');
model.result.table.remove('tbl5');
model.result.table.remove('tbl6');
model.result.table.create('tbl3', 'Table');
model.result.table('tbl3').label('1C');
model.result.table('tbl3').importData('F:\group\Research\Mechanic-electrochemic coupling method\Network model for electrode\1C.csv');
model.result.table.create('tbl4', 'Table');
model.result.table('tbl4').label('2C');
model.result.table('tbl4').importData('F:\group\Research\Mechanic-electrochemic coupling method\Network model for electrode\2C.csv');
model.result.table.create('tbl5', 'Table');
model.result.table('tbl5').label('3C');
model.result.table('tbl5').importData('F:\group\Research\Mechanic-electrochemic coupling method\Network model for electrode\3C.csv');
model.result.table.create('tbl6', 'Table');
model.result.table('tbl6').label('4C');
model.result.table('tbl6').importData('F:\group\Research\Mechanic-electrochemic coupling method\Network model for electrode\4C.csv');
model.result.table.create('tbl7', 'Table');
model.result.table('tbl7').label('5C');
model.result.table('tbl7').importData('F:\group\Research\Mechanic-electrochemic coupling method\Network model for electrode\5C.csv');
model.result.table.create('tbl8', 'Table');
model.result.table('tbl8').label('7C');
model.result.table('tbl8').importData('F:\group\Research\Mechanic-electrochemic coupling method\Network model for electrode\7C.csv');
model.result.table.create('tbl9', 'Table');
model.result.table('tbl9').label('9C');
model.result.table('tbl9').importData('F:\group\Research\Mechanic-electrochemic coupling method\Network model for electrode\9C.csv');
model.result.table.create('tbl10', 'Table');
model.result.table('tbl10').label('12C');
model.result.table('tbl10').importData('F:\group\Research\Mechanic-electrochemic coupling method\Network model for electrode\12C.csv');
model.result.table.create('tbl11', 'Table');
model.result.table('tbl11').label('15C');
model.result.table('tbl11').importData('F:\group\Research\Mechanic-electrochemic coupling method\Network model for electrode\15C.csv');
model.result.table.create('tbl12', 'Table');
model.result.table('tbl12').label('20C');
model.result.table('tbl12').importData('F:\group\Research\Mechanic-electrochemic coupling method\Network model for electrode\20C.csv');
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg20').run;
model.result('pg19').run;
model.result.create('pg48', 'PlotGroup1D');
model.result('pg48').set('data', 'none');
model.result('pg48').create('tblp1', 'Table');
model.result('pg48').feature('tblp1').set('source', 'table');
model.result('pg48').feature('tblp1').set('table', 'tbl3');
model.result('pg48').run;
model.result.create('pg49', 'PlotGroup1D');
model.result('pg49').set('data', 'none');
model.result('pg49').create('tblp1', 'Table');
model.result('pg49').feature('tblp1').set('source', 'table');
model.result('pg49').feature('tblp1').set('table', 'tbl4');
model.result('pg49').run;
model.result.create('pg50', 'PlotGroup1D');
model.result('pg50').set('data', 'none');
model.result('pg50').create('tblp1', 'Table');
model.result('pg50').feature('tblp1').set('source', 'table');
model.result('pg50').feature('tblp1').set('table', 'tbl5');
model.result('pg50').run;
model.result.create('pg51', 'PlotGroup1D');
model.result('pg51').set('data', 'none');
model.result('pg51').create('tblp1', 'Table');
model.result('pg51').feature('tblp1').set('source', 'table');
model.result('pg51').feature('tblp1').set('table', 'tbl6');
model.result('pg51').run;
model.result.create('pg52', 'PlotGroup1D');
model.result('pg52').set('data', 'none');
model.result('pg52').create('tblp1', 'Table');
model.result('pg52').feature('tblp1').set('source', 'table');
model.result('pg52').feature('tblp1').set('table', 'tbl7');
model.result('pg52').run;
model.result('pg52').run;
model.result.create('pg53', 'PlotGroup1D');
model.result('pg53').set('data', 'none');
model.result('pg53').create('tblp1', 'Table');
model.result('pg53').feature('tblp1').set('source', 'table');
model.result('pg53').feature('tblp1').set('table', 'tbl8');
model.result('pg53').run;
model.result.create('pg54', 'PlotGroup1D');
model.result('pg54').set('data', 'none');
model.result('pg54').create('tblp1', 'Table');
model.result('pg54').feature('tblp1').set('source', 'table');
model.result('pg54').feature('tblp1').set('table', 'tbl9');
model.result('pg54').run;
model.result.create('pg55', 'PlotGroup1D');
model.result('pg55').set('data', 'none');
model.result('pg55').create('tblp1', 'Table');
model.result('pg55').feature('tblp1').set('source', 'table');
model.result('pg55').feature('tblp1').set('table', 'tbl10');
model.result('pg55').run;
model.result.create('pg56', 'PlotGroup1D');
model.result('pg56').set('data', 'none');
model.result('pg56').create('tblp1', 'Table');
model.result('pg56').feature('tblp1').set('source', 'table');
model.result('pg56').feature('tblp1').set('table', 'tbl11');
model.result('pg56').run;
model.result.create('pg57', 'PlotGroup1D');
model.result('pg57').set('data', 'none');
model.result('pg57').create('tblp1', 'Table');
model.result('pg57').feature('tblp1').set('source', 'table');
model.result('pg57').feature('tblp1').set('table', 'tbl12');
model.result('pg57').run;
model.result('pg48').run;
model.result('pg49').run;
model.result('pg48').run;
model.result('pg48').feature('tblp1').label('1C');
model.result('pg49').run;
model.result('pg49').feature('tblp1').label('2C');
model.result('pg50').run;
model.result('pg50').feature('tblp1').label('3C');
model.result('pg51').run;
model.result('pg51').feature('tblp1').label('4C');
model.result('pg52').run;
model.result('pg52').feature('tblp1').label('5C');
model.result('pg53').run;
model.result('pg53').feature('tblp1').label('7C');
model.result('pg54').run;
model.result('pg54').feature('tblp1').label('9C');
model.result('pg55').run;
model.result('pg55').feature('tblp1').label('12C');
model.result('pg56').run;
model.result('pg56').feature('tblp1').label('15C');
model.result('pg57').run;
model.result('pg57').feature('tblp1').label('20C');
model.result('pg48').run;
model.result('pg19').run;
model.result.move('pg19', 29);
model.result.move('pg19', 33);
model.result('pg48').run;
model.result('pg19').feature.copy('tblp1', 'pg48/tblp1');
model.result('pg48').feature.remove('tblp1');
model.result('pg51').run;
model.result('pg49').run;
model.result('pg19').feature.copy('tblp2', 'pg49/tblp1');
model.result('pg49').feature.remove('tblp1');
model.result('pg51').run;
model.result('pg50').run;
model.result('pg19').feature.copy('tblp3', 'pg50/tblp1');
model.result('pg50').feature.remove('tblp1');
model.result('pg52').run;
model.result('pg51').run;
model.result('pg19').feature.copy('tblp4', 'pg51/tblp1');
model.result('pg51').feature.remove('tblp1');
model.result('pg52').run;
model.result('pg19').feature.copy('tblp5', 'pg52/tblp1');
model.result('pg52').feature.remove('tblp1');
model.result('pg53').run;
model.result('pg19').feature.copy('tblp6', 'pg53/tblp1');
model.result('pg53').feature.remove('tblp1');
model.result('pg54').run;
model.result('pg19').run;
model.result('pg54').run;
model.result('pg19').feature.copy('tblp7', 'pg54/tblp1');
model.result('pg54').feature.remove('tblp1');
model.result('pg55').run;
model.result('pg19').feature.copy('tblp8', 'pg55/tblp1');
model.result('pg55').feature.remove('tblp1');
model.result('pg56').run;
model.result('pg19').feature.copy('tblp9', 'pg56/tblp1');
model.result('pg56').feature.remove('tblp1');
model.result('pg57').run;
model.result('pg19').feature.copy('tblp10', 'pg57/tblp1');
model.result('pg57').feature.remove('tblp1');
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').feature('tblp1').label('1C-Si');
model.result('pg19').run;
model.result('pg19').feature('tblp2').label('2C-Si');
model.result('pg19').run;
model.result('pg19').feature('tblp3').label('3C-Si');
model.result('pg19').run;
model.result('pg19').feature('tblp4').label('4C-Si');
model.result('pg19').run;
model.result('pg19').feature('tblp5').label('5C-Si');
model.result('pg19').run;
model.result('pg19').feature('tblp6').label('7C-Si');
model.result('pg19').run;
model.result('pg19').feature('tblp7').label('9C-Si');
model.result('pg19').run;
model.result('pg19').feature('tblp8').label('12C-Si');
model.result('pg19').run;
model.result('pg19').feature('tblp9').label('15C-Si');
model.result('pg19').run;
model.result('pg19').feature('tblp10').label('20C-Si');

model.label('Electrode_model_with_paper.mph');

model.result('pg19').run;
model.result('pg19').run;
model.result('pg48').run;
model.result.remove('pg48');
model.result.remove('pg49');
model.result.remove('pg50');
model.result.remove('pg51');
model.result.remove('pg52');
model.result.remove('pg53');
model.result.remove('pg54');
model.result.remove('pg55');
model.result.remove('pg56');
model.result.remove('pg57');
model.result('pg2').run;
model.result('pg46').run;
model.result('pg20').run;
model.result('pg40').run;

model.label('Electrode_model_with_paper.mph');

model.result('pg40').run;
model.result('pg8').run;
model.result('pg8').run;
model.result('pg8').run;
model.result('pg8').setIndex('looplevelinput', 'manual', 2);
model.result('pg8').setIndex('looplevel', [3], 2);
model.result('pg8').run;
model.result('pg39').run;
model.result('pg39').setIndex('looplevel', [3], 2);
model.result('pg39').run;
model.result('pg40').run;
model.result('pg40').setIndex('looplevelinput', 'manual', 0);
model.result('pg40').setIndex('looplevelinput', 'all', 0);
model.result('pg40').set('data', 'dset11');
model.result('pg40').setIndex('looplevelinput', 'manual', 2);
model.result('pg40').setIndex('looplevel', [2], 2);
model.result('pg40').setIndex('looplevel', [3], 2);
model.result('pg40').run;
model.result('pg39').run;
model.result('pg23').run;
model.result('pg16').run;
model.result('pg21').run;
model.result('pg15').run;
model.result('pg17').run;
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [3], 2);
model.result('pg18').run;
model.result('pg33').run;
model.result('pg33').run;
model.result('pg33').run;
model.result('pg26').run;
model.result('pg26').run;
model.result('pg26').run;
model.result('pg38').run;
model.result('pg38').setIndex('looplevelinput', 'manual', 2);
model.result('pg38').setIndex('looplevel', [3], 2);
model.result('pg38').run;
model.result('pg38').setIndex('looplevelinput', 'manualindices', 0);
model.result('pg38').setIndex('looplevelindices', 1, 0);
model.result('pg38').setIndex('looplevelindices', 'range(1,10,90)', 0);
model.result('pg38').run;
model.result('pg38').run;
model.result('pg38').feature('lngr1').set('legend', true);
model.result('pg38').run;
model.result('pg30').run;
model.result('pg30').setIndex('looplevelinput', 'manual', 2);
model.result('pg30').setIndex('looplevel', [3], 2);
model.result('pg30').run;
model.result('pg30').run;
model.result('pg46').run;
model.result('pg46').run;
model.result('pg46').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').run;
model.result.table.remove('tbl5');
model.result.table('tbl3').importData('F:\group\Research\Mechanic-electrochemic coupling method\Network model for electrode\SiO\1C.csv');
model.result.table('tbl4').importData('F:\group\Research\Mechanic-electrochemic coupling method\Network model for electrode\SiO\2C.csv');
model.result.table('tbl6').importData('F:\group\Research\Mechanic-electrochemic coupling method\Network model for electrode\SiO\4C.csv');
model.result.table('tbl7').importData('F:\group\Research\Mechanic-electrochemic coupling method\Network model for electrode\SiO\5C.csv');
model.result.table('tbl8').importData('F:\group\Research\Mechanic-electrochemic coupling method\Network model for electrode\SiO\7C.csv');
model.result.table('tbl9').importData('F:\group\Research\Mechanic-electrochemic coupling method\Network model for electrode\SiO\9C.csv');
model.result.table('tbl10').importData('F:\group\Research\Mechanic-electrochemic coupling method\Network model for electrode\SiO\12C.csv');
model.result.table('tbl11').importData('F:\group\Research\Mechanic-electrochemic coupling method\Network model for electrode\SiO\15C.csv');
model.result.table('tbl12').importData('F:\group\Research\Mechanic-electrochemic coupling method\Network model for electrode\SiO\20C.csv');
model.result.create('pg48', 'PlotGroup1D');
model.result('pg48').set('data', 'none');
model.result('pg48').create('tblp1', 'Table');
model.result('pg48').feature('tblp1').set('source', 'table');
model.result('pg48').feature('tblp1').set('table', 'tbl3');
model.result('pg48').run;
model.result.create('pg49', 'PlotGroup1D');
model.result('pg49').set('data', 'none');
model.result('pg49').create('tblp1', 'Table');
model.result('pg49').feature('tblp1').set('source', 'table');
model.result('pg49').feature('tblp1').set('table', 'tbl4');
model.result('pg49').run;
model.result.create('pg50', 'PlotGroup1D');
model.result('pg50').set('data', 'none');
model.result('pg50').create('tblp1', 'Table');
model.result('pg50').feature('tblp1').set('source', 'table');
model.result('pg50').feature('tblp1').set('table', 'tbl6');
model.result('pg50').run;
model.result.create('pg51', 'PlotGroup1D');
model.result('pg51').set('data', 'none');
model.result('pg51').create('tblp1', 'Table');
model.result('pg51').feature('tblp1').set('source', 'table');
model.result('pg51').feature('tblp1').set('table', 'tbl7');
model.result('pg51').run;
model.result.create('pg52', 'PlotGroup1D');
model.result('pg52').set('data', 'none');
model.result('pg52').create('tblp1', 'Table');
model.result('pg52').feature('tblp1').set('source', 'table');
model.result('pg52').feature('tblp1').set('table', 'tbl8');
model.result('pg52').run;
model.result.create('pg53', 'PlotGroup1D');
model.result('pg53').set('data', 'none');
model.result('pg53').create('tblp1', 'Table');
model.result('pg53').feature('tblp1').set('source', 'table');
model.result('pg53').feature('tblp1').set('table', 'tbl9');
model.result('pg53').run;
model.result.create('pg54', 'PlotGroup1D');
model.result('pg54').set('data', 'none');
model.result('pg54').create('tblp1', 'Table');
model.result('pg54').feature('tblp1').set('source', 'table');
model.result('pg54').feature('tblp1').set('table', 'tbl10');
model.result('pg54').run;
model.result.create('pg55', 'PlotGroup1D');
model.result('pg55').set('data', 'none');
model.result('pg55').create('tblp1', 'Table');
model.result('pg55').feature('tblp1').set('source', 'table');
model.result('pg55').feature('tblp1').set('table', 'tbl11');
model.result('pg55').run;
model.result.create('pg56', 'PlotGroup1D');
model.result('pg56').set('data', 'none');
model.result('pg56').create('tblp1', 'Table');
model.result('pg56').feature('tblp1').set('source', 'table');
model.result('pg56').feature('tblp1').set('table', 'tbl12');
model.result('pg56').run;
model.result('pg48').run;
model.result('pg48').feature('tblp1').label('1C-SiO');
model.result('pg49').run;
model.result('pg49').feature('tblp1').label('2C-SiO');
model.result('pg50').run;
model.result('pg50').feature('tblp1').label('4C-SiO');
model.result('pg51').run;
model.result('pg51').feature('tblp1').label('5C-SiO');
model.result('pg52').run;
model.result('pg52').feature('tblp1').label('7C-SiO');
model.result('pg53').run;
model.result('pg53').feature('tblp1').label('9C-SiO');
model.result('pg54').run;
model.result('pg54').feature('tblp1').label('12C-SiO');
model.result('pg56').run;
model.result('pg55').run;
model.result('pg55').feature('tblp1').label('15C-SiO');
model.result('pg56').run;
model.result('pg56').feature('tblp1').label('20C-SiO');
model.result('pg48').run;
model.result('pg19').run;
model.result('pg48').feature.copy('tblp2', 'pg19/tblp1');
model.result('pg19').feature.remove('tblp1');
model.result('pg48').feature.copy('tblp3', 'pg19/tblp2');
model.result('pg19').feature.remove('tblp2');
model.result('pg48').feature.copy('tblp4', 'pg19/tblp4');
model.result('pg19').feature.remove('tblp4');
model.result('pg48').feature.copy('tblp5', 'pg19/tblp5');
model.result('pg19').feature.remove('tblp5');
model.result('pg48').feature.copy('tblp6', 'pg19/tblp6');
model.result('pg19').feature.remove('tblp6');
model.result('pg48').feature.copy('tblp7', 'pg19/tblp7');
model.result('pg19').feature.remove('tblp7');
model.result('pg48').feature.copy('tblp8', 'pg19/tblp8');
model.result('pg19').feature.remove('tblp8');
model.result('pg48').feature.copy('tblp9', 'pg19/tblp9');
model.result('pg19').feature.remove('tblp9');
model.result('pg48').feature.copy('tblp10', 'pg19/tblp10');
model.result('pg19').feature.remove('tblp10');
model.result('pg48').feature.move('tblp2', 0);
model.result('pg48').feature.move('tblp3', 1);
model.result('pg48').feature.move('tblp4', 2);
model.result('pg48').feature.move('tblp5', 3);
model.result('pg48').feature.move('tblp6', 4);
model.result('pg48').feature.move('tblp7', 5);
model.result('pg48').feature.move('tblp8', 6);
model.result('pg48').feature.move('tblp9', 7);
model.result('pg48').feature.move('tblp10', 8);
model.result('pg48').run;
model.result('pg19').feature.copy('tblp1', 'pg48/tblp1');
model.result('pg48').feature.remove('tblp1');
model.result('pg49').run;
model.result('pg19').feature.copy('tblp2', 'pg49/tblp1');
model.result('pg49').feature.remove('tblp1');
model.result('pg50').run;
model.result('pg19').feature.copy('tblp3', 'pg50/tblp1');
model.result('pg50').feature.remove('tblp1');
model.result('pg51').run;
model.result('pg19').feature.copy('tblp4', 'pg51/tblp1');
model.result('pg51').feature.remove('tblp1');
model.result('pg52').run;
model.result('pg19').feature.copy('tblp5', 'pg52/tblp1');
model.result('pg52').feature.remove('tblp1');
model.result('pg53').run;
model.result('pg19').feature.copy('tblp6', 'pg53/tblp1');
model.result('pg53').feature.remove('tblp1');
model.result('pg54').run;
model.result('pg19').feature.copy('tblp7', 'pg54/tblp1');
model.result('pg54').feature.remove('tblp1');
model.result('pg55').run;
model.result('pg19').feature.copy('tblp8', 'pg55/tblp1');
model.result('pg55').feature.remove('tblp1');
model.result('pg56').run;
model.result('pg19').feature.copy('tblp9', 'pg56/tblp1');
model.result('pg56').feature.remove('tblp1');
model.result('pg49').run;
model.result.remove('pg49');
model.result.remove('pg50');
model.result.remove('pg51');
model.result.remove('pg52');
model.result.remove('pg53');
model.result.remove('pg54');
model.result.remove('pg55');
model.result.remove('pg56');
model.result('pg38').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').feature('tblp1').set('preprocx', 'linear');
model.result('pg19').feature('tblp1').set('scalingx', '1/1413');
model.result('pg19').run;
model.result('pg19').feature('tblp2').set('preprocx', 'linear');
model.result('pg19').feature('tblp2').set('scalingx', '1/1413');
model.result('pg19').run;
model.result('pg19').feature('tblp3').set('preprocx', 'linear');
model.result('pg19').feature('tblp3').set('scalingx', '1/1413');
model.result('pg19').run;
model.result('pg19').feature('tblp4').set('preprocx', 'linear');
model.result('pg19').feature('tblp4').set('scalingx', '1/1413');
model.result('pg19').run;
model.result('pg19').feature('tblp5').set('preprocx', 'linear');
model.result('pg19').feature('tblp5').set('scalingx', '1/1413');
model.result('pg19').run;
model.result('pg19').feature('tblp6').set('preprocx', 'linear');
model.result('pg19').feature('tblp6').set('scalingx', '1/1413');
model.result('pg19').run;
model.result('pg19').feature('tblp7').set('preprocx', 'linear');
model.result('pg19').feature('tblp7').set('scalingx', '1/1413');
model.result('pg19').run;
model.result('pg19').feature('tblp8').set('preprocx', 'linear');
model.result('pg19').feature('tblp8').set('scalingx', '1/1413');
model.result('pg19').run;
model.result('pg19').feature('tblp9').set('preprocx', 'linear');
model.result('pg19').feature('tblp9').set('scalingx', '1/1413');
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').feature('tblp1').set('linecolor', 'cyclereset');

model.study('std2').feature('param').setIndex('plistarr', '1 2 4 5 7 9 12 15 20', 0);

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').feature('tblp9').active(false);
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').feature('tblp1').set('linestyle', 'dotted');
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').feature('tblp2').set('linestyle', 'dotted');
model.result('pg19').run;
model.result('pg19').feature('tblp3').set('linestyle', 'dotted');
model.result('pg19').run;
model.result('pg19').feature('tblp4').set('linestyle', 'dotted');
model.result('pg19').run;
model.result('pg19').feature('tblp5').set('linestyle', 'dotted');
model.result('pg19').run;
model.result('pg19').feature('tblp6').set('linestyle', 'dotted');
model.result('pg19').run;
model.result('pg19').feature('tblp7').set('linestyle', 'dotted');
model.result('pg19').run;
model.result('pg19').feature('tblp8').set('linestyle', 'dotted');
model.result('pg19').run;
model.result('pg19').run;
model.result('pg48').run;
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [7], 2);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [6], 2);
model.result('pg18').run;
model.result('pg39').run;
model.result('pg39').setIndex('looplevel', [7], 2);
model.result('pg39').run;
model.result('pg39').setIndex('looplevel', [6], 2);
model.result('pg39').run;
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [7], 2);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [8], 2);
model.result('pg18').run;

model.param.set('epsl_s_0', '1-0.216-epsl_l_0');

model.component('comp1').physics('dode').feature('aleq1').setIndex('f', 'epsl_l-(1-0.216-((cs_ave-cs_0_neg)*omega+1)*epsl_s_0/det_F_M)', 0);

model.param.set('epsl_l_0', '0.54');

model.component('comp1').variable('var4').set('epsl_s', '1-0.216-epsl_l_1');
model.component('comp1').variable('var3').set('epsl_l_2', '(1-0.216-((cs_ave-cs_0_neg)*omega+1)*epsl_s_0/det_F_M)');

model.param.set('L', '10.2[um]');

model.component('comp1').geom('geom2').runPre('fin');
model.component('comp1').geom('geom2').run;

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.sol('sol1').runAll;

model.result('pg20').run;
model.result('pg8').run;
model.result('pg8').run;
model.result('pg8').run;
model.result('pg8').set('data', 'dset1');
model.result('pg8').run;
model.result('pg8').run;
model.result('pg8').run;
model.result('pg8').run;
model.result('pg8').feature('lngr1').selection.set([1]);
model.result('pg8').run;
model.result('pg8').run;
model.result('pg8').run;
model.result('pg8').run;
model.result('pg8').feature('lngr1').set('expr', 'epsl_l_1');
model.result('pg8').run;
model.result('pg8').run;

model.component('comp1').physics('g2').feature('cons1').active(false);
model.component('comp1').physics('g2').feature('cons2').active(true);

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.sol('sol1').runAll;

model.result('pg20').run;
model.result('pg8').run;
model.result('pg8').run;

model.param.set('M', '0.1');

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.sol('sol1').runAll;

model.result('pg20').run;

model.study('std3').feature('time').set('solnum', 101);
model.study('std3').feature('time').set('notsolnum', 101);

model.sol('sol9').study('std3');

model.study('std3').feature('time').set('notlistsolnum', 1);
model.study('std3').feature('time').set('notsolnum', '101');
model.study('std3').feature('time').set('listsolnum', 1);
model.study('std3').feature('time').set('solnum', '101');

model.sol('sol9').feature.remove('t1');
model.sol('sol9').feature.remove('v1');
model.sol('sol9').feature.remove('st1');
model.sol('sol9').create('st1', 'StudyStep');
model.sol('sol9').feature('st1').set('study', 'std3');
model.sol('sol9').feature('st1').set('studystep', 'time');
model.sol('sol9').create('v1', 'Variables');
model.sol('sol9').feature('v1').set('control', 'time');
model.sol('sol9').create('t1', 'Time');
model.sol('sol9').feature('t1').set('tlist', 'range(0,10,100)');
model.sol('sol9').feature('t1').set('plot', 'off');
model.sol('sol9').feature('t1').set('plotgroup', 'pg34');
model.sol('sol9').feature('t1').set('plotfreq', 'tout');
model.sol('sol9').feature('t1').set('probesel', 'all');
model.sol('sol9').feature('t1').set('probes', {'pdom1' 'dom1'});
model.sol('sol9').feature('t1').set('probefreq', 'tsteps');
model.sol('sol9').feature('t1').set('atolglobalvaluemethod', 'factor');
model.sol('sol9').feature('t1').set('endtimeinterpolation', true);
model.sol('sol9').feature('t1').set('control', 'time');
model.sol('sol9').feature('t1').create('seDef', 'Segregated');
model.sol('sol9').feature('t1').create('fc1', 'FullyCoupled');
model.sol('sol9').feature('t1').feature('fc1').set('linsolver', 'dDef');
model.sol('sol9').feature('t1').feature.remove('fcDef');
model.sol('sol9').feature('t1').feature.remove('seDef');
model.sol('sol4').feature('v1').set('notsolnum', 'last');
model.sol('sol4').feature('v1').set('notsolvertype', 'solnum');
model.sol('sol4').feature('v1').set('notlistsolnum', {'1'});
model.sol('sol4').feature('v1').set('notsolnum', 'last');
model.sol('sol4').feature('v1').set('notlistsolnum', {'1'});
model.sol('sol4').feature('v1').set('notsolnum', 'last');
model.sol('sol4').feature('v1').set('control', 'time');
model.sol('sol4').feature('v1').set('solnum', 'last');
model.sol('sol4').feature('v1').set('solvertype', 'solnum');
model.sol('sol4').feature('v1').set('listsolnum', {'1'});
model.sol('sol4').feature('v1').set('solnum', 'last');
model.sol('sol4').feature('v1').set('listsolnum', {'1'});
model.sol('sol4').feature('v1').set('solnum', 'last');
model.sol('sol4').feature('v1').set('control', 'time');

model.study('std2').feature('time').set('notsolnum', 'last');
model.study('std2').feature('time').set('notsolvertype', 'solnum');
model.study('std2').feature('time').set('notlistsolnum', {'1'});
model.study('std2').feature('time').set('notsolnum', 'last');
model.study('std2').feature('time').set('notlistsolnum', {'1'});
model.study('std2').feature('time').set('notsolnum', 'last');
model.study('std2').feature('time').set('notsolnumhide', 'off');
model.study('std2').feature('time').set('notstudyhide', 'off');
model.study('std2').feature('time').set('notsolhide', 'on');
model.study('std2').feature('time').set('solnum', 'last');
model.study('std2').feature('time').set('solvertype', 'solnum');
model.study('std2').feature('time').set('listsolnum', {'1'});
model.study('std2').feature('time').set('solnum', 'last');
model.study('std2').feature('time').set('listsolnum', {'1'});
model.study('std2').feature('time').set('solnum', 'last');
model.study('std2').feature('time').set('solnumhide', 'off');
model.study('std2').feature('time').set('initstudyhide', 'off');
model.study('std2').feature('time').set('initsolhide', 'on');

model.sol('sol9').attach('std3');

model.batch('p3').feature.remove('so1');
model.batch('p3').create('so1', 'Solutionseq');
model.batch('p3').feature('so1').set('seq', 'sol9');
model.batch('p3').feature('so1').set('store', 'on');
model.batch('p3').feature('so1').set('clear', 'on');
model.batch('p3').feature('so1').set('psol', 'sol10');
model.batch('p3').set('pname', {'C'});
model.batch('p3').set('plistarr', {'0'});
model.batch('p3').set('sweeptype', 'sparse');
model.batch('p3').set('probesel', 'all');
model.batch('p3').set('probes', {'pdom1' 'dom1'});
model.batch('p3').set('plot', 'off');
model.batch('p3').set('err', 'on');
model.batch('p3').attach('std3');
model.batch('p3').set('control', 'param');

model.result.create('pg49', 'PlotGroup2D');
model.result('pg49').set('data', 'dset16');
model.result('pg49').create('surf1', 'Surface');
model.result('pg49').feature('surf1').set('expr', 'u');
model.result.create('pg50', 'PlotGroup2D');
model.result('pg50').set('data', 'dset16');
model.result('pg50').create('surf1', 'Surface');
model.result('pg50').feature('surf1').set('expr', 'cs');
model.result.create('pg51', 'PlotGroup1D');
model.result('pg51').set('data', 'dset15');
model.result('pg51').create('lngr1', 'LineGraph');
model.result('pg51').feature('lngr1').set('xdata', 'expr');
model.result('pg51').feature('lngr1').set('xdataexpr', 'x');
model.result('pg51').feature('lngr1').selection.all;
model.result('pg51').feature('lngr1').set('expr', 'cl');
model.result.create('pg52', 'PlotGroup1D');
model.result('pg52').set('data', 'dset15');
model.result('pg52').create('lngr1', 'LineGraph');
model.result('pg52').feature('lngr1').set('xdata', 'expr');
model.result('pg52').feature('lngr1').set('xdataexpr', 'x');
model.result('pg52').feature('lngr1').selection.all;
model.result('pg52').feature('lngr1').set('expr', 'uM');
model.result.create('pg53', 'PlotGroup1D');
model.result('pg53').set('data', 'dset15');
model.result('pg53').create('lngr1', 'LineGraph');
model.result('pg53').feature('lngr1').set('xdata', 'expr');
model.result('pg53').feature('lngr1').set('xdataexpr', 'x');
model.result('pg53').feature('lngr1').selection.all;
model.result('pg53').feature('lngr1').set('expr', 'epsl_l');

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.result.remove('pg52');
model.result.remove('pg53');
model.result.remove('pg50');
model.result.remove('pg51');
model.result.remove('pg49');
model.result('pg8').run;
model.result('pg8').set('data', 'dset11');

model.component('comp1').probe('pdom1').genResul