del.result('pg27').run;
model.result('pg28').run;
model.result('pg28').set('data', 'dset17');
model.result('pg28').run;
model.result('pg27').run;
model.result('pg27').set('data', 'dset17');
model.result('pg27').run;
model.result('pg37').run;
model.result('pg37').set('data', 'dset17');
model.result('pg37').run;
model.result('pg37').run;
model.result('pg37').run;
model.result('pg37').run;
model.result('pg37').run;
model.result('pg37').feature('lngr1').selection.set([1]);
model.result('pg37').run;
model.result('pg37').run;

model.component('comp1').mesh('mesh2').run;
model.component('comp1').mesh('mesh2').run;

model.sol('sol60').feature('t1').feature('fc1').set('ntolfact', 0.01);

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.sol('sol60').runAll;

model.result('pg20').run;
model.result('pg19').run;
model.result('pg19').set('data', 'dset17');
model.result('pg19').run;

model.component('comp1').mesh('mesh2').feature('size').set('hmax', '50/100');
model.component('comp2').mesh('mesh3').feature('map1').feature('dis2').set('numelem', 50);
model.component('comp2').mesh('mesh3').run;
model.component('comp2').mesh('mesh3').run;
model.component('comp2').mesh('mesh3').run;
model.component('comp1').mesh('mesh2').feature('size').set('hmax', '50/50');
model.component('comp1').mesh('mesh2').run;
model.component('comp1').mesh('mesh2').run;
model.component('comp1').mesh('mesh2').run;
model.component('comp2').mesh('mesh3').feature('map1').feature('dis1').set('numelem', 20);
model.component('comp2').mesh('mesh3').run;

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.sol('sol1').feature('t1').feature('fc1').set('ntolfact', 0.05);

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.sol('sol1').feature('t1').feature('fc1').set('ntolfact', 0.01);

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.component('comp2').mesh('mesh3').feature('map1').feature('dis1').set('numelem', 15);
model.component('comp2').mesh('mesh3').run;

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.param.set('C', '0.05');
model.param.set('Flag', '1');

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.sol('sol1').feature('t1').feature('fc1').set('ntolfact', 0.1);

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.sol('sol1').runAll;

model.result('pg34').run;

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.batch('p3').run('compute');

model.result('pg54').run;

model.param.set('C', '2');
model.param.set('Flag', '-1');

model.sol('sol60').feature('t1').feature('fc1').set('ntolfact', 0.01);

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.sol('sol60').feature('t1').set('consistent', 'bweuler');
model.sol('sol60').feature('t1').feature('fc1').set('dtech', 'hnlin');
model.sol('sol60').feature('t1').feature('fc1').set('ntolfact', 0.005);
model.sol('sol60').feature('t1').feature('fc1').set('maxiter', 250);

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.sol('sol60').runAll;

model.result('pg20').run;

model.sol('sol60').feature('t1').feature('fc1').set('ntolfact', 0.001);

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.sol('sol60').runAll;

model.result('pg20').run;

model.sol('sol4').feature('t1').feature('fc1').set('maxiter', 250);
model.sol('sol4').feature('t1').feature('fc1').set('ntolfact', 0.001);
model.sol('sol4').feature('t1').set('tstepsbdf', 'strict');
model.sol('sol4').feature('t1').feature('fc1').set('dtech', 'hnlin');

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.batch('p2').run('compute');

model.result('pg23').run;
model.result('pg19').run;
model.result('pg19').set('data', 'dset15');
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').set('data', 'dset11');
model.result('pg19').run;
model.result('pg2').run;
model.result('pg39').run;
model.result('pg35').run;
model.result('pg37').run;
model.result('pg37').set('data', 'dset11');
model.result('pg37').run;
model.result('pg37').setIndex('looplevelinput', 'manual', 2);
model.result('pg37').setIndex('looplevel', [3], 2);
model.result('pg37').setIndex('looplevel', [7], 2);
model.result('pg37').run;
model.result('pg37').setIndex('looplevel', [6], 2);
model.result('pg37').run;
model.result('pg37').run;
model.result('pg39').run;
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [3], 2);
model.result('pg18').setIndex('looplevel', [6], 2);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [7], 2);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [6], 2);
model.result('pg18').run;
model.result.dataset('dset17').set('solution', 'none');
model.result.dataset('dset18').set('solution', 'none');

model.study.remove('std4');

model.component('comp1').variable('var4').set('kl_eff', 'max(k_kl*kl_an1(cl)*cl[mol/m^3]/tau,1e-6[S/m])');

model.func('an3').setIndex('plotargs', 10000, 0, 2);

model.result('pg54').run;
model.result('pg55').run;
model.result('pg56').run;
model.result('pg57').run;
model.result('pg58').run;
model.result('pg59').set('window', 'window3');
model.result('pg59').set('windowtitle', [native2unicode(hex2dec({'63' 'a2'}), 'unicode')  native2unicode(hex2dec({'94' '88'}), 'unicode')  native2unicode(hex2dec({'56' 'fe'}), 'unicode')  native2unicode(hex2dec({'20' '1c'}), 'unicode') '3' native2unicode(hex2dec({'20' '1d'}), 'unicode') ]);
model.result('pg59').run;
model.result('pg52').run;
model.result('pg54').run;
model.result.remove('pg54');
model.result.remove('pg55');
model.result.remove('pg56');
model.result.remove('pg57');
model.result.remove('pg58');
model.result.remove('pg59');
model.result('pg52').run;
model.result('pg41').set('window', 'window1');
model.result('pg41').run;
model.result.remove('pg41');
model.result('pg52').run;
model.result('pg52').run;
model.result('pg52').set('data', 'dset11');
model.result('pg52').run;
model.result('pg52').run;
model.result('pg52').run;
model.result('pg52').run;
model.result('pg52').run;
model.result('pg52').feature.remove('ptgr1');
model.result('pg52').run;
model.result('pg52').create('lngr1', 'LineGraph');
model.result('pg52').feature('lngr1').set('expr', 'kl_eff');
model.result('pg52').run;
model.result('pg52').feature('lngr1').selection.set([1]);
model.result('pg52').run;
model.result('pg52').run;
model.result('pg52').setIndex('looplevelinput', 'manualindices', 2);
model.result('pg52').setIndex('looplevelinput', 'manual', 2);
model.result('pg52').setIndex('looplevel', [3], 2);
model.result('pg52').setIndex('looplevel', [6], 2);
model.result('pg52').run;
model.result('pg52').setIndex('looplevel', [7], 2);
model.result('pg52').run;

model.param.set('Flag', '1');
model.param.set('C', '0.05');
model.param.set('k_Ds', '1');

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.batch('p2').run('compute');

model.result('pg23').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').feature('tblp8').active(true);
model.result('pg19').run;
model.result('pg19').feature('tblp8').active(false);
model.result('pg19').run;
model.result('pg19').run;
model.result('pg52').run;
model.result('pg52').setIndex('looplevel', [6], 2);
model.result('pg52').run;
model.result('pg52').setIndex('looplevel', [7], 2);
model.result('pg52').run;
model.result('pg8').run;
model.result('pg1').run;
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [7], 2);
model.result('pg18').run;
model.result('pg19').run;
model.result('pg1').run;
model.result('pg20').run;
model.result('pg20').run;
model.result('pg20').run;
model.result('pg20').set('data', 'dset11');
model.result('pg20').run;

model.param.set('k_i0', '2');

model.result('pg20').run;
model.result('pg2').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg20').run;
model.result('pg20').feature.copy('tblp1', 'pg19/tblp1');
model.result('pg20').run;
model.result('pg20').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').feature('tblp1').set('scalingx', '1/0.85');
model.result('pg19').run;
model.result('pg19').feature('tblp1').set('scalingx', '1/0.83');
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').feature('tblp3').set('scalingx', '1/0.83');
model.result('pg19').run;
model.result('pg19').feature('tblp4').set('scalingx', '1/0.83');
model.result('pg19').run;
model.result('pg19').feature('tblp5').set('scalingx', '1/0.83');
model.result('pg19').run;
model.result('pg19').feature('tblp2').set('scalingx', '1/0.83');
model.result('pg19').run;
model.result('pg19').feature('tblp6').set('scalingx', '1/0.83');
model.result('pg19').run;
model.result('pg19').feature('tblp7').set('scalingx', '1/0.83');
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').run;

model.param.set('k_Ds', '5');

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.batch('p2').run('compute');

model.result('pg20').run;
model.result('pg19').run;

model.label('Electrode_model_with_experiment_deLi_constant_thickness.mph');

model.result('pg19').run;
model.result('pg6').run;
model.result('pg1').run;
model.result('pg20').run;

model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int1').active(false);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func.create('int2', 'Interpolation');
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').set('funcname', 'Eeq_int');
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int1').set('funcname', 'Eeq_int2');
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').set('funcname', 'Eeq_int1');
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int1').set('funcname', 'Eeq_int0');
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.012132, 0, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 1.20519, 0, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.026863, 1, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 1.14078, 1, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.05286, 2, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 1.03688, 2, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.073657, 3, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.93091, 3, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.10052, 4, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.83325, 4, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.123917, 5, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.7439, 5, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.149047, 6, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.67117, 6, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.17331, 7, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.62338, 7, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.197574, 8, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.58182, 8, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.221837, 9, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.55481, 9, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.246101, 10, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.52987, 10, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.270364, 11, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.50909, 11, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.29636, 12, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.48416, 12, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.318891, 13, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.47169, 13, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.343154, 14, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.45922, 14, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.368284, 15, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.4426, 15, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.392548, 16, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.43429, 16, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.416811, 17, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.42182, 17, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.441075, 18, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.40935, 18, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.465338, 19, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.39688, 19, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.489601, 20, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.38234, 20, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.513865, 21, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.37403, 21, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.538128, 22, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.35532, 22, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.562392, 23, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.34286, 23, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.586655, 24, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.33247, 24, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.611785, 25, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.31792, 25, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.635182, 26, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.30961, 26, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.660312, 27, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.29714, 27, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.682842, 28, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.28468, 28, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.707972, 29, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.27844, 29, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.732236, 30, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.2639, 30, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.757366, 31, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.25558, 31, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.781629, 32, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.24519, 32, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.805893, 33, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.23481, 33, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.829289, 34, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.22649, 34, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.854419, 35, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.21403, 35, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.878683, 36, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.20156, 36, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.903813, 37, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.18494, 37, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.92721, 38, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.16831, 38, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.954073, 39, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.13922, 39, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.976603, 40, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.09766, 40, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 1.0026, 41, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.03948, 41, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.012132, 0, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 1.20519, 0, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.026863, 1, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 1.14078, 1, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.05286, 2, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 1.03688, 2, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.073657, 3, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.93091, 3, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.10052, 4, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.83325, 4, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.123917, 5, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.7439, 5, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.149047, 6, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.67117, 6, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.17331, 7, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.62338, 7, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.197574, 8, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.58182, 8, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.221837, 9, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.55481, 9, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.246101, 10, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.52987, 10, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.270364, 11, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.50909, 11, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.29636, 12, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.48416, 12, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.318891, 13, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.47169, 13, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.343154, 14, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.45922, 14, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.368284, 15, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.4426, 15, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.392548, 16, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.43429, 16, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.416811, 17, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.42182, 17, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.441075, 18, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.40935, 18, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.465338, 19, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.39688, 19, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.489601, 20, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.38234, 20, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.513865, 21, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.37403, 21, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.538128, 22, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.35532, 22, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.562392, 23, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.34286, 23, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.586655, 24, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.33247, 24, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.611785, 25, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.31792, 25, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.635182, 26, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.30961, 26, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.660312, 27, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.29714, 27, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.682842, 28, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.28468, 28, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.707972, 29, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.27844, 29, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.732236, 30, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.2639, 30, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.757366, 31, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.25558, 31, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.781629, 32, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.24519, 32, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.805893, 33, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.23481, 33, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.829289, 34, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.22649, 34, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.854419, 35, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.21403, 35, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.878683, 36, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.20156, 36, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.903813, 37, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.18494, 37, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.92721, 38, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.16831, 38, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.954073, 39, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.13922, 39, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.976603, 40, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.09766, 40, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 1.0026, 41, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.03948, 41, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').set('extrap', 'interior');

model.study('std2').feature('param').setIndex('plistarr', '1 2 5 10 14 20 25 30', 0);

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.batch('p2').run('compute');

model.result('pg20').run;
model.result('pg19').run;

model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').set('table', {});
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 1, 0, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0158, 0, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.998563218, 1, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0223, 1, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.998563218, 2, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0239, 2, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.997126437, 3, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0257, 3, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.997126437, 4, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0282, 4, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.995689655, 5, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0301, 5, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.995689655, 6, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0316, 6, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.994252874, 7, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0329, 7, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.994252874, 8, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.035, 8, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.992816092, 9, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0369, 9, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.992816092, 10, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0384, 10, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.99137931, 11, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0397, 11, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.99137931, 12, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0415, 12, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.989942529, 13, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0428, 13, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.989942529, 14, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0437, 14, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.988505747, 15, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0453, 15, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.988505747, 16, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0465, 16, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.987068966, 17, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0487, 17, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.987068966, 18, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0496, 18, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.985632184, 19, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0508, 19, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.985632184, 20, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0521, 20, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.984195402, 21, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0543, 21, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.984195402, 22, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0558, 22, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.982758621, 23, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0567, 23, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.982758621, 24, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.058, 24, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.981321839, 25, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0586, 25, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.981321839, 26, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0611, 26, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.979885057, 27, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0623, 27, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.978448276, 28, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0639, 28, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.978448276, 29, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0648, 29, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.977011494, 30, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.066, 30, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.977011494, 31, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0676, 31, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.975574713, 32, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0688, 32, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.975574713, 33, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0694, 33, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.974137931, 34, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0704, 34, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.974137931, 35, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0704, 35, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.972701149, 36, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0716, 36, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.972701149, 37, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0722, 37, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.971264368, 38, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0735, 38, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.971264368, 39, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0747, 39, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.969827586, 40, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.076, 40, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.969827586, 41, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0772, 41, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.968390805, 42, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0781, 42, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.968390805, 43, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0787, 43, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.966954023, 44, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0791, 44, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.966954023, 45, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.08, 45, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.965517241, 46, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0806, 46, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.965517241, 47, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0812, 47, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.96408046, 48, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0822, 48, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.96408046, 49, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0834, 49, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.962643678, 50, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0834, 50, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.961206897, 51, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0843, 51, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.961206897, 52, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0849, 52, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.959770115, 53, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0853, 53, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.959770115, 54, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0859, 54, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.958333333, 55, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0862, 55, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.958333333, 56, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0865, 56, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.956896552, 57, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0871, 57, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.956896552, 58, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.088, 58, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.95545977, 59, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0887, 59, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.95545977, 60, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0887, 60, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.954022989, 61, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.089, 61, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.954022989, 62, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0896, 62, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.952586207, 63, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0899, 63, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.952586207, 64, 0);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').setIndex('table', 0.0899, 64, 1);
model.component('comp1').material('mat1').propertyGroup('ElectrodePotential').func('int2').set