;
model.result('pg58').set('looplevel', [61 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [71 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [81 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [91 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [94 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [91 1 4]);
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').feature('surf1').set('expr', 'T_tt');
model.result('pg58').run;
model.result('pg58').set('looplevel', [11 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [21 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [31 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [41 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [51 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [61 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [71 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [81 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [91 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [94 1 4]);
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [41 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [43 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [45 1 4]);
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').feature('surf1').set('expr', 'T_RR');
model.result('pg58').run;
model.result('pg38').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [41 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [43 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [47 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [55 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [41 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [43 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [45 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [47 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [49 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [51 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [53 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [55 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [57 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [59 1 4]);
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').feature('surf1').set('expr', 'T_tt');
model.result('pg58').run;
model.result('pg58').set('data', 'dset20');
model.result('pg58').set('looplevel', [6 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [11 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [16 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [21 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [26 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [31 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [36 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [41 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [46 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [51 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [56 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [61 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [66 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [61 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [66 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [69 1]);
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').feature('surf1').set('expr', 'T_RR');
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [6 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [11 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [16 1]);
model.result('pg58').run;
model.result.table('evl2').addRow([2.8165828553028405E-5 2.657895720403758E-6 -0.04625376939603454], [0 0 0]);
model.result('pg58').set('looplevel', [21 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [26 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [32 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [36 1]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [41 1]);
model.result('pg58').run;

model.label('Electrode_model_with_experiment_deLi_constant_thickness_1.mph');

model.result('pg58').run;
model.result('pg29').run;
model.result('pg29').set('data', 'dset11');
model.result('pg29').setIndex('looplevelinput', 'manual', 2);
model.result('pg29').setIndex('looplevel', [3], 2);
model.result('pg29').setIndex('looplevel', [4], 2);
model.result('pg29').run;
model.result('pg29').run;
model.result('pg29').feature('lngr1').set('expr', 'det_F_M');
model.result('pg29').run;
model.result.export.create('plot2', 'pg29', 'lngr1', 'Plot');
model.result.export('plot1').set('plotgroup', 'pg29');
model.result.export('plot1').set('filename', 'F:\group\Research\Mechanic-electrochemic coupling method\Network model for electrode\Rate performance test 2 G5\det_F_M_10C.txt');
model.result('pg29').run;
model.result.export('plot1').run;

model.label('Electrode_model_with_experiment_deLi_constant_thickness_1.mph');
model.label('Electrode_model_with_experiment_deLi_constant_thickness_clean.mph');

model.func.remove('an4');
model.func.remove('an3');
model.func.remove('an7');
model.func.remove('an8');
model.func('an2').set('funcname', 'kl_an1');
model.func('an5').set('funcname', 'Dl_an1');

model.result.dataset('dset5').set('solution', 'none');
model.result.dataset('dset6').set('solution', 'none');
model.result.dataset('dset17').set('solution', 'none');
model.result.dataset('dset18').set('solution', 'none');
model.result.dataset('dset19').set('solution', 'none');
model.result.dataset('dset20').set('solution', 'none');

model.study.remove('std4');

model.sol('sol1').clearSolutionData;
model.sol('sol4').clearSolutionData;
model.sol('sol5').clearSolutionData;
model.sol('sol9').clearSolutionData;
model.sol('sol10').clearSolutionData;
model.sol('sol149').clearSolutionData;
model.sol('sol150').clearSolutionData;
model.sol('sol151').clearSolutionData;
model.sol('sol152').clearSolutionData;
model.sol('sol153').clearSolutionData;
model.sol('sol154').clearSolutionData;

model.label('Electrode_model_with_experiment_deLi_constant_thickness_clean.mph');

model.component('comp1').physics('g').feature('dir1').setIndex('useDirichletCondition', 1, 2);
model.component('comp1').physics('g').feature('dir1').setIndex('useDirichletCondition', 0, 2);

out = model;
