dset11');
model.result('pg53').run;
model.result('pg53').setIndex('looplevelinput', 'manual', 2);
model.result('pg53').setIndex('looplevel', [3], 2);
model.result('pg53').run;
model.result('pg53').setIndex('looplevel', [4], 2);
model.result('pg53').run;
model.result('pg53').set('data', 'dset19');
model.result('pg53').run;
model.result('pg53').run;
model.result('pg53').run;
model.result('pg53').run;
model.result('pg53').run;
model.result('pg53').set('data', 'dset17');
model.result('pg53').run;
model.result('pg53').run;
model.result('pg53').run;
model.result('pg53').run;
model.result('pg53').run;
model.result('pg53').feature('lngr1').selection.set([1]);
model.result('pg53').run;
model.result('pg53').setIndex('looplevelinput', 'manual', 0);
model.result('pg53').setIndex('looplevel', [1], 0);
model.result('pg53').setIndex('looplevel', [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179], 0);
model.result('pg53').run;

model.component('comp1').variable('var4').set('kl_eff', 'max(k_kl*kl_an1(cl)*cl[mol/m^3]/tau,1e-6[S/m])');

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.result('pg19').run;
model.result('pg39').run;
model.result('pg39').set('data', 'dset9');
model.result('pg39').run;
model.result('pg39').setIndex('looplevelinput', 'manual', 0);
model.result('pg39').setIndex('looplevel', [1], 0);
model.result('pg39').setIndex('looplevel', [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73], 0);
model.result('pg39').run;
model.result('pg52').run;
model.result('pg52').setIndex('looplevel', [74], 0);
model.result('pg52').run;
model.result('pg52').feature.remove('lngr1');
model.result('pg52').run;
model.result('pg52').create('ptgr1', 'PointGraph');
model.result('pg52').feature('ptgr1').selection.set([1]);
model.result('pg52').feature('ptgr1').set('expr', 'kl_eff');
model.result('pg52').run;
model.result('pg52').run;
model.result('pg52').setIndex('looplevelinput', 'all', 0);
model.result('pg52').run;
model.result('pg52').run;
model.result('pg52').run;
model.result('pg52').set('axisactive', false);
model.result('pg52').set('showgrid', true);
model.result('pg52').set('ylog', true);
model.result('pg52').set('showmanualgrid', true);
model.result('pg52').set('showxspacing', true);
model.result('pg52').set('showyspacing', false);
model.result('pg52').set('showsecyspacing', false);
model.result('pg52').set('showsecyextra', false);
model.result('pg52').set('data', 'dset11');
model.result('pg52').setIndex('looplevelinput', 'manual', 2);
model.result('pg52').setIndex('looplevel', [4], 2);
model.result('pg52').run;
model.result('pg52').setIndex('looplevel', [3], 2);
model.result('pg52').run;
model.result('pg52').setIndex('looplevel', [4], 2);
model.result('pg52').run;
model.result('pg39').run;
model.result('pg19').run;
model.result('pg10').run;
model.result('pg18').run;
model.result('pg30').run;
model.result('pg24').run;
model.result('pg40').run;
model.result('pg25').run;
model.result('pg27').run;
model.result('pg42').run;
model.result('pg43').run;
model.result('pg2').run;
model.result('pg19').run;

model.component('comp1').variable('var4').set('kl_eff', 'max(k_kl*kl_an1(cl)*cl[mol/m^3]/tau,1e-5[S/m])');

model.result.create('pg54', 'PlotGroup1D');
model.result('pg54').set('data', 'dset19');
model.result('pg54').create('lngr1', 'LineGraph');
model.result('pg54').feature('lngr1').set('xdata', 'expr');
model.result('pg54').feature('lngr1').set('xdataexpr', 'x');
model.result('pg54').feature('lngr1').selection.all;
model.result('pg54').feature('lngr1').set('expr', 'cl');
model.result.create('pg55', 'PlotGroup2D');
model.result('pg55').set('data', 'dset20');
model.result('pg55').create('surf1', 'Surface');
model.result('pg55').feature('surf1').set('expr', 'u');
model.result.create('pg56', 'PlotGroup2D');
model.result('pg56').set('data', 'dset20');
model.result('pg56').create('surf1', 'Surface');
model.result('pg56').feature('surf1').set('expr', 'cs');
model.result.create('pg57', 'PlotGroup1D');
model.result('pg57').set('data', 'dset19');
model.result('pg57').create('lngr1', 'LineGraph');
model.result('pg57').feature('lngr1').set('xdata', 'expr');
model.result('pg57').feature('lngr1').set('xdataexpr', 'x');
model.result('pg57').feature('lngr1').selection.all;
model.result('pg57').feature('lngr1').set('expr', 'uM');
model.result.create('pg58', 'PlotGroup1D');
model.result('pg58').set('data', 'dset19');
model.result('pg58').create('lngr1', 'LineGraph');
model.result('pg58').feature('lngr1').set('xdata', 'expr');
model.result('pg58').feature('lngr1').set('xdataexpr', 'x');
model.result('pg58').feature('lngr1').selection.all;
model.result('pg58').feature('lngr1').set('expr', 'epsl_l');

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.result.remove('pg54');
model.result.remove('pg55');
model.result.remove('pg56');
model.result.remove('pg57');
model.result.remove('pg58');
model.result('pg18').run;
model.result('pg18').set('data', 'dset9');
model.result('pg18').run;
model.result('pg18').set('data', 'dset11');
model.result('pg18').setIndex('looplevelinput', 'manual', 2);
model.result('pg18').setIndex('looplevel', [3], 2);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [4], 2);
model.result('pg18').run;
model.result('pg10').run;
model.result('pg18').run;

model.component('comp1').physics('g2').feature('cons1').setIndex('R', 'T_xx_M+1E6[Pa]', 0);

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.sol('sol1').runAll;

model.result('pg34').run;
model.result('pg27').run;
model.result('pg27').set('data', 'dset1');
model.result('pg27').run;

model.study('std3').feature('time').set('tlist', 'range(0,10,600)');

model.sol('sol9').study('std3');

model.study('std3').feature('time').set('notlistsolnum', 1);
model.study('std3').feature('time').set('notsolnum', 'last');
model.study('std3').feature('time').set('listsolnum', 1);
model.study('std3').feature('time').set('solnum', 'last');

model.sol('sol9').feature.remove('t1');
model.sol('sol9').feature.remove('v1');
model.sol('sol9').feature.remove('st1');
model.sol('sol9').create('st1', 'StudyStep');
model.sol('sol9').feature('st1').set('study', 'std3');
model.sol('sol9').feature('st1').set('studystep', 'time');
model.sol('sol9').create('v1', 'Variables');
model.sol('sol9').feature('v1').set('control', 'time');
model.sol('sol9').create('t1', 'Time');
model.sol('sol9').feature('t1').set('tlist', 'range(0,10,600)');
model.sol('sol9').feature('t1').set('plot', 'off');
model.sol('sol9').feature('t1').set('plotgroup', 'pg34');
model.sol('sol9').feature('t1').set('plotfreq', 'tout');
model.sol('sol9').feature('t1').set('probesel', 'all');
model.sol('sol9').feature('t1').set('probes', {'pdom1' 'dom1'});
model.sol('sol9').feature('t1').set('probefreq', 'tsteps');
model.sol('sol9').feature('t1').set('atolglobalvaluemethod', 'factor');
model.sol('sol9').feature('t1').set('endtimeinterpolation', true);
model.sol('sol9').feature('t1').set('control', 'time');
model.sol('sol9').feature('t1').create('seDef', 'Segregated');
model.sol('sol9').feature('t1').create('fc1', 'FullyCoupled');
model.sol('sol9').feature('t1').feature('fc1').set('linsolver', 'dDef');
model.sol('sol9').feature('t1').feature.remove('fcDef');
model.sol('sol9').feature('t1').feature.remove('seDef');
model.sol('sol16').feature('v1').set('notsolnum', 'auto');
model.sol('sol16').feature('v1').set('notsolvertype', 'solnum');
model.sol('sol16').feature('v1').set('notlistsolnum', {'1'});
model.sol('sol16').feature('v1').set('notsolnum', 6);
model.sol('sol16').feature('v1').set('notlistsolnum', {'1'});
model.sol('sol16').feature('v1').set('notsolnum', '6');
model.sol('sol16').feature('v1').set('control', 'time');
model.sol('sol16').feature('v1').set('solnum', 'auto');
model.sol('sol16').feature('v1').set('solvertype', 'solnum');
model.sol('sol16').feature('v1').set('listsolnum', {'1'});
model.sol('sol16').feature('v1').set('solnum', 6);
model.sol('sol16').feature('v1').set('listsolnum', {'1'});
model.sol('sol16').feature('v1').set('solnum', '6');
model.sol('sol16').feature('v1').set('control', 'time');
model.sol('sol4').feature('v1').set('notsolnum', 'auto');
model.sol('sol4').feature('v1').set('notsolvertype', 'solnum');
model.sol('sol4').feature('v1').set('notlistsolnum', {'1'});
model.sol('sol4').feature('v1').set('notsolnum', 6);
model.sol('sol4').feature('v1').set('notlistsolnum', {'1'});
model.sol('sol4').feature('v1').set('notsolnum', '6');
model.sol('sol4').feature('v1').set('control', 'time');
model.sol('sol4').feature('v1').set('solnum', 'auto');
model.sol('sol4').feature('v1').set('solvertype', 'solnum');
model.sol('sol4').feature('v1').set('listsolnum', {'1'});
model.sol('sol4').feature('v1').set('solnum', 6);
model.sol('sol4').feature('v1').set('listsolnum', {'1'});
model.sol('sol4').feature('v1').set('solnum', '6');
model.sol('sol4').feature('v1').set('control', 'time');

model.study('std4').feature('time').set('notsolnum', 'auto');
model.study('std4').feature('time').set('notsolvertype', 'solnum');
model.study('std4').feature('time').set('notlistsolnum', {'1'});
model.study('std4').feature('time').set('notsolnum', 6);
model.study('std4').feature('time').set('notlistsolnum', {'1'});
model.study('std4').feature('time').set('notsolnum', '6');
model.study('std4').feature('time').set('notsolnumhide', 'off');
model.study('std4').feature('time').set('notstudyhide', 'off');
model.study('std4').feature('time').set('notsolhide', 'on');
model.study('std4').feature('time').set('solnum', 'auto');
model.study('std4').feature('time').set('solvertype', 'solnum');
model.study('std4').feature('time').set('listsolnum', {'1'});
model.study('std4').feature('time').set('solnum', 6);
model.study('std4').feature('time').set('listsolnum', {'1'});
model.study('std4').feature('time').set('solnum', '6');
model.study('std4').feature('time').set('solnumhide', 'off');
model.study('std4').feature('time').set('initstudyhide', 'off');
model.study('std4').feature('time').set('initsolhide', 'on');
model.study('std2').feature('time').set('notsolnum', 'auto');
model.study('std2').feature('time').set('notsolvertype', 'solnum');
model.study('std2').feature('time').set('notlistsolnum', {'1'});
model.study('std2').feature('time').set('notsolnum', 6);
model.study('std2').feature('time').set('notlistsolnum', {'1'});
model.study('std2').feature('time').set('notsolnum', '6');
model.study('std2').feature('time').set('notsolnumhide', 'off');
model.study('std2').feature('time').set('notstudyhide', 'off');
model.study('std2').feature('time').set('notsolhide', 'on');
model.study('std2').feature('time').set('solnum', 'auto');
model.study('std2').feature('time').set('solvertype', 'solnum');
model.study('std2').feature('time').set('listsolnum', {'1'});
model.study('std2').feature('time').set('solnum', 6);
model.study('std2').feature('time').set('listsolnum', {'1'});
model.study('std2').feature('time').set('solnum', '6');
model.study('std2').feature('time').set('solnumhide', 'off');
model.study('std2').feature('time').set('initstudyhide', 'off');
model.study('std2').feature('time').set('initsolhide', 'on');

model.sol('sol9').attach('std3');

model.batch('p3').feature.remove('so1');
model.batch('p3').create('so1', 'Solutionseq');
model.batch('p3').feature('so1').set('seq', 'sol9');
model.batch('p3').feature('so1').set('store', 'on');
model.batch('p3').feature('so1').set('clear', 'on');
model.batch('p3').feature('so1').set('psol', 'sol10');
model.batch('p3').set('pname', {'C'});
model.batch('p3').set('plistarr', {'0'});
model.batch('p3').set('sweeptype', 'sparse');
model.batch('p3').set('probesel', 'all');
model.batch('p3').set('probes', {'pdom1' 'dom1'});
model.batch('p3').set('plot', 'off');
model.batch('p3').set('err', 'on');
model.batch('p3').attach('std3');
model.batch('p3').set('control', 'param');

model.result.create('pg54', 'PlotGroup1D');
model.result('pg54').set('data', 'dset15');
model.result('pg54').create('lngr1', 'LineGraph');
model.result('pg54').feature('lngr1').set('xdata', 'expr');
model.result('pg54').feature('lngr1').set('xdataexpr', 'x');
model.result('pg54').feature('lngr1').selection.all;
model.result('pg54').feature('lngr1').set('expr', 'cl');
model.result.create('pg55', 'PlotGroup2D');
model.result('pg55').set('data', 'dset16');
model.result('pg55').create('surf1', 'Surface');
model.result('pg55').feature('surf1').set('expr', 'u');
model.result.create('pg56', 'PlotGroup2D');
model.result('pg56').set('data', 'dset16');
model.result('pg56').create('surf1', 'Surface');
model.result('pg56').feature('surf1').set('expr', 'cs');
model.result.create('pg57', 'PlotGroup1D');
model.result('pg57').set('data', 'dset15');
model.result('pg57').create('lngr1', 'LineGraph');
model.result('pg57').feature('lngr1').set('xdata', 'expr');
model.result('pg57').feature('lngr1').set('xdataexpr', 'x');
model.result('pg57').feature('lngr1').selection.all;
model.result('pg57').feature('lngr1').set('expr', 'uM');
model.result.create('pg58', 'PlotGroup1D');
model.result('pg58').set('data', 'dset15');
model.result('pg58').create('lngr1', 'LineGraph');
model.result('pg58').feature('lngr1').set('xdata', 'expr');
model.result('pg58').feature('lngr1').set('xdataexpr', 'x');
model.result('pg58').feature('lngr1').selection.all;
model.result('pg58').feature('lngr1').set('expr', 'epsl_l');

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.result.remove('pg54');
model.result.remove('pg55');
model.result.remove('pg56');
model.result.remove('pg57');
model.result.remove('pg58');
model.result('pg27').run;
model.result('pg27').set('data', 'dset9');
model.result('pg27').run;
model.result('pg27').setIndex('looplevelinput', 'manual', 0);
model.result('pg27').setIndex('looplevel', [73], 0);
model.result('pg27').set('data', 'dset13');
model.result('pg27').run;
model.result('pg27').setIndex('looplevel', [57], 0);
model.result('pg27').run;
model.result('pg28').run;

model.study('std2').feature('time').set('solnum', 56);
model.study('std2').feature('time').set('notsolnum', 56);

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.sol('sol4').feature('t1').feature('fc1').set('ntolfact', 1);

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.batch('p2').run('compute');

model.result('pg20').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').setIndex('looplevelinput', 'manual', 2);
model.result('pg19').run;
model.result('pg19').feature.remove('ptgr2');
model.result('pg19').run;
model.result('pg52').run;
model.result('pg52').setIndex('looplevel', [4], 2);
model.result('pg52').run;
model.result('pg52').setIndex('looplevel', [5], 2);
model.result('pg52').run;
model.result('pg52').setIndex('looplevel', [4], 2);
model.result('pg52').run;
model.result('pg39').run;
model.result('pg39').set('data', 'dset11');
model.result('pg39').run;
model.result('pg39').setIndex('looplevelinput', 'manual', 2);
model.result('pg39').setIndex('looplevel', [5], 2);
model.result('pg39').run;
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [3], 2);
model.result('pg18').setIndex('looplevel', [4], 2);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [5], 2);
model.result('pg18').run;
model.result('pg53').run;
model.result('pg52').run;
model.result('pg52').run;
model.result('pg52').run;
model.result('pg52').run;
model.result('pg52').feature('ptgr1').set('expr', 'Dl_eff');
model.result('pg53').run;
model.result.remove('pg53');
model.result('pg52').run;
model.result('pg52').setIndex('looplevel', [5], 2);
model.result('pg52').run;
model.result('pg52').setIndex('looplevel', [4], 2);
model.result('pg52').run;
model.result('pg52').run;
model.result('pg52').run;
model.result('pg52').run;
model.result('pg52').run;
model.result('pg52').setIndex('looplevel', [3], 2);
model.result('pg52').run;
model.result('pg52').setIndex('looplevel', [2], 2);
model.result('pg52').run;
model.result('pg52').setIndex('looplevel', [1], 2);
model.result('pg52').run;
model.result('pg52').setIndex('looplevel', [5], 2);
model.result('pg52').run;
model.result('pg24').run;
model.result('pg24').run;
model.result('pg24').run;
model.result('pg24').set('data', 'dset11');
model.result('pg24').run;
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [4], 2);
model.result('pg18').run;
model.result('pg18').setIndex('looplevelinput', 'manualindices', 0);
model.result('pg18').setIndex('looplevelindices', 'range(1,10,96)', 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevelindices', 96, 0);
model.result('pg18').run;
model.result('pg18').run;
model.result('pg18').run;
model.result('pg18').setIndex('looplevelinput', 'all', 0);
model.result('pg18').run;
model.result('pg37').run;
model.result('pg37').setIndex('looplevelinput', 'all', 0);
model.result('pg37').setIndex('looplevel', [5], 2);
model.result('pg37').setIndex('looplevel', [4], 2);
model.result('pg37').run;
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [3], 2);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [4], 2);
model.result('pg18').run;
model.result('pg37').run;
model.result('pg37').setIndex('looplevel', [5], 2);
model.result('pg37').run;

model.study('std4').feature('param').setIndex('plistarr', '70/6 99/6', 0);

model.result.create('pg53', 'PlotGroup1D');
model.result('pg53').set('data', 'dset19');
model.result('pg53').create('lngr1', 'LineGraph');
model.result('pg53').feature('lngr1').set('xdata', 'expr');
model.result('pg53').feature('lngr1').set('xdataexpr', 'x');
model.result('pg53').feature('lngr1').selection.all;
model.result('pg53').feature('lngr1').set('expr', 'cl');
model.result.create('pg54', 'PlotGroup2D');
model.result('pg54').set('data', 'dset20');
model.result('pg54').create('surf1', 'Surface');
model.result('pg54').feature('surf1').set('expr', 'u');
model.result.create('pg55', 'PlotGroup2D');
model.result('pg55').set('data', 'dset20');
model.result('pg55').create('surf1', 'Surface');
model.result('pg55').feature('surf1').set('expr', 'cs');
model.result.create('pg56', 'PlotGroup1D');
model.result('pg56').set('data', 'dset19');
model.result('pg56').create('lngr1', 'LineGraph');
model.result('pg56').feature('lngr1').set('xdata', 'expr');
model.result('pg56').feature('lngr1').set('xdataexpr', 'x');
model.result('pg56').feature('lngr1').selection.all;
model.result('pg56').feature('lngr1').set('expr', 'uM');
model.result.create('pg57', 'PlotGroup1D');
model.result('pg57').set('data', 'dset19');
model.result('pg57').create('lngr1', 'LineGraph');
model.result('pg57').feature('lngr1').set('xdata', 'expr');
model.result('pg57').feature('lngr1').set('xdataexpr', 'x');
model.result('pg57').feature('lngr1').selection.all;
model.result('pg57').feature('lngr1').set('expr', 'epsl_l');

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.result.remove('pg53');
model.result.remove('pg54');
model.result.remove('pg55');
model.result.remove('pg56');
model.result.remove('pg57');

model.study('std4').feature('param').set('sweeptype', 'filled');

model.result.create('pg53', 'PlotGroup1D');
model.result('pg53').set('data', 'dset19');
model.result('pg53').create('lngr1', 'LineGraph');
model.result('pg53').feature('lngr1').set('xdata', 'expr');
model.result('pg53').feature('lngr1').set('xdataexpr', 'x');
model.result('pg53').feature('lngr1').selection.all;
model.result('pg53').feature('lngr1').set('expr', 'cl');
model.result.create('pg54', 'PlotGroup2D');
model.result('pg54').set('data', 'dset20');
model.result('pg54').create('surf1', 'Surface');
model.result('pg54').feature('surf1').set('expr', 'u');
model.result.create('pg55', 'PlotGroup2D');
model.result('pg55').set('data', 'dset20');
model.result('pg55').create('surf1', 'Surface');
model.result('pg55').feature('surf1').set('expr', 'cs');
model.result.create('pg56', 'PlotGroup1D');
model.result('pg56').set('data', 'dset19');
model.result('pg56').create('lngr1', 'LineGraph');
model.result('pg56').feature('lngr1').set('xdata', 'expr');
model.result('pg56').feature('lngr1').set('xdataexpr', 'x');
model.result('pg56').feature('lngr1').selection.all;
model.result('pg56').feature('lngr1').set('expr', 'uM');
model.result.create('pg57', 'PlotGroup1D');
model.result('pg57').set('data', 'dset19');
model.result('pg57').create('lngr1', 'LineGraph');
model.result('pg57').feature('lngr1').set('xdata', 'expr');
model.result('pg57').feature('lngr1').set('xdataexpr', 'x');
model.result('pg57').feature('lngr1').selection.all;
model.result('pg57').feature('lngr1').set('expr', 'epsl_l');

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.batch('p4').run('compute');

model.result('pg53').run;
model.result('pg19').run;

model.param.set('epsl_l_0', '0.68');
model.param.set('epsl_s_0', '1-0.15-epsl_l_0');

model.component('comp1').variable('var3').set('epsl_l_2', '(1-0.15-((cs_ave-cs_0_neg)*omega+1)*epsl_s_0/det_F_M)');
model.component('comp1').variable('var4').set('epsl_s', '1-0.15-epsl_l_1');

model.component('comp1').physics('dode').feature('aleq1').setIndex('f', 'epsl_l-(1-0.15-((cs_ave-cs_0_neg)*omega+1)*epsl_s_0/det_F_M)', 0);

model.param.set('L', '32[um]');

model.component('comp1').geom('geom2').run;

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.sol('sol1').runAll;

model.result('pg34').run;

model.sol('sol9').study('std3');

model.study('std3').feature('time').set('notlistsolnum', 1);
model.study('std3').feature('time').set('notsolnum', 'last');
model.study('std3').feature('time').set('listsolnum', 1);
model.study('std3').feature('time').set('solnum', 'last');

model.sol('sol9').feature.remove('t1');
model.sol('sol9').feature.remove('v1');
model.sol('sol9').feature.remove('st1');
model.sol('sol9').create('st1', 'StudyStep');
model.sol('sol9').feature('st1').set('study', 'std3');
model.sol('sol9').feature('st1').set('studystep', 'time');
model.sol('sol9').create('v1', 'Variables');
model.sol('sol9').feature('v1').set('control', 'time');
model.sol('sol9').create('t1', 'Time');
model.sol('sol9').feature('t1').set('tlist', 'range(0,10,600)');
model.sol('sol9').feature('t1').set('plot', 'off');
model.sol('sol9').feature('t1').set('plotgroup', 'pg34');
model.sol('sol9').feature('t1').set('plotfreq', 'tout');
model.sol('sol9').feature('t1').set('probesel', 'all');
model.sol('sol9').feature('t1').set('probes', {'pdom1' 'dom1'});
model.sol('sol9').feature('t1').set('probefreq', 'tsteps');
model.sol('sol9').feature('t1').set('atolglobalvaluemethod', 'factor');
model.sol('sol9').feature('t1').set('endtimeinterpolation', true);
model.sol('sol9').feature('t1').set('control', 'time');
model.sol('sol9').feature('t1').create('seDef', 'Segregated');
model.sol('sol9').feature('t1').create('fc1', 'FullyCoupled');
model.sol('sol9').feature('t1').feature('fc1').set('linsolver', 'dDef');
model.sol('sol9').feature('t1').feature.remove('fcDef');
model.sol('sol9').feature('t1').feature.remove('seDef');
model.sol('sol16').feature('v1').set('notsolnum', 'auto');
model.sol('sol16').feature('v1').set('notsolvertype', 'solnum');
model.sol('sol16').feature('v1').set('notlistsolnum', {'1'});
model.sol('sol16').feature('v1').set('notsolnum', 6);
model.sol('sol16').feature('v1').set('notlistsolnum', {'1'});
model.sol('sol16').feature('v1').set('notsolnum', '6');
model.sol('sol16').feature('v1').set('control', 'time');
model.sol('sol16').feature('v1').set('solnum', 'auto');
model.sol('sol16').feature('v1').set('solvertype', 'solnum');
model.sol('sol16').feature('v1').set('listsolnum', {'1'});
model.sol('sol16').feature('v1').set('solnum', 6);
model.sol('sol16').feature('v1').set('listsolnum', {'1'});
model.sol('sol16').feature('v1').set('solnum', '6');
model.sol('sol16').feature('v1').set('control', 'time');
model.sol('sol4').feature('v1').set('notsolnum', 'auto');
model.sol('sol4').feature('v1').set('notsolvertype', 'solnum');
model.sol('sol4').feature('v1').set('notlistsolnum', {'1'});
model.sol('sol4').feature('v1').set('notsolnum', 56);
model.sol('sol4').feature('v1').set('notlistsolnum', {'1'});
model.sol('sol4').feature('v1').set('notsolnum', '56');
model.sol('sol4').feature('v1').set('control', 'time');
model.sol('sol4').feature('v1').set('solnum', 'auto');
model.sol('sol4').feature('v1').set('solvertype', 'solnum');
model.sol('sol4').feature('v1').set('listsolnum', {'1'});
model.sol('sol4').feature('v1').set('solnum', 56);
model.sol('sol4').feature('v1').set('listsolnum', {'1'});
model.sol('sol4').feature('v1').set('solnum', '56');
model.sol('sol4').feature('v1').set('control', 'time');

model.study('std4').feature('time').set('notsolnum', 'auto');
model.study('std4').feature('time').set('notsolvertype', 'solnum');
model.study('std4').feature('time').set('notlistsolnum', {'1'});
model.study('std4').feature('time').set('notsolnum', 6);
model.study('std4').feature('time').set('notlistsolnum', {'1'});
model.study('std4').feature('time').set('notsolnum', '6');
model.study('std4').feature('time').set('notsolnumhide', 'off');
model.study('std4').feature('time').set('notstudyhide', 'off');
model.study('std4').feature('time').set('notsolhide', 'on');
model.study('std4').feature('time').set('solnum', 'auto');
model.study('std4').feature('time').set('solvertype', 'solnum');
model.study('std4').feature('time').set('listsolnum', {'1'});
model.study('std4').feature('time').set('solnum', 6);
model.study('std4').feature('time').set('listsolnum', {'1'});
model.study('std4').feature('time').set('solnum', '6');
model.study('std4').feature('time').set('solnumhide', 'off');
model.study('std4').feature('time').set('initstudyhide', 'off');
model.study('std4').feature('time').set('initsolhide', 'on');
model.study('std2').feature('time').set('notsolnum', 'auto');
model.study('std2').feature('time').set('notsolvertype', 'solnum');
model.study('std2').feature('time').set('notlistsolnum', {'1'});
model.study('std2').feature('time').set('notsolnum', 56);
model.study('std2').feature('time').set('notlistsolnum', {'1'});
model.study('std2').feature('time').set('notsolnum', '56');
model.study('std2').feature('time').set('notsolnumhide', 'off');
model.study('std2').feature('time').set('notstudyhide', 'off');
model.study('std2').feature('time').set('notsolhide', 'on');
model.study('std2').feature('time').set('solnum', 'auto');
model.study('std2').feature('time').set('solvertype', 'solnum');
model.study('std2').feature('time').set('listsolnum', {'1'});
model.study('std2').feature('time').set('solnum', 56);
model.study('std2').feature('time').set('listsolnum', {'1'});
model.study('std2').feature('time').set('solnum', '56');
model.study('std2').feature('time').set('solnumhide', 'off');
model.study('std2').feature('time').set('initstudyhide', 'off');
model.study('std2').feature('time').set('initsolhide', 'on');

model.sol('sol9').attach('std3');

model.batch('p3').feature.remove('so1');
model.batch('p3').create('so1', 'Solutionseq');
model.batch('p3').feature('so1').set('seq', 'sol9');
model.batch('p3').feature('so1').set('store', 'on');
model.batch('p3').feature('so1').set('clear', 'on');
model.batch('p3').feature('so1').set('psol', 'sol10');
model.batch('p3').set('pname', {'C'});
model.batch('p3').set('plistarr', {'0'});
model.batch('p3').set('sweeptype', 'sparse');
model.batch('p3').set('probesel', 'all');
model.batch('p3').set('probes', {'pdom1' 'dom1'});
model.batch('p3').set('plot', 'off');
model.batch('p3').set('err', 'on');
model.batch('p3').attach('std3');
model.batch('p3').set('control', 'param');

model.result.create('pg58', 'PlotGroup1D');
model.result('pg58').set('data', 'dset15');
model.result('pg58').create('lngr1', 'LineGraph');
model.result('pg58').feature('lngr1').set('xdata', 'expr');
model.result('pg58').feature('lngr1').set('xdataexpr', 'x');
model.result('pg58').feature('lngr1').selection.all;
model.result('pg58').feature('lngr1').set('expr', 'cl');
model.result.create('pg59', 'PlotGroup2D');
model.result('pg59').set('data', 'dset16');
model.result('pg59').create('surf1', 'Surface');
model.result('pg59').feature('surf1').set('expr', 'u');
model.result.create('pg60', 'PlotGroup2D');
model.result('pg60').set('data', 'dset16');
model.result('pg60').create('surf1', 'Surface');
model.result('pg60').feature('surf1').set('expr', 'cs');
model.result.create('pg61', 'PlotGroup1D');
model.result('pg61').set('data', 'dset15');
model.result('pg61').create('lngr1', 'LineGraph');
model.result('pg61').feature('lngr1').set('xdata', 'expr');
model.result('pg61').feature('lngr1').set('xdataexpr', 'x');
model.result('pg61').feature('lngr1').selection.all;
model.result('pg61').feature('lngr1').set('expr', 'uM');
model.result.create('pg62', 'PlotGroup1D');
model.result('pg62').set('data', 'dset15');
model.result('pg62').create('lngr1', 'LineGraph');
model.result('pg62').feature('lngr1').set('xdata', 'expr');
model.result('pg62').feature('lngr1').set('xdataexpr', 'x');
model.result('pg62').feature('lngr1').selection.all;
model.result('pg62').feature('lngr1').set('expr', 'epsl_l');

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.batch('p3').run('compute');

model.result('pg58').run;
model.result('pg30').run;
model.result('pg27').run;
model.result('pg27').setIndex('looplevel', [2], 0);
model.result('pg27').setIndex('looplevel', [60], 0);
model.result('pg27').setIndex('looplevel', [61], 0);
model.result('pg27').run;

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');
model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.batch('p2').run('compute');

model.result('pg20').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').feature('ptgr1').set('expr', 'ppb1[V]+(I_input-I_input_1C)*(0.01[V]/I_input_1C)');
model.result('pg19').run;
model.result('pg19').feature('ptgr1').set('expr', 'ppb1[V]+(I_input-I_input_1C)*(0.015[V]/I_input_1C)');
model.result('pg19').run;
model.result('pg19').run;
model.result('pg18').run;
model.result('pg18').setIndex('looplevelinput', 'manual', 2);
model.result('pg18').setIndex('looplevel', [5], 2);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [4], 2);
model.result('pg18').run;
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [3], 2);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [4], 2);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [5], 2);
model.result('pg18').run;
model.result('pg39').run;
model.result('pg2').run;
model.result('pg2').set('looplevel', [78 1 1]);
model.result('pg2').run;
model.result('pg2').set('looplevel', [91 1 5]);
model.result('pg2').run;
model.result('pg2').run;
model.result('pg2').set('looplevel', [83 1 5]);
model.result('pg2').run;
model.result('pg37').run;
model.result('pg37').run;
model.result('pg37').run;
model.result('pg37').setIndex('looplevelinput', 'manual', 2);
model.result('pg37').setIndex('looplevel', [5], 2);
model.result('pg37').run;
model.result('pg37').setIndex('looplevel', [4], 2);
model.result('pg37').run;
model.result('pg37').run;
model.result('pg37').run;
model.result('pg52').run;
model.result('pg40').run;
model.result('pg39').run;
model.result('pg37').run;
model.result('pg37').setIndex('looplevelinput', 'first', 0);
model.result('pg37').setIndex('looplevelinput', 'manualindices', 0);
model.result('pg37').setIndex('looplevelindices', 5, 0);
model.result('pg37').run;
model.result('pg37').setIndex('looplevel', [5], 2);
model.result('pg37').run;
model.result('pg37').run;
model.result('pg37').run;

model.component('comp1').physics('g2').feature('cons1').active(false);
model.component('comp1').physics('g2').feature('cons2').active(true);

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');
model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.sol('sol1').runAll;

model.result('pg34').run;

model.sol('sol9').study('std3');

model.study('std3').feature('time').set('notlistsolnum', 1);
model.study('std3').feature('time').set('notsolnum', 'last');
model.study('std3').feature('time').set('listsolnum', 1);
model.study('std3').feature('time').set('solnum', 'last');

model.sol('sol9').feature.remove('t1');
model.sol('sol9').feature.remove('v1');
model.sol('sol9').feature.remove('st1');
model.sol('sol9').create('st1', 'StudyStep');
model.sol('sol9').feature('st1').set('study', 'std3');
model.sol('sol9').feature('st1').set('studystep', 'time');
model.sol('sol9').create('v1', 'Variables');
model.sol('sol9').feature('v1').set('control', 'time');
model.sol('sol9').create('t1', 'Time');
model.sol('sol9').feature('t1').set('tlist', 'range(0,10,600)');
model.sol('sol9').feature('t1').set('plot', 'off');
model.sol('sol9').feature('t1').set('plotgroup', 'pg34');
model.sol('sol9').feature('t1').set('plotfreq', 'tout');
model.sol('sol9').feature('t1').set('probesel', 'all');
model.sol('sol9').feature('t1').set('probes', {'pdom1' 'dom1'});
model.sol('sol9').feature('t1').set('probefreq', 'tsteps');
model.sol('sol9').feature('t1').set('atolglobalvaluemethod', 'factor');
model.sol('sol9').feature('t1').set('endtimeinterpolation', true);
model.sol('sol9').feature('t1').set('control', 'time');
model.sol('sol9').feature('t1').create('seDef', 'Segregated');
model.sol('sol9').feature('t1').create('fc1', 'FullyCoupled');
model.sol('sol9').feature('t1').feature('fc1').set('linsolver', 'dDef');
model.sol('sol9').feature('t1').feature.remove('fcDef');
model.sol('sol9').feature('t1').feature.remove('seDef');
model.sol('sol16').feature('v1').set('notsolnum', 'auto');
model.sol('sol16').feature('v1').set('notsolvertype', 'solnum');
model.sol('sol16').feature('v1').set('notlistsolnum', {'1'});
model.sol('sol16').feature('v1').set('notsolnum', 6);
model.sol('sol16').feature('v1').set('notlistsolnum', {'1'});
model.sol('sol16').feature('v1').set('notsolnum', '6');
model.sol('sol16').feature('v1').set('control', 'time');
model.sol('sol16').feature('v1').set('solnum', 'auto');
model.sol('sol16').feature('v1').set('solvertype', 'solnum');
model.sol('sol16').feature('v1').set('listsolnum', {'1'});
model.sol('sol16').feature('v1').set('solnum', 6);
model.sol('sol16').feature('v1').set('listsolnum', {'1'});
model.sol('sol16').feature('v1').set('solnum', '6');
model.sol('sol16').feature('v1').set('control', 'time');
model.sol('sol4').feature('v1').set('notsolnum', 'auto');
model.sol('sol4').feature('v1').set('notsolvertype', 'solnum');
model.sol('sol4').feature('v1').set('notlistsolnum', {'1'});
model.sol('sol4').feature('v1').set('notsolnum', 56);
model.sol('sol4').feature('v1').set('notlistsolnum', {'1'});
model.sol('sol4').feature('v1').set('notsolnum', '56');
model.sol('sol4').feature('v1').set('control', 'time');
model.sol('sol4').feature('v1').set('solnum', 'auto');
model.sol('sol4').feature('v1').set('solvertype', 'solnum');
model.sol('sol4').feature('v1').set('listsolnum', {'1'});
model.sol('sol4').feature('v1').set('solnum', 56);
model.sol('sol4').feature('v1').set('listsolnum', {'1'});
model.sol('sol4').feature('v1').set('solnum', '56');
model.sol('sol4').feature('v1').set('control', 'time');

model.study('std4').feature('time').set('notsolnum', 'auto');
model.study('std4').feature('time').set('notsolvertype', 'solnum');
model.study('std4').feature('time').set('notlistsolnum', {'1'});
model.study('std4').feature('time').set('notsolnum', 6);
model.study('std4').feature('time').set('notlistsolnum', {'1'});
model.study('std4').feature('time').set('notsolnum', '6');
model.study('std4').feature('time').set('notsolnumhide', 'off');
model.study('std4').feature('time').set('notstudyhide', 'off');
model.study('std4').feature('time').set('notsolhide', 'on');
model.study('std4').feature('time').set('solnum', 'auto');
model.study('std4').feature('time').set('solvertype', 'solnum');
model.study('std4').feature('time').set('listsolnum', {'1'});
model.study('std4').feature('time').set('solnum', 6);
model.study('std4').feature('time').set('listsolnum', {'1'});
model.study('std4').feature('time').set('solnum', '6');
model.study('std4').feature('time').set('solnumhide', 'off');
model.study('std4').feature('time').set('initstudyhide', 'off');
model.study('std4').feature('time').set('initsolhide', 'on');
model.study('std2').feature('time').set('notsolnum', 'auto');
model.study('std2').feature('time').set('notsolvertype', 'solnum');
model.study('std2').feature('time').set('notlistsolnum', {'1'});
model.study('std2').feature('time').set('notsolnum', 56);
model.study('std2').feature('time').set('notlistsolnum', {'1'});
model.study('std2').feature('time').set('notsolnum', '56');
model.study('std2').feature('time').set('notsolnumhide', 'off');
model.study('std2').feature('time').set('notstudyhide', 'off');
model.study('std2').feature('time').set('notsolhide', 'on');
model.study('std2').feature('time').set('solnum', 'auto');
model.study('std2').feature('time').set('solvertype', 'solnum');
model.study('std2').feature('time').set('listsolnum', {'1'});
model.study('std2').feature('time').set('solnum', 56);
model.study('std2').feature('time').set('listsolnum', {'1'});
model.study('std2').feature('time').set('solnum', '56');
model.study('std2').feature('time').set('solnumhide', 'off');
model.study('std2').feature('time').set('initstudyhide', 'off');
model.study('std2').feature('time').set('initsolhide', 'on');

model.sol('sol9').attach('std3');

model.batch('p3').feature.remove('so1');
model.batch('p3').create('so1', 'Solutionseq');
model.batch('p3').feature('so1').set('seq', 'sol9');
model.batch('p3').feature('so1').set('store', 'on');
model.batch('p3').feature('so1').set('clear', 'on');
model.batch('p3').feature('so1').set('psol', 'sol10');
model.batch('p3').set('pname', {'C'});
model.batch('p3').set('plistarr', {'0'});
model.batch('p3').set('sweeptype', 'sparse');
model.batch('p3').set('probesel', 'all');
model.batch('p3').set('probes', {'pdom1' 'dom1'});
model.batch('p3').set('plot', 'off');
model.batch('p3').set('err', 'on');
model.batch('p3').attach('std3');
model.batch('p3').set('control', 'param');

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.batch('p3').run('compute');

model.result('pg58').run;

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.result('pg19').run;
model.result('pg19').create('ptgr2', 'PointGraph');
model.result('pg19').feature.move('ptgr2', 1);
model.result('pg19').feature('ptgr2').selection.set([1]);
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').feature('ptgr2').set('expr', 'ppb1[V]+(I_input-I_input_1C)*(0.015[V]/I_input_1C)');
model.result('pg19').feature('ptgr2').set('data', 'dset9');
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').feature('ptgr2').set('xdata', 'expr');
model.result('pg19').feature('ptgr2').set('xdataexpr', 't/3600*C');
model.result('pg19').run;
model.result('pg19').run;
model.result('pg18').run;
model.result('pg18').set('data', 'dset9');
model.result('pg18').run;
model.result('pg18').setIndex('looplevelinput', 'manual', 0);
model.result('pg18').setIndex('looplevel', [1], 0);
model.result('pg18').setIndex('looplevel', [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [66], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [62], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [59], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [58], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [55], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [52], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [45], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [42], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [37], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [30], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [24], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [67], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [68], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [67], 0);
model.result('pg18').run;
model.result('pg37').run;
model.result('pg37').setIndex('looplevel', [4], 2);
model.result('pg37').setIndex('looplevelinput', 'first', 0);
model.result('pg37').setIndex('looplevelinput', 'all', 0);
model.result('pg37').run;
model.result('pg37').setIndex('looplevel', [2], 2);
model.result('pg37').setIndex('looplevel', [3], 2);
model.result('pg37').run;
model.result('pg37').setIndex('looplevel', [4], 2);
model.result('pg37').run;
model.result('pg37').setIndex('looplevelinput', 'first', 0);
model.result('pg37').run;
model.result('pg35').run;
model.result('pg39').run;
model.result('pg39').setIndex('looplevelinput', 'manual', 2);
model.result('pg20').run;
model.result('pg53').run;
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [70], 0);
model.result('pg18').run;
model.result('pg18').run;
model.result('pg18').run;
model.result('pg18').set('data', 'dset11');
model.result('pg18').run;
model.result('pg52').run;
model.result('pg52').setIndex('looplevelinput', 'manual', 2);
model.result('pg52').setIndex('looplevel', [4], 2);
model.result('pg52').run;
model.result('pg52').set('data', 'dset9');
model.result('pg52').run;
model.result('pg41').set('window', 'window1');
model.result('pg41').run;
model.result('pg41').set('window', 'window1');
model.result('pg41').run;
model.result('pg41').set('window', 'window1');
model.result('pg41').run;
model.result('pg52').run;
model.result('pg52').run;
model.result('pg52').feature('ptgr1').selection.set([1]);
model.result('pg52').run;
model.result('pg52').run;
model.result('pg39').run;
model.result('pg37').run;
model.result('pg37').set('data', 'dset9');
model.result('pg37').run;
model.result('pg37').run;
model.result('pg37').run;
model.result('pg37').run;
model.result('pg37').run;
model.result('pg39').run;
model.result('pg39').run;
model.result('pg39').run;
model.result('pg39').set('data', 'dset9');
model.result('pg39').run;
model.result('pg39').setIndex('looplevelinput', 'manual', 0);
model.result('pg39').setIndex('looplevel', [2], 0);
model.result('pg39').setIndex('looplevel', [69], 0);
model.result('pg39').run;
model.result('pg39').setIndex('looplevel', [70], 0);
model.result('pg39').run;
model.result('pg18').run;
model.result('pg18').setIndex('looplevelinput', 'manual', 2);
model.result('pg18').setIndex('looplevel', [4], 2);
model.result('pg18').run;
model.result('pg18').set('data', 'dset9');
model.result('pg18').setIndex('looplevelinput', 'manual', 0);
model.result('pg18').setIndex('looplevel', [68], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [64], 0);
model.result('pg18').run;
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [47], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [40], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [38], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [35], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [26], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [22], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [17], 0);
model.result('pg18').run;
model.result('pg18').setIndex('looplevel', [11], 0);
model.result('pg18').run;
model.result('pg37').run;
model.result('pg37').run;
model.result('pg37').run;
model.result('pg19').run;
model.result('pg1').run;
model.result('pg1').run;
model.result('pg1').run;
model.result('pg23').run;
model.result('pg19').run;
model.result('pg1').run;
model.result('pg23').run;
model.result('pg23').run;
model.result('pg23').feature('ptgr1').set('xdata', 'expr');
model.result('pg23').feature('ptgr1').set('xdataexpr', 't/3600[s]*C');
model.result('pg23').run;
model.result('pg23').run;
model.result('pg38').run;
model.result('pg1').run;
model.result('pg8').run;
model.result('pg54').run;
model.result('pg53').run;
model.result('pg53').run;
model.result('pg53').run;
model.result('pg54').run;
model.result('pg54').run;
model.result('pg54').run;
model.result('pg55').run;
model.result('pg55').run;
model.result('pg55').run;
model.result('pg56').run;
model.result('pg57').run;
model.result.remove('pg57');
model.result.remove('pg58');
model.result.remove('pg59');
model.result.remove('pg60');
model.result.remove('pg61');
model.result.remove('pg62');
model.result('pg54').run;
model.result.remove('pg54');
model.result.remove('pg55');
model.result.remove('pg56');
model.result('pg10').run;
model.result('pg30').run;
model.result('pg27').run;
model.result('pg28').run;
model.result('pg19').run;
model.result('pg25').run;
model.result('pg29').run;
model.result('pg2').run;
model.result('pg33').run;
model.result('pg1').run;
model.result('pg22').run;
model.result('pg21').run;
model.result('pg21').run;
model.result('pg21').run;
model.result('pg24').run;
model.result('pg40').run;
model.result('pg45').run;
model.result('pg31').run;
model.result('pg36').run;
model.result('pg23').run;

model.func('int6').setIndex('table', 0.4, 6, 0);
model.func('int6').setIndex('table', 0.270462184856707, 6, 1);
model.func('int6').setIndex('table', 0.3, 7, 0);
model.func('int6').setIndex('table', 0.161119331558135, 7, 1);
model.func('int6').setIndex('table', 0.2, 8, 0);
model.func('int6').setIndex('table', 0.0627391329194658, 8, 1);
model.func('int6').setIndex('table', 0.1, 9, 0);
model.func('int6').setIndex('table', 0.031699850024753, 9, 1);
model.func('int6').setIndex('table', 0, 10, 0);
model.func('int6').setIndex('table', 0.01, 10, 1);
model.func('int6').setIndex('table', 0.4, 6, 0);
model.func('int6').setIndex('table', 0.270462184856707, 6, 1);
model.func('int6').setIndex('table', 0.3, 7, 0);
model.func('int6').setIndex('table', 0.161119331558135, 7, 1);
model.func('int6').setIndex('table', 0.2, 8, 0);
model.func('int6').setIndex('table', 0.0627391329194658, 8, 1);
model.func('int6').setIndex('table', 0.1, 9, 0);
model.func('int6').setIndex('table', 0.031699850024753, 9, 1);
model.func('int6').setIndex('table', 0, 10, 0);
model.func('int6').setIndex('table', 0.01, 10, 1);

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.result('pg37').run;
model.result('pg19').run;

model.label('Electrode_model_with_experiment_deLi_constant_P.mph');

model.func.create('int9', 'Interpolation');
model.func('int9').label('ECSA');
model.func('int9').set('funcname', 'S_v_int');
model.func('int9').setIndex('table', '0.343092286036790', 0, 0);
model.func('int9').setIndex('table', '', 0, 1);
model.func('int9').setIndex('table', 0.374001793855368, 1, 0);
model.func('int9').setIndex('table', '', 1, 1);
model.func('int9').setIndex('table', 0.404910435736404, 2, 0);
model.func('int9').setIndex('table', '', 2, 1);
model.func('int9').setIndex('table', 0.435819542204424, 3, 0);
model.func('int9').setIndex('table', '', 3, 1);
model.func('int9').setIndex('table', 0.466728718021602, 4, 0);
model.func('int9').setIndex('table', '', 4, 1);
model.func('int9').setIndex('table', '0.497637622220740', 5, 0);
model.func('int9').setIndex('table', '', 5, 1);
model.func('int9').setIndex('table', 0.528575581170815, 6, 0);
model.func('int9').setIndex('table', '', 6, 1);
model.func('int9').setIndex('table', 0.559988156121831, 7, 0);
model.func('int9').setIndex('table', '', 7, 1);
model.func('int9').setIndex('table', 0.590472493522265, 8, 0);
model.func('int9').setIndex('table', '', 8, 1);
model.func('int9').setIndex('table', '0.343092286036790', 0, 0);
model.func('int9').setIndex('table', '', 0, 1);
model.func('int9').setIndex('table', 0.374001793855368, 1, 0);
model.func('int9').setIndex('table', '', 1, 1);
model.func('int9').setIndex('table', 0.404910435736404, 2, 0);
model.func('int9').set