t('pg38').run;
model.result('pg60').run;
model.result('pg59').run;
model.result('pg60').run;
model.result('pg59').run;
model.result('pg19').run;
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').feature('surf1').set('expr', 'T_RR');
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [11 1 4]);
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [21 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [31 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [41 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [51 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [61 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [71 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [81 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [91 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [95 1 4]);
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').feature('surf1').set('expr', 'T_tt');
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [11 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [21 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [31 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [41 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [51 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [61 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [81 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [91 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [95 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [51 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [41 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [46 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [51 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [56 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [66 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [51 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [41 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [46 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [51 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [56 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [61 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [51 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [46 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [41 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [42 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [43 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [44 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [41 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [43 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [45 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [41 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [47 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [49 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [51 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [53 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [55 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [57 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [59 1 4]);
model.result('pg58').run;
model.result('pg38').run;
model.result('pg38').setIndex('looplevelindices', 'range(40,2,60)', 0);
model.result('pg38').run;
model.result('pg38').set('showlegends', true);
model.result('pg38').setIndex('looplevelindices', 'range(41,2,61)', 0);
model.result('pg38').run;
model.result('pg38').run;
model.result('pg38').setIndex('looplevel', [3], 2);
model.result('pg38').setIndex('looplevel', [4], 2);
model.result('pg38').run;
model.result('pg38').run;
model.result('pg38').feature('lngr1').set('linecolor', 'cycle');
model.result('pg58').run;
model.result('pg58').set('looplevel', [41 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [43 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [45 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [47 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [49 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [51 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [53 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [55 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [57 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [59 1 4]);
model.result('pg58').run;
model.result('pg38').run;
model.result('pg58').run;
model.result('pg38').run;
model.result('pg55').run;
model.result('pg55').setIndex('looplevel', [4], 2);
model.result('pg55').setIndex('looplevel', [5], 2);
model.result('pg55').setIndex('looplevel', [4], 2);
model.result('pg55').setIndex('looplevelinput', 'manualindices', 0);
model.result('pg55').setIndex('looplevelindices', 'range(41,2,61)', 0);
model.result('pg55').run;
model.result('pg25').run;
model.result('pg25').setIndex('looplevelinput', 'manual', 2);
model.result('pg25').setIndex('looplevel', [4], 2);
model.result('pg25').setIndex('looplevel', [5], 2);
model.result('pg25').setIndex('looplevel', [4], 2);
model.result('pg25').run;
model.result('pg25').setIndex('looplevelinput', 'manualindices', 0);
model.result('pg25').setIndex('looplevelindices', 'range(41,2,61)', 0);
model.result('pg25').run;

model.func('int6').setIndex('table', 0.270462184856707, 6, 1);

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.batch('p2').run('compute');

model.result('pg1').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [51 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [54 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [57 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [59 1 4]);
model.result('pg58').run;
model.result('pg38').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [41 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [46 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [51 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [56 1 4]);
model.result('pg58').run;
model.result('pg19').run;

model.func('int6').setIndex('table', 0.3, 7, 0);
model.func('int6').setIndex('table', 0.161119331558135, 7, 1);
model.func('int6').setIndex('table', 0.2, 8, 0);
model.func('int6').setIndex('table', 0.0627391329194658, 8, 1);
model.func('int6').setIndex('table', 0.1, 9, 0);
model.func('int6').setIndex('table', 0.031699850024753, 9, 1);
model.func('int6').setIndex('table', 0.3, 7, 0);
model.func('int6').setIndex('table', 0.161119331558135, 7, 1);
model.func('int6').setIndex('table', 0.2, 8, 0);
model.func('int6').setIndex('table', 0.0627391329194658, 8, 1);
model.func('int6').setIndex('table', 0.1, 9, 0);
model.func('int6').setIndex('table', 0.031699850024753, 9, 1);

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.batch('p2').run('compute');

model.result('pg1').run;
model.result('pg19').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [51 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [46 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [51 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [47 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [44 1 4]);
model.result('pg58').run;
model.result('pg38').run;
model.result('pg38').setIndex('looplevelinput', 'all', 0);
model.result('pg38').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [41 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [36 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [6 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [11 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [16 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [21 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [26 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [31 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [36 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [41 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [46 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [51 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [56 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [61 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [66 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [71 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [76 1 4]);
model.result('pg58').run;
model.result.table('evl2').addRow([1.2280221199034713E-5 2.0253232833056245E-6 0.05933317242959861], [0 0 0]);
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [11 1 4]);
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').feature('surf1').set('expr', 'T_RR');
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [21 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [31 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [41 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [51 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [61 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [71 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [81 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [91 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [94 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [51 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [46 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [41 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [43 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [45 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [47 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [49 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [51 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [53 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [55 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [57 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [59 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [61 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [63 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [41 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [43 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [45 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [47 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [49 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [51 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [53 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [55 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [57 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [59 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [11 1 4]);
model.result('pg58').run;
model.result('pg58').feature('surf1').set('expr', 'T_tt');
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [21 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [31 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [41 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [51 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [61 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [71 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [81 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [91 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [94 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [51 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [41 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [43 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [45 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [47 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [49 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [51 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [53 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [55 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [57 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [59 1 4]);
model.result('pg58').run;
model.result('pg38').run;
model.result('pg38').setIndex('looplevelinput', 'manualindices', 0);
model.result('pg38').run;
model.result('pg38').set('legendpos', 'lowermiddle');
model.result('pg38').setIndex('looplevelindices', 'range(41,4,61)', 0);
model.result('pg38').run;
model.result('pg38').setIndex('looplevelindices', 'range(41,2,61)', 0);
model.result('pg38').run;
model.result('pg38').set('showlegends', false);
model.result('pg58').run;
model.result('pg37').run;
model.result('pg37').setIndex('looplevelinput', 'manual', 2);
model.result('pg37').setIndex('looplevel', [4], 2);
model.result('pg37').setIndex('looplevelindices', '50 range(41,2,61)', 0);
model.result('pg37').setIndex('looplevelindices', 'range(41,2,61)', 0);
model.result('pg37').run;
model.result('pg55').run;
model.result('pg25').run;
model.result('pg25').setIndex('looplevelindices', 'range(61,2,71)', 0);
model.result('pg25').run;
model.result('pg25').setIndex('looplevelindices', 'range(61,2,81)', 0);
model.result('pg25').run;
model.result('pg25').setIndex('looplevelindices', 'range(71,2,81)', 0);
model.result('pg25').run;
model.result('pg30').run;
model.result('pg30').setIndex('looplevelinput', 'manualindices', 0);
model.result('pg30').setIndex('looplevelindices', 'range(41,2,61)', 0);
model.result('pg30').run;
model.result('pg55').run;
model.result('pg30').run;
model.result('pg30').setIndex('looplevelinput', 'all', 0);
model.result('pg30').run;
model.result('pg30').setIndex('looplevelinput', 'manualindices', 0);
model.result('pg30').run;
model.result('pg30').setIndex('looplevelindices', 'range(61,2,71)', 0);
model.result('pg30').run;
model.result('pg27').run;
model.result('pg59').run;
model.result('pg57').run;
model.result('pg60').run;
model.result('pg45').run;
model.result('pg29').run;
model.result('pg33').run;
model.result('pg37').run;
model.result('pg55').run;
model.result('pg30').run;
model.result('pg55').run;
model.result('pg30').run;
model.result('pg30').setIndex('looplevelindices', 'range(71,2,81)', 0);
model.result('pg30').run;
model.result('pg55').run;
model.result('pg55').setIndex('looplevelindices', 'range(71,2,81)', 0);
model.result('pg55').run;
model.result('pg55').run;
model.result('pg55').run;
model.result('pg55').setIndex('looplevelindices', 'range(61,2,71)', 0);
model.result('pg55').run;
model.result('pg55').setIndex('looplevelindices', 'range(41,2,61)', 0);
model.result('pg55').run;
model.result('pg30').run;
model.result('pg38').run;
model.result('pg38').setIndex('looplevelindices', 'range(61,2,71)', 0);
model.result('pg38').run;
model.result('pg38').setIndex('looplevelindices', 'range(31,2,41)', 0);
model.result('pg38').run;
model.result('pg38').setIndex('looplevelindices', 'range(71,2,81)', 0);
model.result('pg38').run;
model.result('pg38').set('showlegends', true);
model.result('pg38').setIndex('looplevelindices', 'range(31,2,41)', 0);
model.result('pg38').run;
model.result('pg38').set('legendpos', 'upperright');
model.result('pg37').run;

model.component('comp1').variable('var3').set('i0', 'max(eps^2,k_i0*i0_int1(cs_surf/cs_max_neg))');

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.batch('p2').run('compute');

model.result('pg1').run;
model.result('pg19').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [16 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [21 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [36 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [46 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [51 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [56 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [61 1 4]);
model.result('pg58').run;
model.result('pg38').run;
model.result('pg38').setIndex('looplevelindices', 'range(51,2,71)', 0);
model.result('pg38').run;
model.result('pg38').setIndex('looplevelindices', 'range(71,2,81)', 0);
model.result('pg38').run;
model.result('pg38').set('showlegends', false);
model.result('pg38').setIndex('looplevelindices', 'range(81,2,91)', 0);
model.result('pg38').run;
model.result('pg38').setIndex('looplevelindices', 'range(1,2,71)', 0);
model.result('pg38').run;
model.result('pg38').setIndex('looplevelindices', 'range(1,2,31)', 0);
model.result('pg38').run;
model.result('pg30').run;
model.result('pg30').setIndex('looplevelindices', 'range(1,2,31)', 0);
model.result('pg30').run;
model.result('pg58').run;
model.result('pg37').run;
model.result('pg37').setIndex('looplevelindices', 50, 0);
model.result('pg37').setIndex('looplevelinput', 'all', 2);
model.result('pg37').run;
model.result('pg37').setIndex('looplevelindices', 40, 0);
model.result('pg37').run;
model.result('pg37').setIndex('looplevelindices', 31, 0);
model.result('pg37').run;
model.result('pg55').run;
model.result('pg30').run;
model.result('pg37').run;
model.result('pg30').run;
model.result('pg37').run;

model.component('comp1').variable('var3').set('i0', 'max(eps^2,k_i0*i0_int1(cs_surf/cs_max_neg)*(max(cl[mol/m^3]/cl_ref,eps^2))^aa_neg)');

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.batch('p2').run('compute');

model.result('pg1').run;

model.label('Electrode_model_with_experiment_deLi_constant_thickness.mph');

model.result('pg1').run;

model.component('comp2').mesh('mesh3').feature('map1').feature('dis1').set('numelem', 30);
model.component('comp2').mesh('mesh3').run;
model.component('comp2').mesh('mesh3').feature('map1').feature('dis1').set('numelem', 50);
model.component('comp2').mesh('mesh3').run;

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');
model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.batch('p2').run('compute');

model.result('pg1').run;
model.result('pg58').run;

model.label('Electrode_model_with_experiment_deLi_constant_thickness.mph');

model.result('pg58').run;
model.result('pg19').run;
model.result('pg2').run;
model.result('pg38').run;
model.result('pg35').run;
model.result('pg37').run;
model.result('pg36').run;
model.result('pg33').run;
model.result('pg31').run;
model.result.remove('pg31');
model.result('pg29').run;
model.result('pg59').run;
model.result('pg59').setIndex('looplevel', [4], 2);
model.result('pg27').run;
model.result('pg59').run;
model.result('pg59').setIndex('looplevelinput', 'all', 0);
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').feature('lngr2').active(false);
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').feature('lngr1').active(true);
model.result('pg59').run;
model.result('pg59').feature('lngr1').active(false);
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').feature('lngr2').active(true);
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').feature('lngr1').set('legend', true);
model.result('pg59').feature('lngr2').set('legend', true);
model.result('pg59').set('showlegends', false);
model.result('pg27').run;
model.result('pg27').setIndex('looplevelinput', 'manual', 2);
model.result('pg27').setIndex('looplevel', [3], 2);
model.result('pg27').setIndex('looplevel', [4], 2);
model.result('pg27').setIndex('looplevelinput', 'all', 0);
model.result('pg27').run;
model.result('pg27').setIndex('looplevelinput', 'manualindices', 0);
model.result('pg27').setIndex('looplevelindices', '50 range(1,10,91)', 0);
model.result('pg27').setIndex('looplevelindices', 'range(1,10,91)', 0);
model.result('pg27').run;
model.result('pg57').run;
model.result('pg57').run;
model.result('pg57').feature('lngr1').set('expr', 'T_xx_M');
model.result('pg57').run;
model.result('pg45').run;
model.result('pg57').run;
model.result('pg60').run;
model.result('pg60').run;
model.result('pg60').feature('ptgr1').set('expr', 'T_xx_M');
model.result('pg60').run;
model.result('pg60').run;
model.result('pg57').run;
model.result('pg57').run;
model.result('pg57').run;
model.result('pg57').run;
model.result('pg57').feature('lngr1').set('expr', 'T_yy_M');
model.result('pg57').run;
model.result('pg57').run;
model.result('pg57').setIndex('looplevelindices', 50, 0);
model.result('pg57').run;
model.result('pg57').setIndex('looplevelinput', 'manual', 2);
model.result('pg57').setIndex('looplevel', [4], 2);
model.result('pg57').setIndex('looplevel', [5], 2);
model.result('pg57').setIndex('looplevel', [4], 2);
model.result('pg57').run;
model.result('pg57').setIndex('looplevelinput', 'all', 0);
model.result('pg57').run;
model.result('pg60').run;
model.result('pg35').run;
model.result('pg35').setIndex('looplevelinput', 'manual', 2);
model.result('pg35').setIndex('looplevel', [4], 2);
model.result('pg35').setIndex('looplevelinput', 'all', 0);
model.result('pg35').run;
model.result('pg35').setIndex('looplevelinput', 'manualindices', 0);
model.result('pg35').setIndex('looplevelindices', 'range(1,10,91)', 0);
model.result('pg35').run;
model.result('pg35').run;
model.result('pg35').run;
model.result('pg35').run;
model.result('pg35').feature('lngr1').set('legend', true);
model.result('pg35').feature('lngr1').set('expr', 'comp2.linext1(comp2.u)-rp_primary*(3^(1/3)-1)');
model.result('pg35').run;
model.result('pg35').run;
model.result('pg35').run;
model.result('pg35').feature('lngr1').set('expr', 'comp2.linext1(comp2.u)');
model.result('pg35').run;
model.result('pg35').run;
model.result('pg35').feature('lngr1').set('expr', 'comp2.linext1(comp2.u)+rp_primary');
model.result('pg35').run;
model.result('pg35').feature('lngr1').set('legend', true);
model.result('pg35').run;
model.result('pg35').run;
model.result('pg35').feature('lngr1').set('legendmethod', 'evaluated');
model.result('pg35').feature('lngr1').set('legendpattern', 'eval(t/3600[s]*C)');
model.result('pg35').run;
model.result('pg35').feature('lngr1').set('legendpattern', 'eval(t/3600[s]*C)');
model.result('pg35').run;
model.result('pg35').feature('lngr1').set('linewidth', 2);
model.result('pg35').run;
model.result('pg35').run;
model.result('pg24').run;
model.result('pg45').run;
model.result('pg45').run;
model.result('pg45').feature('lngr1').set('linewidth', 2);
model.result('pg45').run;
model.result('pg45').setIndex('looplevelinput', 'manual', 2);
model.result('pg45').setIndex('looplevel', [4], 2);
model.result('pg45').setIndex('looplevelinput', 'manualindices', 0);
model.result('pg45').setIndex('looplevelindices', 'range(1,10,91)', 0);
model.result('pg45').run;
model.result('pg45').run;
model.result('pg45').feature('lngr1').set('legend', true);
model.result('pg45').feature('lngr1').set('legendmethod', 'evaluated');
model.result('pg45').feature('lngr1').set('legendpattern', 'eval(t/3600[s]*C)');
model.result('pg45').run;
model.result('pg45').run;
model.result('pg45').set('legendpos', 'lowerright');
model.result('pg38').run;
model.result('pg38').setIndex('looplevelinput', 'all', 0);
model.result('pg38').run;
model.result('pg38').run;
model.result('pg38').run;
model.result('pg38').run;
model.result.export.create('plot1', 'pg38', 'lngr1', 'Plot');
model.result.export('plot1').set('filename', 'F:\group\Research\Mechanic-electrochemic coupling method\Network model for electrode\Rate performance test 2 G5\j_react_10C.txt');
model.result.export('plot1').run;
model.result('pg38').run;
model.result('pg38').setIndex('looplevelinput', 'manualindices', 0);
model.result('pg38').run;
model.result('pg38').setIndex('looplevelinput', 'all', 0);
model.result('pg38').run;
model.result('pg45').run;
model.result('pg45').setIndex('looplevelinput', 'all', 0);
model.result('pg45').run;
model.result('pg45').run;
model.result.export.create('plot2', 'pg45', 'lngr1', 'Plot');
model.result.export('plot2').set('filename', 'F:\group\Research\Mechanic-electrochemic coupling method\Network model for electrode\Rate performance test 2 G5\uM_10C.txt');
model.result.export('plot2').run;
model.result('pg45').run;
model.result('pg35').run;
model.result('pg35').setIndex('looplevelinput', 'all', 0);
model.result('pg35').run;
model.result('pg35').run;
model.result.export.create('plot3', 'pg35', 'lngr1', 'Plot');
model.result.export('plot3').set('filename', 'F:\group\Research\Mechanic-electrochemic coupling method\Network model for electrode\Rate performance test 2 G5\Rp_10C.txt');
model.result.export('plot3').run;
model.result('pg35').run;
model.result('pg37').run;
model.result('pg37').setIndex('looplevelindices', 51, 0);
model.result('pg37').run;
model.result('pg37').run;
model.result('pg37').feature('lngr1').set('legend', true);
model.result('pg37').feature('lngr1').set('legendmethod', 'manual');
model.result('pg37').feature('lngr1').setIndex('legends', '1C', 0);
model.result('pg37').feature('lngr1').setIndex('legends', '2C', 1);
model.result('pg37').feature('lngr1').setIndex('legends', '5C', 2);
model.result('pg37').feature('lngr1').setIndex('legends', '10C', 3);
model.result('pg37').feature('lngr1').setIndex('legends', '14C', 4);
model.result('pg37').run;
model.result('pg37').setIndex('looplevelindices', 11, 0);
model.result('pg37').run;
model.result('pg37').setIndex('looplevelindices', 21, 0);
model.result('pg37').run;
model.result('pg37').setIndex('looplevelindices', 31, 0);
model.result('pg37').run;
model.result('pg37').setIndex('looplevelindices', 41, 0);
model.result('pg37').run;
model.result('pg37').setIndex('looplevelindices', 51, 0);
model.result('pg37').run;
model.result('pg37').run;
model.result('pg37').feature('lngr1').set('linewidth', 2);
model.result('pg37').run;
model.result('pg35').run;
model.result('pg38').run;
model.result('pg58').run;
model.result('pg2').run;

model.label('Electrode_model_with_experiment_deLi_constant_thickness.mph');

model.result('pg2').run;
model.result('pg37').run;
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [11 1 4]);
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').feature('surf1').set('expr', 'T_RR');
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [21 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [31 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [41 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [51 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [61 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [71 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [81 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [91 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [94 1 4]);
model.result('pg58').run;
model.result('pg19').run;
model.result('pg58').run;
model.result('pg58').feature('surf1').set('expr', 'T_tt');
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [91 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [81 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [71 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [61 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [51 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [41 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [31 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [21 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [11 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [41 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [43 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [45 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [47 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [49 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [51 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [53 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [55 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [57 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [59 1 4]);
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').feature('surf1').set('expr', 'T_RR');
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').set('looplevel', [57 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [55 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [53 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [51 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [49 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [47 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [45 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [43 1 4]);
model.result('pg58').run;
model.result('pg58').set('looplevel', [41 1 4]);
model.result('pg58').run;
model.result('pg58').run;
model.result('pg58').run;
model.result('pg37').run;
model.result('pg37').run;
model.result('pg37').run;

model.label('Electrode_model_with_experiment_deLi_constant_thickness.mph');

model.result('pg37').run;
model.result('pg58').run;
model.result('pg35').run;
model.result('pg2').run;
model.result('pg55').run;
model.result('pg55').setIndex('looplevel', [5], 2);
model.result('pg55').run;
model.result('pg55').setIndex('looplevel', [4], 2);
model.result('pg55').run;
model.result('pg55').setIndex('looplevel', [5], 2);
model.result('pg55').setIndex('looplevel', [4], 2);
model.result('pg55').setIndex('looplevel', [5], 2);
model.result('pg55').run;
model.result('pg55').setIndex('looplevel', [4], 2);
model.result('pg55').run;
model.result('pg25').run;
model.result('pg27').run;
model.result('pg59').run;
model.result('pg57').run;
model.result('pg60').run;
model.result('pg45').run;
model.result('pg29').run;
model.result('pg33').run;
model.result('pg45').run;

model.study.create('std4');
model.study('std4').create('time', 'Transient');
model.study('std4').feature('time').setSolveFor('/physics/g', true);
model.study('std4').feature('time').setSolveFor('/physics/g3', true);
model.study('std4').feature('time').setSolveFor('/physics/g4', true);
model.study('std4').feature('time').setSolveFor('/physics/g2', true);
model.study('std4').feature('time').setSolveFor('/physics/dode', true);
model.study('std4').feature('time').set('tlist', 'range(0,3600/C/100,3600/C)');

model.sol.create('sol146');
model.sol('sol146').study('std4');

model.study('std4').feature('time').set('notlistsolnum', 1);
model.study('std4').feature('time').set('notsolnum', 'auto');
model.study('std4').feature('time').set('listsolnum', 1);
model.study('std4').feature('time').set('solnum', 'auto');

model.sol('sol146').create('st1', 'StudyStep');
model.sol('sol146').feature('st1').set('study', 'std4');
model.sol('sol146').feature('st1').set('studystep', 'time');
model.sol('sol146').create('v1', 'Variables');
model.sol('sol146').feature('v1').set('control', 'time');
model.sol('sol146').create('t1', 'Time');
model.sol('sol146').feature('t1').set('tlist', 'range(0,3600/C/100,3600/C)');
model.sol('sol146').feature('t1').set('plot', 'off');
model.sol('sol146').feature('t1').set('plotgroup', 'pg34');
model.sol('sol146').feature('t1').set('plotfreq', 'tout');
model.sol('sol146').feature('t1').set('probesel', 'all');
model.sol('sol146').feature('t1').set('probes', {'pdom1' 'pdom2' 'dom1'});
model.sol('sol146').feature('t1').set('probefreq', 'tsteps');
model.sol('sol146').feature('t1').set('atolglobalvaluemethod', 'factor');
model.sol('sol146').feature('t1').set('endtimeinterpolation', true);
model.sol('sol146').feature('t1').set('control', 'time');
model.sol('sol146').feature('t1').create('seDef', 'Segregated');
model.sol('sol146').feature('t1').create('fc1', 'FullyCoupled');
model.sol('sol146').feature('t1').feature('fc1').set('linsolver', 'dDef');
model.sol('sol146').feature('t1').feature.remove('fcDef');
model.sol('sol146').feature('t1').feature.remove('seDef');
model.sol('sol146').attach('std4');
model.sol('sol146').feature('t1').create('st1', 'StopCondition');
model.sol('sol146').feature('t1').feature('st1').setIndex('stopcondarr', '', 0);
model.sol('sol146').feature('t1').feature('st1').setIndex('stopcondterminateon', 'true', 0);
model.sol('sol146').feature('t1').feature('st1').setIndex('stopcondActive', true, 0);
model.sol('sol146').feature('t1').feature('st1').setIndex('stopconddesc', [native2unicode(hex2dec({'50' '5c'}), 'unicode')  native2unicode(hex2dec({'6b' '62'}), 'unicode')  native2unicode(hex2dec({'88' '68'}), 'unicode')  native2unicode(hex2dec({'8f' 'be'}), 'unicode')  native2unicode(hex2dec({'5f' '0f'}), 'unicode') ' 1'], 0);
model.sol('sol146').feature('t1').feature('st1').setIndex('stopcondarr', '', 0);
model.sol('sol146').feature('t1').feature('st1').setIndex('stopcondterminateon', 'true', 0);
model.sol('sol146').feature('t1').feature('st1').setIndex('stopcondActive', true, 0);
model.sol('sol146').feature('t1').feature('st1').setIndex('stopconddesc', [native2unicode(hex2dec({'50' '5c'}), 'unicode')  native2unicode(hex2dec({'6b' '62'}), 'unicode')  native2unicode(hex2dec({'88' '68'}), 'unicode')  native2unicode(hex2dec({'8f' 'be'}), 'unicode')  native2unicode(hex2dec({'5f' '0f'}), 'unicode') ' 1'], 0);
model.sol('sol146').feature('t1').feature('st1').setIndex('stopcondarr', 'comp1.ppb1>2', 0);
model.sol('sol146').feature('t1').feature('fc1').set('dtech', 'auto');
model.sol('sol146').feature('t1').feature('fc1').set('ntolfact', 0.001);
model.sol('sol146').feature('t1').feature('fc1').set('maxiter', 250);
model.sol('sol146').feature('t1').feature('fc1').set('dtech', 'hnlin');

model.study('std4').create('param', 'Parametric');
model.study('std4').feature('param').setIndex('pname', 'aa_neg', 0);
model.study('std4').feature('param').setIndex('plistarr', '', 0);
model.study('std4').feature('param').setIndex('punit', '', 0);
model.study('std4').feature('param').setIndex('pname', 'aa_neg', 0);
model.study('std4').feature('param').setIndex('plistarr', '', 0);
model.study('std4').feature('param').setIndex('punit', '', 0);
model.study('std4').feature('param').setIndex('pname', 'C', 0);
model.study('std4').feature('param').setIndex('pname', 'aa_neg', 1);
model.study('std4').feature('param').setIndex('plistarr', '', 1);
model.study('std4').feature('param').setIndex('punit', '', 1);
model.study('std4').feature('param').setIndex('pname', 'aa_neg', 1);
model.study('std4').feature('param').setIndex('plistarr', '', 1);
model.study('std4').feature('param').setIndex('punit', '', 1);
model.study('std4').feature('param').setIndex('pname', 'Flag', 1);
model.study('std4').feature('param').setIndex('plistarr', -1, 1);
model.study('std4').feature('param').setIndex('plistarr', 20, 0);

model.batch.create('p4', 'Parametric');
model.batch('p4').study('std4');
model.batch('p4').create('so1', 'Solutionseq');
model.batch('p4').feature('so1').set('seq', 'sol146');
model.batch('p4').feature('so1').set('store', 'on');
model.batch('p4').feature('so1').set('clear', 'on');
model.batch('p4').feature('so1').set('psol', 'none');
model.batch('p4').set('pname', {'C' 'Flag'});
model.batch('p4').set('plistarr', {'20' '-1'});
model.batch('p4').set('sweeptype', 'sparse');
model.batch('p4').set('probesel', 'all');
model.batch('p4').set('probes', {'pdom1' 'pdom2' 'dom1'});
model.batch('p4').set('plot', 'off');
model.batch('p4').set('err', 'on');
model.batch('p4').attach('std4');
model.batch('p4').set('control', 'param');

model.sol.create('sol147');
model.sol('sol147').study('std4');
model.sol('sol147').label([native2unicode(hex2dec({'53' 'c2'}), 'unicode')  native2unicode(hex2dec({'65' '70'}), 'unicode')  native2unicode(hex2dec({'53' '16'}), 'unicode')  native2unicode(hex2dec({'89' 'e3'}), 'unicode') ' 3']);

model.batch('p4').feature('so1').set('psol', 'sol147');

model.result.create('pg61', 'PlotGroup1D');
model.result('pg61').set('data', 'dset19');
model.result('pg61').create('lngr1', 'LineGraph');
model.result('pg61').feature('lngr1').set('xdata', 'expr');
model.result('pg61').feature('lngr1').set('xdataexpr', 'x');
model.result('pg61').feature('lngr1').selection.all;
model.result('pg61').feature('lngr1').set('expr', 'cl');
model.result.create('pg62', 'PlotGroup2D');
model.result('pg62').set('data', 'dset20');
model.result('pg62').create('surf1', 'Surface');
model.result('pg62').feature('surf1').set('expr', 'u');
model.result.create('pg63', 'PlotGroup2D');
model.result('pg63').set('data', 'dset20');
model.result('pg63').create('surf1', 'Surface');
model.result('pg63').feature('surf1').set('expr', 'cs');
model.result.create('pg64', 'PlotGroup1D');
model.result('pg64').set('data', 'dset19');
model.result('pg64').create('lngr1', 'LineGraph');
model.result('pg64').feature('lngr1').set('xdata', 'expr');
model.result('pg64').feature('lngr1').set('xdataexpr', 'x');
model.result('pg64').feature('lngr1').selection.all;
model.result('pg64').feature('lngr1').set('expr', 'uM');
model.result.create('pg65', 'PlotGroup1D');
model.result('pg65').set('data', 'dset19');
model.result('pg65').create('lngr1', 'LineGraph');
model.result('pg65').feature('lngr1').set('xdata', 'expr');
model.result('pg65').feature('lngr1').set('xdataexpr', 'x');
model.result('pg65').feature('lngr1').selection.all;
model.result('pg65').feature('lngr1').set('expr', 'epsl_l');

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.result.remove('pg63');
model.result.remove('pg64');
model.result.remove('pg65');
model.result.remove('pg61');
model.result.remove('pg62');

model.study('std4').feature('time').set('useinitsol', true);
model.study('std4').feature('time').set('initmethod', 'sol');
model.study('std4').feature('time').set('initstudy', 'std3');
model.study('std4').feature('time').set('solnum', 'last');
model.study('std4').feature('time').set('usesol', true);
model.study('std4').feature('time').set('notsolmethod', 'sol');
model.study('std4').feature('time').set('notstudy', 'std3');
model.study('std4').feature('time').set('notsolnum', 'last');

model.result.create('pg61', 'PlotGroup1D');
model.result('pg61').set('data', 'dset19');
model.result('pg61').create('lngr1', 'LineGraph');
model.result('pg61').feature('lngr1').set('xdata', 'expr');
model.result('pg61').feature('lngr1').set('xdataexpr', 'x');
model.result('pg61').feature('lngr1').selection.all;
model.result('pg61').feature('lngr1').set('expr', 'cl');
model.result.create('pg62', 'PlotGroup2D');
model.result('pg62').set('data', 'dset20');
model.result('pg62').create('surf1', 'Surface');
model.result('pg62').feature('surf1').set('expr', 'u');
model.result.create('pg63', 'PlotGroup2D');
model.result('pg63').set('data', 'dset20');
model.result('pg63').create('surf1', 'Surface');
model.result('pg63').feature('surf1').set('expr', 'cs');
model.result.create('pg64', 'PlotGroup1D');
model.result('pg64').set('data', 'dset19');
model.result('pg64').create('lngr1', 'LineGraph');
model.result('pg64').feature('lngr1').set('xdata', 'expr');
model.result('pg64').feature('lngr1').set('xdataexpr', 'x');
model.result('pg64').feature('lngr1').selection.all;
model.result('pg64').feature('lngr1').set('expr', 'uM');
model.result.create('pg65', 'PlotGroup1D');
model.result('pg65').set('data', 'dset19');
model.result('pg65').create('lngr1', 'LineGraph');
model.result('pg65').feature('lngr1').set('xdata', 'expr');
model.result('pg65').feature('lngr1').set('xdataexpr', 'x');
model.result('pg65').feature('lngr1').selection.all;
model.result('pg65').feature('lngr1').set('expr', 'epsl_l');

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.batch('p4').run('compute');

model.result('pg61').run;
model.result('pg65').run;
model.result('pg61').run;
model.result.remove('pg61');
model.result.remove('pg62');
model.result.remove('pg63');
model.result.remove('pg64');
model.result.remove('pg65');
model.result('pg55').run;
model.result('pg55').setIndex('looplevel', [5], 2);
model.result('pg55').run;
model.result('pg55').set('data', 'dset19');
model.result('pg55').run;
model.result('pg19').run;
model.result('pg19').create('ptgr2', 'PointGraph');
model.result('pg19').feature.move('ptgr2', 1);
model.result('pg19').feature('ptgr2').set('data', 'dset19');
model.result('pg19').feature('ptgr2').selection.set([1]);
model.result('pg19').feature('ptgr2').set('expr', 'phis');
model.result('pg19').run;
model.result('pg19').feature('ptgr2').set('xdata', 'expr');
model.result('pg19').feature('ptgr2').set('xdataexpr', 't/3600[s]*C');
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').feature('tblp6').active(true);
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').feature('ptgr2').set('linewidth', 2);
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').feature('ptgr2').set('expr', 'phis+(I_input-I_input_1C)*(0.01[V]/I_input_1C)');
model.result('pg19').run;
model.result('pg19').run;
model.result('pg55').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').feature('ptgr1').set('expr', 'ppb1[V]+(I_input-I_input_1C)*(0.01[V]/I_input_1C)');
model.result('pg19').run;
model.result('pg19').feature('ptgr1').set('expr', 'ppb1[V]+(I_input-I_input_1C)*(0.0[V]/I_input_1C)');
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').feature('ptgr2').set('expr', 'phis+(I_input-I_input_1C)*(0.0[V]/I_input_1C)');
model.result('pg19').run;
model.result('pg19').run;
model.result.create('pg61', 'PlotGroup1D');
model.result('pg61').run;
model.result.move('pg61', 25);
model.result('pg61').label('phil');
model.result('pg19').run;
model.result('pg61').run;
model.result('pg61').create('lngr1', 'LineGraph');
model.result('pg61').feature('lngr1').selection.set([1]);
model.result('pg61').feature('lngr1').set('expr', 'phil');
model.result('pg61').run;
model.result('pg61').set('data', 'dset19');
model.result('pg61').run;
model.result.create('pg62', 'PlotGroup1D');
model.result('pg62').run;
model.result.move('pg62', 27);
model.result('pg62').set('data', 'dset19');
model.result('pg62').create('lngr1', 'LineGraph');
model.result('pg62').feature('lngr1').selection.set([1]);
model.result('pg62').run;
model.result('pg62').label('kl_eff');
model.result('pg62').run;
model.result('pg62').feature('lngr1').set('expr', 'kl_eff');
model.result('pg62').run;
model.result('pg62').run;
model.result('pg62').set('ylog', true);
model.result('pg62').set('showmanualgrid', true);
model.result('pg62').set('showxspacing', true);
model.result('pg62').set('showyspacing', false);
model.result('pg62').set('showsecyspacing', false);
model.result('pg62').set('showsecyextra', false);

model.func('an2').set('funcname', 'kl_an1_1');
model.func('an5').set('funcname', 'Dl_an1_1');
model.func('an4').set('funcname', 'kl_an1');
model.func('an3').set('funcname', 'Dl_an1');

model.component('comp1').probe('pdom1').genResult('none');
model.component('comp1').probe('pdom2').genResult('none');
model.component('comp1').probe('dom1').genResult('none');

model.batch('p4').run('compute');

model.result('pg55').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').run;
model.result('pg19').feature('ptgr2').set('legend', true);
model.result('pg19').feature('ptgr2').set('legendmethod', 'manual');
model.result('pg19').feature('ptgr2').setIndex('legends', '20C', 0);
model.result('pg19').run;
model.result('pg19').run;
model.result('pg61').run;
model.result('pg30').run;
model.result('pg24').run;
model.result('pg23').run;
model.result('pg27').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').setIndex('looplevelinput', 'all', 2);
model.result('pg59').setIndex('looplevelinput', 'manualindices', 0);
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').feature('lngr1').label('T_tt_1');
model.result('pg59').run;
model.result('pg59').create('lngr3', 'LineGraph');
model.result('pg59').feature.move('lngr3', 1);
model.result('pg59').feature('lngr3').label('T_tt_2');
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').feature('lngr2').active(false);
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').feature('lngr1').active(true);
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').run;
model.result.dataset('cln2').set('genparaactive', true);
model.result.dataset.move('cln3', 17);
model.result.dataset('cln3').set('data', 'dset20');
model.result.dataset('cln3').setIndex('genpoints', '5e-5', 0, 0);
model.result.dataset('cln3').setIndex('genpoints', '5e-5', 1, 0);
model.result.dataset('cln3').set('genparaactive', true);
model.result.dataset('cln3').set('genparadist', 'range(1.0e-5,1.0e-5,5.0e-5)');
model.result('pg59').feature('lngr1').set('data', 'cln2');
model.result('pg59').feature('lngr1').setIndex('looplevelinput', 'manualindices', 0);
model.result('pg59').feature('lngr1').setIndex('looplevelindices', 51, 0);
model.result('pg59').run;
model.result.dataset('cln2').setIndex('genpoints', 2.69E-6, 1, 1);
model.result('pg59').run;
model.result('pg59').run;
model.result.dataset('cln2').set('genparaactive', true);
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').feature('lngr3').set('data', 'cln3');
model.result('pg59').feature('lngr1').set('xdata', 'arc');
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').feature('lngr3').setIndex('looplevelinput', 'manualindices', 0);
model.result('pg59').feature('lngr3').setIndex('looplevelindices', 51, 0);
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').feature('lngr3').set('expr', 'T_tt');
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').set('showlegends', true);
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').run;
model.result('pg59').feature('lngr3').set('cutline', 'cln3');
model.result('pg59').feature('lngr3').set('linefirst', [2.499999936844688E-5 0 0]);
model.result('pg59').feature('lngr3').set('linesecond', [2.499999936844688E-5 2.6899999738816405E-6 0]);
model.result('pg59').feature('lngr3').set('lineisinit', true);
model.result.dataset('cln3').set('method', 'twopoint');
model.result.dataset('c